// packages/vue/src/components/BubbleMenuToolbar.vue
<script setup lang="ts">
import type { Editor } from "@vizel/core";
import { computed, ref } from "vue";
import { useEditorState } from "../composables/useEditorState.ts";
import BubbleMenuButton from "./BubbleMenuButton.vue";
import BubbleMenuColorPicker from "./BubbleMenuColorPicker.vue";
import BubbleMenuLinkEditor from "./BubbleMenuLinkEditor.vue";

export interface BubbleMenuToolbarProps {
  /** The editor instance */
  editor: Editor;
  /** Custom class name */
  class?: string;
}

const props = defineProps<BubbleMenuToolbarProps>();

// Subscribe to editor state changes to update active states
const editorStateVersion = useEditorState(() => props.editor);

// Create computed properties that depend on editorStateVersion to trigger re-renders
const isBoldActive = computed(() => {
  void editorStateVersion.value; // Trigger reactivity
  return props.editor.isActive("bold");
});
const isItalicActive = computed(() => {
  void editorStateVersion.value;
  return props.editor.isActive("italic");
});
const isStrikeActive = computed(() => {
  void editorStateVersion.value;
  return props.editor.isActive("strike");
});
const isUnderlineActive = computed(() => {
  void editorStateVersion.value;
  return props.editor.isActive("underline");
});
const isCodeActive = computed(() => {
  void editorStateVersion.value;
  return props.editor.isActive("code");
});
const isLinkActive = computed(() => {
  void editorStateVersion.value;
  return props.editor.isActive("link");
});

const showLinkEditor = ref(false);
</script>

<template>
  <BubbleMenuLinkEditor
    v-if="showLinkEditor"
    :editor="props.editor"
    @close="showLinkEditor = false"
  />
  <div v-else :class="['vizel-bubble-menu-toolbar', $props.class]">
    <BubbleMenuButton
      action="bold"
      :is-active="isBoldActive"
      title="Bold (Cmd+B)"
      @click="props.editor.chain().focus().toggleBold().run()"
    >
      <strong>B</strong>
    </BubbleMenuButton>
    <BubbleMenuButton
      action="italic"
      :is-active="isItalicActive"
      title="Italic (Cmd+I)"
      @click="props.editor.chain().focus().toggleItalic().run()"
    >
      <em>I</em>
    </BubbleMenuButton>
    <BubbleMenuButton
      action="strike"
      :is-active="isStrikeActive"
      title="Strikethrough"
      @click="props.editor.chain().focus().toggleStrike().run()"
    >
      <s>S</s>
    </BubbleMenuButton>
    <BubbleMenuButton
      action="underline"
      :is-active="isUnderlineActive"
      title="Underline (Cmd+U)"
      @click="props.editor.chain().focus().toggleUnderline().run()"
    >
      <u>U</u>
    </BubbleMenuButton>
    <BubbleMenuButton
      action="code"
      :is-active="isCodeActive"
      title="Code (Cmd+E)"
      @click="props.editor.chain().focus().toggleCode().run()"
    >
      <code>&lt;/&gt;</code>
    </BubbleMenuButton>
    <BubbleMenuButton
      action="link"
      :is-active="isLinkActive"
      title="Link (Cmd+K)"
      @click="showLinkEditor = true"
    >
      <span>L</span>
    </BubbleMenuButton>
    <BubbleMenuColorPicker :editor="props.editor" type="textColor" />
    <BubbleMenuColorPicker :editor="props.editor" type="highlight" />
  </div>
</template>

// packages/svelte/src/components/BubbleMenuToolbar.svelte
<script lang="ts" module>
import type { Editor } from "@vizel/core";

export interface BubbleMenuToolbarProps {
  /** The editor instance */
  editor: Editor;
  /** Custom class name */
  class?: string;
}
</script>

<script lang="ts">
import { useEditorState } from "../runes/useEditorState.svelte.ts";
import BubbleMenuButton from "./BubbleMenuButton.svelte";
import BubbleMenuColorPicker from "./BubbleMenuColorPicker.svelte";
import BubbleMenuLinkEditor from "./BubbleMenuLinkEditor.svelte";

let { editor, class: className }: BubbleMenuToolbarProps = $props();
let showLinkEditor = $state(false);

// Subscribe to editor state changes to update active states
const editorState = useEditorState(() => editor);

// Create derived values that depend on editorState.current to trigger re-renders
const isBoldActive = $derived.by(() => {
  void editorState.current; // Trigger reactivity
  return editor.isActive("bold");
});
const isItalicActive = $derived.by(() => {
  void editorState.current;
  return editor.isActive("italic");
});
const isStrikeActive = $derived.by(() => {
  void editorState.current;
  return editor.isActive("strike");
});
const isUnderlineActive = $derived.by(() => {
  void editorState.current;
  return editor.isActive("underline");
});
const isCodeActive = $derived.by(() => {
  void editorState.current;
  return editor.isActive("code");
});
const isLinkActive = $derived.by(() => {
  void editorState.current;
  return editor.isActive("link");
});
</script>

{#if showLinkEditor}
  <BubbleMenuLinkEditor {editor} onclose={() => (showLinkEditor = false)} />
{:else}
  <div class="vizel-bubble-menu-toolbar {className ?? ''}">
    <BubbleMenuButton
      action="bold"
      isActive={isBoldActive}
      title="Bold (Cmd+B)"
      onclick={() => editor.chain().focus().toggleBold().run()}
    >
      <strong>B</strong>
    </BubbleMenuButton>
    <BubbleMenuButton
      action="italic"
      isActive={isItalicActive}
      title="Italic (Cmd+I)"
      onclick={() => editor.chain().focus().toggleItalic().run()}
    >
      <em>I</em>
    </BubbleMenuButton>
    <BubbleMenuButton
      action="strike"
      isActive={isStrikeActive}
      title="Strikethrough"
      onclick={() => editor.chain().focus().toggleStrike().run()}
    >
      <s>S</s>
    </BubbleMenuButton>
    <BubbleMenuButton
      action="underline"
      isActive={isUnderlineActive}
      title="Underline (Cmd+U)"
      onclick={() => editor.chain().focus().toggleUnderline().run()}
    >
      <u>U</u>
    </BubbleMenuButton>
    <BubbleMenuButton
      action="code"
      isActive={isCodeActive}
      title="Code (Cmd+E)"
      onclick={() => editor.chain().focus().toggleCode().run()}
    >
      <code>&lt;/&gt;</code>
    </BubbleMenuButton>
    <BubbleMenuButton
      action="link"
      isActive={isLinkActive}
      title="Link (Cmd+K)"
      onclick={() => (showLinkEditor = true)}
    >
      <span>L</span>
    </BubbleMenuButton>
    <BubbleMenuColorPicker {editor} type="textColor" />
    <BubbleMenuColorPicker {editor} type="highlight" />
  </div>
{/if}
