// packages/vue/src/components/BubbleMenuLinkEditor.vue
<script setup lang="ts">
import { detectProvider, type Editor } from "@vizel/core";
import { computed, onMounted, onUnmounted, ref } from "vue";
import Icon from "./Icon.vue";

export interface BubbleMenuLinkEditorProps {
  /** The editor instance */
  editor: Editor;
  /** Custom class name */
  class?: string;
  /** Enable embed option (requires Embed extension) */
  enableEmbed?: boolean;
}

const props = withDefaults(defineProps<BubbleMenuLinkEditorProps>(), {
  enableEmbed: false,
});

const emit = defineEmits<{
  close: [];
}>();

const formRef = ref<HTMLFormElement | null>(null);
const inputRef = ref<HTMLInputElement | null>(null);
const currentHref = computed(() => props.editor.getAttributes("link").href || "");
const url = ref(currentHref.value);
const asEmbed = ref(false);

// Check if embed extension is available
const canEmbed = computed(() => {
  if (!props.enableEmbed) return false;
  // Check if embed extension is loaded
  const extensionManager = props.editor.extensionManager;
  return extensionManager.extensions.some((ext) => ext.name === "embed");
});

// Check if URL is a known embed provider
const isEmbedProvider = computed(() => {
  if (!url.value.trim()) return false;
  return detectProvider(url.value.trim()) !== null;
});

// Handle click outside to close
function handleClickOutside(event: MouseEvent) {
  if (formRef.value && !formRef.value.contains(event.target as Node)) {
    emit("close");
  }
}

// Handle Escape key to close
function handleKeyDown(event: KeyboardEvent) {
  if (event.key === "Escape") {
    event.preventDefault();
    event.stopImmediatePropagation();
    emit("close");
  }
}

onMounted(() => {
  inputRef.value?.focus();

  // Use setTimeout to avoid immediate trigger from the click that opened the editor
  setTimeout(() => {
    document.addEventListener("mousedown", handleClickOutside);
  }, 0);
  // Use capture phase so this handler runs before BubbleMenu's handler
  document.addEventListener("keydown", handleKeyDown, true);
});

onUnmounted(() => {
  document.removeEventListener("mousedown", handleClickOutside);
  document.removeEventListener("keydown", handleKeyDown, true);
});

function handleSubmit(e: Event) {
  e.preventDefault();
  const trimmedUrl = url.value.trim();

  if (!trimmedUrl) {
    props.editor.chain().focus().unsetLink().run();
    emit("close");
    return;
  }

  if (asEmbed.value && canEmbed.value) {
    // Remove the link first, then insert embed
    props.editor.chain().focus().unsetLink().setEmbed({ url: trimmedUrl }).run();
  } else {
    props.editor.chain().focus().setLink({ href: trimmedUrl }).run();
  }
  emit("close");
}

function handleRemove() {
  props.editor.chain().focus().unsetLink().run();
  emit("close");
}
</script>

<template>
  <form
    ref="formRef"
    :class="['vizel-link-editor', $props.class]"
    @submit="handleSubmit"
  >
    <div class="vizel-link-editor-row">
      <input
        ref="inputRef"
        v-model="url"
        type="url"
        placeholder="Enter URL..."
        class="vizel-link-input"
      />
      <button type="submit" class="vizel-link-button" title="Apply">
        <Icon name="check" />
      </button>
      <button
        v-if="currentHref"
        type="button"
        class="vizel-link-button vizel-link-remove"
        title="Remove link"
        @click="handleRemove"
      >
        <Icon name="x" />
      </button>
    </div>
    <div v-if="canEmbed && isEmbedProvider" class="vizel-link-editor-embed-toggle">
      <input
        id="vizel-embed-toggle"
        v-model="asEmbed"
        type="checkbox"
      />
      <label for="vizel-embed-toggle">Embed as rich content</label>
    </div>
  </form>
</template>

// packages/svelte/src/components/BubbleMenuLinkEditor.svelte
<script lang="ts" module>
import type { Editor } from "@vizel/core";

export interface BubbleMenuLinkEditorProps {
  /** The editor instance */
  editor: Editor;
  /** Custom class name */
  class?: string;
  /** Close handler */
  onclose?: () => void;
  /** Enable embed option (requires Embed extension) */
  enableEmbed?: boolean;
}
</script>

<script lang="ts">
import { detectProvider } from "@vizel/core";
import { onMount, untrack } from "svelte";
import Icon from "./Icon.svelte";

let {
  editor,
  class: className,
  onclose,
  enableEmbed = false,
}: BubbleMenuLinkEditorProps = $props();

let formElement: HTMLFormElement;
let inputElement: HTMLInputElement;
let currentHref = $derived(editor.getAttributes("link").href || "");
let url = $state(untrack(() => editor.getAttributes("link").href || ""));
let asEmbed = $state(false);

// Check if embed extension is available
const canEmbed = $derived.by(() => {
  if (!enableEmbed) return false;
  // Check if embed extension is loaded
  const extensionManager = editor.extensionManager;
  return extensionManager.extensions.some((ext) => ext.name === "embed");
});

// Check if URL is a known embed provider
const isEmbedProvider = $derived.by(() => {
  if (!url.trim()) return false;
  return detectProvider(url.trim()) !== null;
});

// Handle click outside to close
function handleClickOutside(event: MouseEvent) {
  if (formElement && !formElement.contains(event.target as Node)) {
    onclose?.();
  }
}

// Handle Escape key to close
function handleKeyDown(event: KeyboardEvent) {
  if (event.key === "Escape") {
    event.preventDefault();
    event.stopImmediatePropagation();
    onclose?.();
  }
}

onMount(() => {
  inputElement?.focus();

  // Use setTimeout to avoid immediate trigger from the click that opened the editor
  const timeoutId = setTimeout(() => {
    document.addEventListener("mousedown", handleClickOutside);
  }, 0);
  // Use capture phase so this handler runs before BubbleMenu's handler
  document.addEventListener("keydown", handleKeyDown, true);

  return () => {
    clearTimeout(timeoutId);
    document.removeEventListener("mousedown", handleClickOutside);
    document.removeEventListener("keydown", handleKeyDown, true);
  };
});

function handleSubmit(e: Event) {
  e.preventDefault();
  const trimmedUrl = url.trim();

  if (!trimmedUrl) {
    editor.chain().focus().unsetLink().run();
    onclose?.();
    return;
  }

  if (asEmbed && canEmbed) {
    // Remove the link first, then insert embed
    editor.chain().focus().unsetLink().setEmbed({ url: trimmedUrl }).run();
  } else {
    editor.chain().focus().setLink({ href: trimmedUrl }).run();
  }
  onclose?.();
}

function handleRemove() {
  editor.chain().focus().unsetLink().run();
  onclose?.();
}
</script>

<form
  bind:this={formElement}
  class="vizel-link-editor {className ?? ''}"
  onsubmit={handleSubmit}
>
  <div class="vizel-link-editor-row">
    <input
      bind:this={inputElement}
      bind:value={url}
      type="url"
      placeholder="Enter URL..."
      class="vizel-link-input"
    />
    <button type="submit" class="vizel-link-button" title="Apply">
      <Icon name="check" />
    </button>
    {#if currentHref}
      <button
        type="button"
        class="vizel-link-button vizel-link-remove"
        title="Remove link"
        onclick={handleRemove}
      >
        <Icon name="x" />
      </button>
    {/if}
  </div>
  {#if canEmbed && isEmbedProvider}
    <div class="vizel-link-editor-embed-toggle">
      <input
        id="vizel-embed-toggle"
        type="checkbox"
        bind:checked={asEmbed}
      />
      <label for="vizel-embed-toggle">Embed as rich content</label>
    </div>
  {/if}
</form>
