// packages/react/src/components/EditorRoot.tsx
import type { ReactNode } from "react";
import { EditorProvider } from "./EditorContext.tsx";
import type { Editor } from "@vizel/core";

export interface EditorRootProps {
  /** The editor instance from useVizelEditor */
  editor: Editor | null;
  /** Child components (EditorContent, BubbleMenu, etc.) */
  children: ReactNode;
  /** Optional className for the root container */
  className?: string;
}

/**
 * Root component for the Vizel editor.
 * Provides editor context to all child components.
 *
 * @example
 * ```tsx
 * const editor = useVizelEditor();
 *
 * return (
 *   <EditorRoot editor={editor}>
 *     <EditorContent />
 *   </EditorRoot>
 * );
 * ```
 */
export function EditorRoot({ editor, children, className }: EditorRootProps) {
  return (
    <EditorProvider editor={editor}>
      <div className={className} data-vizel-root="">
        {children}
      </div>
    </EditorProvider>
  );
}

// packages/svelte/src/components/EditorRoot.svelte
<script lang="ts" module>
import type { Editor } from "@vizel/core";
import type { Snippet } from "svelte";

export interface EditorRootProps {
  /** The editor instance */
  editor: Editor | null;
  /** Custom class name */
  class?: string;
  /** Children content */
  children: Snippet;
}
</script>

<script lang="ts">
import { setContext } from "svelte";
import { EDITOR_CONTEXT_KEY } from "./EditorContext.ts";

let { editor, class: className, children }: EditorRootProps = $props();

setContext(EDITOR_CONTEXT_KEY, () => editor);
</script>

<div class={className} data-vizel-root>
  {@render children()}
</div>
