// packages/vue/src/components/EditorContent.vue
<script setup lang="ts">
import type { Editor } from "@vizel/core";
import { computed, ref, watch } from "vue";
import { useEditorContextSafe } from "./EditorContext.ts";

export interface EditorContentProps {
  /** Override the editor from context */
  editor?: Editor;
  /** Custom class name */
  class?: string;
}

const props = defineProps<EditorContentProps>();

const containerRef = ref<HTMLDivElement | null>(null);
const getContextEditor = useEditorContextSafe();
const editor = computed(() => props.editor ?? getContextEditor?.());

watch(
  () => [editor.value, containerRef.value] as const,
  ([editorValue, container]) => {
    if (editorValue && container) {
      // Mount the editor's DOM view to the container element
      container.appendChild(editorValue.view.dom);

      // Update editable state
      editorValue.view.setProps({
        editable: () => editorValue?.isEditable ?? false,
      });
    }
  },
  { immediate: true }
);
</script>

<template>
  <div v-if="editor" ref="containerRef" :class="$props.class" data-vizel-content />
</template>

// packages/svelte/src/components/EditorContent.svelte
<script lang="ts" module>
import type { Editor } from "@vizel/core";

export interface EditorContentProps {
  /** Override the editor from context */
  editor?: Editor | null;
  /** Custom class name */
  class?: string;
}
</script>

<script lang="ts">
import { useEditorContextSafe } from "./EditorContext.ts";

let { editor: editorProp, class: className }: EditorContentProps = $props();

const contextEditor = useEditorContextSafe();
const editor = $derived(editorProp ?? contextEditor?.());

let element: HTMLElement | undefined = $state();

$effect(() => {
  if (editor && element) {
    // Mount the editor's DOM view to the container element
    element.appendChild(editor.view.dom);

    // Update editable state
    editor.view.setProps({
      editable: () => editor?.isEditable ?? false,
    });
  }
});
</script>

<div bind:this={element} class={className} data-vizel-content></div>
