// packages/vue/src/components/SaveIndicator.vue
<script setup lang="ts">
import { formatRelativeTime, type SaveStatus } from "@vizel/core";
import { computed, onBeforeUnmount, onMounted, ref, watch } from "vue";

export interface SaveIndicatorProps {
  /** Current save status */
  status: SaveStatus;
  /** Timestamp of last successful save */
  lastSaved?: Date | null;
  /** Show relative timestamp (default: true) */
  showTimestamp?: boolean;
  /** Custom class name */
  class?: string;
}

const props = withDefaults(defineProps<SaveIndicatorProps>(), {
  showTimestamp: true,
});

const relativeTime = ref("");
let intervalId: ReturnType<typeof setInterval> | null = null;

function updateTime() {
  if (props.lastSaved) {
    relativeTime.value = formatRelativeTime(props.lastSaved);
  } else {
    relativeTime.value = "";
  }
}

onMounted(() => {
  updateTime();
  intervalId = setInterval(updateTime, 10000);
});

watch(
  () => props.lastSaved,
  () => {
    updateTime();
  }
);

onBeforeUnmount(() => {
  if (intervalId) {
    clearInterval(intervalId);
  }
});

const statusText = computed(() => {
  switch (props.status) {
    case "saved":
      return "Saved";
    case "saving":
      return "Saving...";
    case "unsaved":
      return "Unsaved";
    case "error":
      return "Error saving";
    default:
      return "";
  }
});

const shouldShowTimestamp = computed(() => {
  return props.showTimestamp && props.lastSaved && relativeTime.value && props.status === "saved";
});
</script>

<template>
  <div
    :class="['vizel-save-indicator', `vizel-save-indicator--${props.status}`, $props.class]"
    role="status"
    aria-live="polite"
    data-vizel-save-indicator
  >
    <span class="vizel-save-indicator-icon" aria-hidden="true">
      <template v-if="props.status === 'saved'">✓</template>
      <template v-else-if="props.status === 'saving'">
        <span class="vizel-save-indicator-spinner" aria-hidden="true">⟳</span>
      </template>
      <template v-else-if="props.status === 'unsaved'">•</template>
      <template v-else-if="props.status === 'error'">⚠</template>
    </span>
    <span class="vizel-save-indicator-text">{{ statusText }}</span>
    <span v-if="shouldShowTimestamp" class="vizel-save-indicator-timestamp">{{ relativeTime }}</span>
  </div>
</template>

// packages/svelte/src/components/SaveIndicator.svelte
<script lang="ts" module>
import type { SaveStatus } from "@vizel/core";

export interface SaveIndicatorProps {
  /** Current save status */
  status: SaveStatus;
  /** Timestamp of last successful save */
  lastSaved?: Date | null;
  /** Show relative timestamp (default: true) */
  showTimestamp?: boolean;
  /** Custom class name */
  class?: string;
}
</script>

<script lang="ts">
import { formatRelativeTime } from "@vizel/core";
import { onDestroy, onMount } from "svelte";

let {
  status,
  lastSaved = null,
  showTimestamp = true,
  class: className,
}: SaveIndicatorProps = $props();

let relativeTime = $state("");
let intervalId: ReturnType<typeof setInterval> | null = null;

function updateTime() {
  if (lastSaved) {
    relativeTime = formatRelativeTime(lastSaved);
  } else {
    relativeTime = "";
  }
}

onMount(() => {
  updateTime();
  intervalId = setInterval(updateTime, 10000);
});

// Watch lastSaved changes
$effect(() => {
  // eslint-disable-next-line @typescript-eslint/no-unused-expressions
  lastSaved;
  updateTime();
});

onDestroy(() => {
  if (intervalId) {
    clearInterval(intervalId);
  }
});

const statusText = $derived.by(() => {
  switch (status) {
    case "saved":
      return "Saved";
    case "saving":
      return "Saving...";
    case "unsaved":
      return "Unsaved";
    case "error":
      return "Error saving";
    default:
      return "";
  }
});

const shouldShowTimestamp = $derived(showTimestamp && lastSaved && relativeTime && status === "saved");
</script>

<div
  class="vizel-save-indicator vizel-save-indicator--{status} {className ?? ''}"
  role="status"
  aria-live="polite"
  data-vizel-save-indicator
>
  <span class="vizel-save-indicator-icon" aria-hidden="true">
    {#if status === "saved"}
      ✓
    {:else if status === "saving"}
      <span class="vizel-save-indicator-spinner" aria-hidden="true">⟳</span>
    {:else if status === "unsaved"}
      •
    {:else if status === "error"}
      ⚠
    {/if}
  </span>
  <span class="vizel-save-indicator-text">{statusText}</span>
  {#if shouldShowTimestamp}
    <span class="vizel-save-indicator-timestamp">{relativeTime}</span>
  {/if}
</div>
