// packages/vue/src/components/ThemeProvider.vue
<script setup lang="ts">
import {
  applyTheme,
  createSystemThemeListener,
  DEFAULT_THEME,
  DEFAULT_THEME_STORAGE_KEY,
  getStoredTheme,
  getSystemTheme,
  type ResolvedTheme,
  resolveTheme,
  storeTheme,
  type Theme,
  type ThemeProviderOptions,
  type ThemeState,
} from "@vizel/core";
import { computed, onBeforeUnmount, onMounted, provide, ref, watch } from "vue";
import { ThemeContextKey } from "./ThemeContext";

export interface ThemeProviderProps extends ThemeProviderOptions {}

const props = withDefaults(defineProps<ThemeProviderProps>(), {
  defaultTheme: DEFAULT_THEME,
  storageKey: DEFAULT_THEME_STORAGE_KEY,
  disableTransitionOnChange: false,
});

const theme = ref<Theme>(getStoredTheme(props.storageKey) ?? props.defaultTheme);
const systemTheme = ref<ResolvedTheme>(getSystemTheme());

const resolvedTheme = computed(() => resolveTheme(theme.value, systemTheme.value));

function setTheme(newTheme: Theme) {
  theme.value = newTheme;
  storeTheme(props.storageKey, newTheme);
}

const themeState: ThemeState = {
  get theme() {
    return theme.value;
  },
  get resolvedTheme() {
    return resolvedTheme.value;
  },
  get systemTheme() {
    return systemTheme.value;
  },
  setTheme,
};

provide(ThemeContextKey, themeState);

let cleanup: (() => void) | null = null;

onMounted(() => {
  // Apply initial theme
  applyTheme(resolvedTheme.value, props.targetSelector, props.disableTransitionOnChange);

  // Listen for system theme changes
  cleanup = createSystemThemeListener((newSystemTheme) => {
    systemTheme.value = newSystemTheme;
  });
});

// Watch for resolved theme changes
watch(resolvedTheme, (newResolvedTheme) => {
  applyTheme(newResolvedTheme, props.targetSelector, props.disableTransitionOnChange);
});

onBeforeUnmount(() => {
  if (cleanup) {
    cleanup();
  }
});
</script>

<template>
  <slot />
</template>

// packages/svelte/src/components/ThemeProvider.svelte
<script lang="ts" module>
import type { ThemeState } from "@vizel/core";

export const THEME_CONTEXT_KEY = Symbol("ThemeContext");
</script>

<script lang="ts">
  import {
    applyTheme,
    createSystemThemeListener,
    DEFAULT_THEME,
    DEFAULT_THEME_STORAGE_KEY,
    getStoredTheme,
    getSystemTheme,
    resolveTheme,
    storeTheme,
    type ResolvedTheme,
    type Theme,
    type ThemeProviderOptions,
  } from "@vizel/core";
  import { onMount, setContext, type Snippet } from "svelte";

  interface Props extends ThemeProviderOptions {
    /** Children to render */
    children: Snippet;
  }

  let {
    children,
    defaultTheme = DEFAULT_THEME,
    storageKey = DEFAULT_THEME_STORAGE_KEY,
    targetSelector,
    disableTransitionOnChange = false,
  }: Props = $props();

  let theme = $state<Theme>(getStoredTheme(storageKey) ?? defaultTheme);
  let systemTheme = $state<ResolvedTheme>(getSystemTheme());

  const resolvedTheme = $derived(resolveTheme(theme, systemTheme));

  function setTheme(newTheme: Theme) {
    theme = newTheme;
    storeTheme(storageKey, newTheme);
  }

  const themeState: ThemeState = {
    get theme() {
      return theme;
    },
    get resolvedTheme() {
      return resolvedTheme;
    },
    get systemTheme() {
      return systemTheme;
    },
    setTheme,
  };

  setContext(THEME_CONTEXT_KEY, themeState);

  // Apply theme when resolved theme changes
  $effect(() => {
    applyTheme(resolvedTheme, targetSelector, disableTransitionOnChange);
  });

  onMount(() => {
    // Listen for system theme changes
    const cleanup = createSystemThemeListener((newSystemTheme) => {
      systemTheme = newSystemTheme;
    });

    return cleanup;
  });
</script>

{@render children()}
