// packages/vue/src/components/VizelSlashMenu.vue
<script setup lang="ts">
import {
  groupVizelSlashCommands,
  type VizelSlashCommandGroup,
  type VizelSlashCommandItem,
} from "@vizel/core";
import { computed, nextTick, ref, useSlots, watch } from "vue";
import VizelSlashMenuEmpty from "./VizelSlashMenuEmpty.vue";
import VizelSlashMenuItem from "./VizelSlashMenuItem.vue";

export interface VizelSlashMenuRef {
  onKeyDown: (props: { event: KeyboardEvent }) => boolean;
}

export interface VizelSlashMenuProps {
  /** The list of slash command items */
  items: VizelSlashCommandItem[];
  /** Custom class name */
  class?: string;
  /** Whether to show items grouped by category (default: true when not searching) */
  showGroups?: boolean;
  /** Custom group order */
  groupOrder?: string[];
}

const props = withDefaults(defineProps<VizelSlashMenuProps>(), {
  showGroups: true,
});

const emit = defineEmits<{
  command: [item: VizelSlashCommandItem];
}>();

const slots = useSlots();
const selectedIndex = ref(0);
const itemRefs = ref<(HTMLElement | null)[]>([]);

// Group items when showGroups is true and there are enough items
const groups = computed<VizelSlashCommandGroup[]>(() => {
  if (!props.showGroups || props.items.length <= 5) {
    // Don't group if explicitly disabled or few items (likely search results)
    return [{ name: "", items: props.items }];
  }
  return groupVizelSlashCommands(props.items, props.groupOrder);
});

// Flatten for navigation
const flatItems = computed(() => groups.value.flatMap((g) => g.items));

// Reset selection and refs when items change
watch(
  () => props.items,
  () => {
    selectedIndex.value = 0;
    // Reset refs array to prevent stale references
    itemRefs.value = [];
  }
);

// Scroll selected item into view when selection changes
watch(selectedIndex, async (newIndex) => {
  await nextTick();
  const selectedElement = itemRefs.value[newIndex];
  if (selectedElement) {
    selectedElement.scrollIntoView({ block: "nearest", behavior: "smooth" });
  }
});

function selectItem(index: number) {
  const item = flatItems.value[index];
  if (item) {
    emit("command", item);
  }
}

// Navigate to next group with Tab
function tabHandler() {
  if (groups.value.length <= 1) return;

  let currentGroupIndex = 0;
  let itemCount = 0;
  for (let i = 0; i < groups.value.length; i++) {
    const group = groups.value[i];
    if (!group) continue;
    if (selectedIndex.value < itemCount + group.items.length) {
      currentGroupIndex = i;
      break;
    }
    itemCount += group.items.length;
  }

  // Move to next group
  const nextGroupIndex = (currentGroupIndex + 1) % groups.value.length;
  let nextIndex = 0;
  for (let i = 0; i < nextGroupIndex; i++) {
    const group = groups.value[i];
    if (group) {
      nextIndex += group.items.length;
    }
  }
  selectedIndex.value = nextIndex;
}

function handleKeyDown(event: KeyboardEvent): boolean {
  if (event.key === "ArrowUp") {
    selectedIndex.value =
      (selectedIndex.value + flatItems.value.length - 1) % flatItems.value.length;
    return true;
  }

  if (event.key === "ArrowDown") {
    selectedIndex.value = (selectedIndex.value + 1) % flatItems.value.length;
    return true;
  }

  if (event.key === "Enter") {
    selectItem(selectedIndex.value);
    return true;
  }

  if (event.key === "Tab") {
    event.preventDefault();
    tabHandler();
    return true;
  }

  return false;
}

// Expose handleKeyDown for parent components
defineExpose({
  onKeyDown: handleKeyDown,
});

// Calculate global index for items
function getGlobalIndex(groupIndex: number, itemIndex: number): number {
  let index = 0;
  for (let i = 0; i < groupIndex; i++) {
    const group = groups.value[i];
    if (group) {
      index += group.items.length;
    }
  }
  return index + itemIndex;
}
</script>

<template>
  <div :class="['vizel-slash-menu', $props.class]" data-vizel-slash-menu>
    <template v-if="flatItems.length === 0">
      <slot v-if="slots.empty" name="empty" />
      <VizelSlashMenuEmpty v-else />
    </template>
    <template v-else>
      <template v-for="(group, groupIndex) in groups" :key="group.name || groupIndex">
        <!-- Group with header -->
        <div
          v-if="group.name"
          class="vizel-slash-menu-group"
          data-vizel-slash-menu-group
        >
          <div class="vizel-slash-menu-group-header">{{ group.name }}</div>
          <div
            v-for="(item, itemIndex) in group.items"
            :key="item.title"
            :ref="(el) => (itemRefs[getGlobalIndex(groupIndex, itemIndex)] = el as HTMLElement)"
          >
            <slot
              v-if="slots.item"
              name="item"
              :item="item"
              :is-selected="getGlobalIndex(groupIndex, itemIndex) === selectedIndex"
              :on-click="() => selectItem(getGlobalIndex(groupIndex, itemIndex))"
            />
            <VizelSlashMenuItem
              v-else
              :item="item"
              :is-selected="getGlobalIndex(groupIndex, itemIndex) === selectedIndex"
              @click="selectItem(getGlobalIndex(groupIndex, itemIndex))"
            />
          </div>
        </div>
        <!-- Items without group header -->
        <template v-else>
          <div
            v-for="(item, itemIndex) in group.items"
            :key="item.title"
            :ref="(el) => (itemRefs[getGlobalIndex(groupIndex, itemIndex)] = el as HTMLElement)"
          >
            <slot
              v-if="slots.item"
              name="item"
              :item="item"
              :is-selected="getGlobalIndex(groupIndex, itemIndex) === selectedIndex"
              :on-click="() => selectItem(getGlobalIndex(groupIndex, itemIndex))"
            />
            <VizelSlashMenuItem
              v-else
              :item="item"
              :is-selected="getGlobalIndex(groupIndex, itemIndex) === selectedIndex"
              @click="selectItem(getGlobalIndex(groupIndex, itemIndex))"
            />
          </div>
        </template>
      </template>
    </template>
  </div>
</template>

// packages/svelte/src/components/VizelSlashMenu.svelte
<script lang="ts" module>
import type { VizelSlashCommandItem } from "@vizel/core";
import type { Snippet } from "svelte";

export interface VizelSlashMenuRef {
  onKeyDown: (event: KeyboardEvent) => boolean;
}

export interface VizelSlashMenuProps {
  /** The list of slash command items */
  items: VizelSlashCommandItem[];
  /** Custom class name */
  class?: string;
  /** Command handler */
  oncommand?: (item: VizelSlashCommandItem) => void;
  /** Whether to show items grouped by category (default: true when not searching) */
  showGroups?: boolean;
  /** Custom group order */
  groupOrder?: string[];
  /** Custom item renderer */
  renderItem?: Snippet<[{ item: VizelSlashCommandItem; isSelected: boolean; onclick: () => void }]>;
  /** Custom empty state renderer */
  renderEmpty?: Snippet;
}
</script>

<script lang="ts">
import { groupVizelSlashCommands, type VizelSlashCommandGroup } from "@vizel/core";
import { tick } from "svelte";
import VizelSlashMenuItem from "./VizelSlashMenuItem.svelte";
import VizelSlashMenuEmpty from "./VizelSlashMenuEmpty.svelte";

let {
  items,
  class: className,
  oncommand,
  showGroups = true,
  groupOrder,
  renderItem,
  renderEmpty,
}: VizelSlashMenuProps = $props();

let selectedIndex = $state(0);
let itemRefs: (HTMLElement | null)[] = $state([]);

// Clean up itemRefs when items decrease
$effect(() => {
  const length = flatItems.length;
  if (itemRefs.length > length) {
    itemRefs.length = length;
  }
});

// Group items when showGroups is true and there are enough items
const groups = $derived.by<VizelSlashCommandGroup[]>(() => {
  if (!showGroups || items.length <= 5) {
    // Don't group if explicitly disabled or few items (likely search results)
    return [{ name: "", items }];
  }
  return groupVizelSlashCommands(items, groupOrder);
});

// Flatten for navigation
const flatItems = $derived(groups.flatMap((g) => g.items));

// Reset selection when items change
$effect(() => {
  items;
  selectedIndex = 0;
});

// Scroll selected item into view when selection changes
$effect(() => {
  const index = selectedIndex;
  tick().then(() => {
    const selectedElement = itemRefs[index];
    if (selectedElement) {
      selectedElement.scrollIntoView({ block: "nearest", behavior: "smooth" });
    }
  });
});

function selectItem(index: number) {
  const item = flatItems[index];
  if (item) {
    oncommand?.(item);
  }
}

// Navigate to next group with Tab
function tabHandler() {
  if (groups.length <= 1) return;

  let currentGroupIndex = 0;
  let itemCount = 0;
  for (let i = 0; i < groups.length; i++) {
    const group = groups[i];
    if (!group) continue;
    if (selectedIndex < itemCount + group.items.length) {
      currentGroupIndex = i;
      break;
    }
    itemCount += group.items.length;
  }

  // Move to next group
  const nextGroupIndex = (currentGroupIndex + 1) % groups.length;
  let nextIndex = 0;
  for (let i = 0; i < nextGroupIndex; i++) {
    const group = groups[i];
    if (group) {
      nextIndex += group.items.length;
    }
  }
  selectedIndex = nextIndex;
}

// Calculate global index for items
function getGlobalIndex(groupIndex: number, itemIndex: number): number {
  let index = 0;
  for (let i = 0; i < groupIndex; i++) {
    const group = groups[i];
    if (group) {
      index += group.items.length;
    }
  }
  return index + itemIndex;
}

export function onKeyDown(event: KeyboardEvent): boolean {
  if (event.key === "ArrowUp") {
    selectedIndex = (selectedIndex + flatItems.length - 1) % flatItems.length;
    return true;
  }

  if (event.key === "ArrowDown") {
    selectedIndex = (selectedIndex + 1) % flatItems.length;
    return true;
  }

  if (event.key === "Enter") {
    selectItem(selectedIndex);
    return true;
  }

  if (event.key === "Tab") {
    event.preventDefault();
    tabHandler();
    return true;
  }

  return false;
}
</script>

<div class="vizel-slash-menu {className ?? ''}" data-vizel-slash-menu>
  {#if flatItems.length === 0}
    {#if renderEmpty}
      {@render renderEmpty()}
    {:else}
      <VizelSlashMenuEmpty />
    {/if}
  {:else}
    {#each groups as group, groupIndex (group.name || groupIndex)}
      {#if group.name}
        <!-- Group with header -->
        <div class="vizel-slash-menu-group" data-vizel-slash-menu-group>
          <div class="vizel-slash-menu-group-header">{group.name}</div>
          {#each group.items as item, itemIndex (item.title)}
            {@const globalIdx = getGlobalIndex(groupIndex, itemIndex)}
            <div bind:this={itemRefs[globalIdx]}>
              {#if renderItem}
                {@render renderItem({
                  item,
                  isSelected: globalIdx === selectedIndex,
                  onclick: () => selectItem(globalIdx),
                })}
              {:else}
                <VizelSlashMenuItem
                  {item}
                  isSelected={globalIdx === selectedIndex}
                  onclick={() => selectItem(globalIdx)}
                />
              {/if}
            </div>
          {/each}
        </div>
      {:else}
        <!-- Items without group header -->
        {#each group.items as item, itemIndex (item.title)}
          {@const globalIdx = getGlobalIndex(groupIndex, itemIndex)}
          <div bind:this={itemRefs[globalIdx]}>
            {#if renderItem}
              {@render renderItem({
                item,
                isSelected: globalIdx === selectedIndex,
                onclick: () => selectItem(globalIdx),
              })}
            {:else}
              <VizelSlashMenuItem
                {item}
                isSelected={globalIdx === selectedIndex}
                onclick={() => selectItem(globalIdx)}
              />
            {/if}
          </div>
        {/each}
      {/if}
    {/each}
  {/if}
</div>
