// packages/react/src/components/VizelToolbarColorPicker.tsx
import type { Editor } from "@tiptap/core";
import {
  addVizelRecentColor,
  getVizelRecentColors,
  VIZEL_HIGHLIGHT_COLORS,
  VIZEL_TEXT_COLORS,
  type VizelColorDefinition,
} from "@vizel/core";
import { useCallback, useEffect, useRef, useState } from "react";
import { VizelColorPicker } from "./VizelColorPicker.tsx";
import { VizelIcon } from "./VizelIcon.tsx";

export interface VizelToolbarColorPickerProps {
  editor: Editor;
  /** Color picker type */
  type: "textColor" | "highlight";
  /** Custom color palette */
  colors?: VizelColorDefinition[];
  /** Custom class name */
  className?: string;
  /** Enable custom color input (default: true) */
  allowCustomColor?: boolean;
  /** Enable recent colors (default: true) */
  showRecentColors?: boolean;
}

/**
 * A color picker component for the VizelToolbar.
 * Supports text color and highlight color selection with custom colors and recent colors.
 */
export function VizelToolbarColorPicker({
  editor,
  type,
  colors,
  className,
  allowCustomColor = true,
  showRecentColors = true,
}: VizelToolbarColorPickerProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [recentColors, setRecentColors] = useState<string[]>([]);
  const containerRef = useRef<HTMLDivElement>(null);

  const colorPalette =
    colors ?? (type === "textColor" ? VIZEL_TEXT_COLORS : VIZEL_HIGHLIGHT_COLORS);

  // Get current color
  const getCurrentColor = (): string | undefined => {
    if (type === "textColor") {
      return editor.getAttributes("textStyle").color;
    }
    return editor.getAttributes("highlight").color;
  };

  const currentColor = getCurrentColor();

  // Load recent colors when dropdown opens
  useEffect(() => {
    if (isOpen && showRecentColors) {
      setRecentColors(getVizelRecentColors(type));
    }
  }, [isOpen, showRecentColors, type]);

  // Apply color to editor
  const handleColorChange = useCallback(
    (color: string) => {
      if (type === "textColor") {
        if (color === "inherit") {
          editor.chain().focus().unsetColor().run();
        } else {
          editor.chain().focus().setColor(color).run();
          addVizelRecentColor(type, color);
        }
      } else if (color === "transparent") {
        editor.chain().focus().unsetHighlight().run();
      } else {
        editor.chain().focus().toggleHighlight({ color }).run();
        addVizelRecentColor(type, color);
      }
      setIsOpen(false);
    },
    [editor, type]
  );

  // Close dropdown when clicking outside
  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (containerRef.current && !containerRef.current.contains(event.target as Node)) {
        setIsOpen(false);
      }
    };

    if (isOpen) {
      document.addEventListener("mousedown", handleClickOutside);
    }
    return () => {
      document.removeEventListener("mousedown", handleClickOutside);
    };
  }, [isOpen]);

  const isTextColor = type === "textColor";
  const icon = isTextColor ? <VizelIcon name="textColor" /> : <VizelIcon name="highlighter" />;

  return (
    <div ref={containerRef} className={`vizel-color-picker ${className ?? ""}`} data-type={type}>
      <button
        type="button"
        className={`vizel-bubble-menu-button vizel-color-picker-trigger ${currentColor ? "has-color" : ""}`}
        onClick={() => setIsOpen(!isOpen)}
        title={isTextColor ? "Text Color" : "Highlight"}
        data-action={type}
        style={
          isTextColor
            ? { color: currentColor || "inherit" }
            : ({ "--highlight-color": currentColor || "transparent" } as React.CSSProperties)
        }
      >
        {icon}
      </button>

      {isOpen && (
        <div className="vizel-color-picker-dropdown">
          <VizelColorPicker
            colors={colorPalette}
            value={currentColor}
            onChange={handleColorChange}
            label={isTextColor ? "Text color palette" : "Highlight color palette"}
            allowCustomColor={allowCustomColor}
            recentColors={recentColors}
            showRecentColors={showRecentColors}
            noneValues={isTextColor ? ["inherit"] : ["transparent"]}
          />
        </div>
      )}
    </div>
  );
}

// packages/svelte/src/components/VizelToolbarColorPicker.svelte
<script lang="ts" module>
import type { Editor } from "@tiptap/core";
import type { VizelColorDefinition } from "@vizel/core";

export interface VizelToolbarColorPickerProps {
  /** The editor instance */
  editor: Editor;
  /** Color picker type */
  type: "textColor" | "highlight";
  /** Custom color palette */
  colors?: VizelColorDefinition[];
  /** Custom class name */
  class?: string;
  /** Enable custom color input (default: true) */
  allowCustomColor?: boolean;
  /** Enable recent colors (default: true) */
  showRecentColors?: boolean;
}
</script>

<script lang="ts">
import {
  addVizelRecentColor,
  getVizelRecentColors,
  VIZEL_HIGHLIGHT_COLORS,
  VIZEL_TEXT_COLORS,
} from "@vizel/core";
import { onMount, onDestroy } from "svelte";
import VizelColorPicker from "./VizelColorPicker.svelte";
import VizelIcon from "./VizelIcon.svelte";

let {
  editor,
  type,
  colors,
  class: className,
  allowCustomColor = true,
  showRecentColors = true,
}: VizelToolbarColorPickerProps = $props();

let isOpen = $state(false);
let recentColors = $state<string[]>([]);
let containerRef: HTMLDivElement | null = $state(null);

const colorPalette = $derived(colors ?? (type === "textColor" ? VIZEL_TEXT_COLORS : VIZEL_HIGHLIGHT_COLORS));

const currentColor = $derived.by(() => {
  if (type === "textColor") {
    return editor.getAttributes("textStyle").color;
  }
  return editor.getAttributes("highlight").color;
});

const isTextColor = $derived(type === "textColor");

const noneValues = $derived(isTextColor ? ["inherit"] : ["transparent"]);

// Load recent colors when dropdown opens
$effect(() => {
  if (isOpen && showRecentColors) {
    recentColors = getVizelRecentColors(type);
  }
});

function handleColorChange(color: string) {
  if (type === "textColor") {
    if (color === "inherit") {
      editor.chain().focus().unsetColor().run();
    } else {
      editor.chain().focus().setColor(color).run();
      addVizelRecentColor(type, color);
    }
  } else if (color === "transparent") {
    editor.chain().focus().unsetHighlight().run();
  } else {
    editor.chain().focus().toggleHighlight({ color }).run();
    addVizelRecentColor(type, color);
  }
  isOpen = false;
}

function handleClickOutside(event: MouseEvent) {
  if (containerRef && !containerRef.contains(event.target as Node)) {
    isOpen = false;
  }
}

onMount(() => {
  document.addEventListener("mousedown", handleClickOutside);
});

onDestroy(() => {
  document.removeEventListener("mousedown", handleClickOutside);
});

function getTriggerStyle(): string {
  if (isTextColor) {
    return `color: ${currentColor || "inherit"}`;
  }
  return `--highlight-color: ${currentColor || "transparent"}`;
}
</script>

<div
  bind:this={containerRef}
  class="vizel-color-picker {className ?? ''}"
  data-type={type}
>
  <button
    type="button"
    class="vizel-bubble-menu-button vizel-color-picker-trigger {currentColor ? 'has-color' : ''}"
    title={isTextColor ? "Text Color" : "Highlight"}
    data-action={type}
    style={getTriggerStyle()}
    onclick={() => (isOpen = !isOpen)}
  >
    {#if isTextColor}
      <VizelIcon name="textColor" />
    {:else}
      <VizelIcon name="highlighter" />
    {/if}
  </button>

  {#if isOpen}
    <div class="vizel-color-picker-dropdown">
      <VizelColorPicker
        colors={colorPalette}
        value={currentColor}
        label={isTextColor ? "Text color palette" : "Highlight color palette"}
        {allowCustomColor}
        {recentColors}
        {showRecentColors}
        {noneValues}
        onchange={handleColorChange}
      />
    </div>
  {/if}
</div>
