// packages/vue/src/components/Vizel.vue
<script setup lang="ts">
// Vizel - All-in-one editor component
//
// A complete editor component that includes EditorContent and BubbleMenu.
// This is the recommended way to use Vizel for most use cases.
import {
  type Editor,
  type Extensions,
  getVizelMarkdown,
  type JSONContent,
  setVizelMarkdown,
  type VizelError,
  type VizelFeatureOptions,
  type VizelLocale,
  type VizelMarkdownFlavor,
} from "@vizel/core";
import { useSlots, watch } from "vue";
import { useVizelEditor } from "../composables/useVizelEditor.ts";
import VizelBlockMenu from "./VizelBlockMenu.vue";
import VizelBubbleMenu from "./VizelBubbleMenu.vue";
import VizelEditor from "./VizelEditor.vue";
import VizelToolbar from "./VizelToolbar.vue";

/**
 * Exposed ref type for Vizel component.
 * Use with `ref` attribute to access the editor instance.
 */
export interface VizelRef {
  /** The underlying Tiptap editor instance */
  editor: Editor | null;
}

export interface VizelProps {
  /** Initial content in JSON format */
  initialContent?: JSONContent;
  /**
   * Initial content in Markdown format.
   * If both initialContent and initialMarkdown are provided, initialMarkdown takes precedence.
   * @example
   * ```vue
   * <Vizel initial-markdown="# Hello World\n\nThis is **bold** text." />
   * ```
   */
  initialMarkdown?: string;
  /**
   * Automatically transform diagram code blocks (mermaid, graphviz) to diagram nodes
   * when importing markdown content. Only applies when initialMarkdown is provided.
   * @default true
   */
  transformDiagramsOnImport?: boolean;
  /** Placeholder text when editor is empty */
  placeholder?: string;
  /** Whether the editor is editable (default: true) */
  editable?: boolean;
  /** Auto focus on mount */
  autofocus?: boolean | "start" | "end" | "all" | number;
  /** Feature configuration */
  features?: VizelFeatureOptions;
  /**
   * Markdown output flavor.
   * Controls how Markdown is serialized when exporting content.
   * @default "gfm"
   */
  flavor?: VizelMarkdownFlavor;
  /** Locale for translated UI strings */
  locale?: VizelLocale;
  /** Additional Tiptap extensions */
  extensions?: Extensions;
  /** Custom class name for the editor container */
  class?: string;
  /** Whether to show the toolbar (default: false) */
  showToolbar?: boolean;
  /** Whether to show the bubble menu (default: true) */
  showBubbleMenu?: boolean;
  /** Enable embed option in bubble menu link editor (requires Embed extension) */
  enableEmbed?: boolean;
}

const props = withDefaults(defineProps<VizelProps>(), {
  editable: true,
  autofocus: false,
  showToolbar: false,
  showBubbleMenu: true,
  enableEmbed: false,
  transformDiagramsOnImport: true,
});

const emit = defineEmits<{
  /** Emitted when content changes */
  update: [{ editor: Editor }];
  /** Emitted when editor is created */
  create: [{ editor: Editor }];
  /** Emitted when editor is destroyed */
  destroy: [];
  /** Emitted when selection changes */
  selectionUpdate: [{ editor: Editor }];
  /** Emitted when editor gets focus */
  focus: [{ editor: Editor }];
  /** Emitted when editor loses focus */
  blur: [{ editor: Editor }];
  /** Emitted when an error occurs during editor operations */
  error: [VizelError];
}>();

/**
 * Two-way binding for markdown content (v-model:markdown).
 * When set, markdown will be synchronized with the editor content.
 * Uses Vue 3.4+ defineModel for cleaner two-way binding.
 */
const markdown = defineModel<string>("markdown");

const slots = useSlots();

// Track whether we're currently updating from external markdown change
let isUpdatingFromMarkdown = false;

const editor = useVizelEditor({
  ...(props.initialContent !== undefined && { initialContent: props.initialContent }),
  ...(props.initialMarkdown !== undefined && { initialMarkdown: props.initialMarkdown }),
  transformDiagramsOnImport: props.transformDiagramsOnImport,
  ...(props.placeholder !== undefined && { placeholder: props.placeholder }),
  editable: props.editable,
  autofocus: props.autofocus,
  ...(props.features !== undefined && { features: props.features }),
  ...(props.flavor !== undefined && { flavor: props.flavor }),
  ...(props.locale !== undefined && { locale: props.locale }),
  ...(props.extensions !== undefined && { extensions: props.extensions }),
  onUpdate: (e) => {
    emit("update", e);
    // Update markdown model if not updating from external change
    if (!isUpdatingFromMarkdown && markdown.value !== undefined) {
      markdown.value = getVizelMarkdown(e.editor);
    }
  },
  onCreate: (e) => emit("create", e),
  onDestroy: () => emit("destroy"),
  onSelectionUpdate: (e) => emit("selectionUpdate", e),
  onFocus: (e) => emit("focus", e),
  onBlur: (e) => emit("blur", e),
  onError: (e) => emit("error", e),
});

// Watch for external markdown changes (v-model:markdown)
watch(markdown, (newMarkdown) => {
  if (newMarkdown === undefined || !editor.value) return;

  // Get current editor markdown
  const currentMarkdown = getVizelMarkdown(editor.value);
  if (newMarkdown === currentMarkdown) return;

  // Set flag to prevent emitting update:markdown during this update
  isUpdatingFromMarkdown = true;
  setVizelMarkdown(editor.value, newMarkdown, {
    transformDiagrams: props.transformDiagramsOnImport,
  });
  isUpdatingFromMarkdown = false;
});

// Expose editor instance for advanced use cases
// Both `editor` property and `getEditor()` method are provided for compatibility
defineExpose<VizelRef & { getEditor: () => Editor | null }>({
  /** The underlying Tiptap editor instance */
  get editor() {
    return editor.value;
  },
  /**
   * Get the underlying Tiptap editor instance
   * @deprecated Use the `editor` property instead
   */
  getEditor: () => editor.value,
});
</script>

<template>
  <div :class="['vizel-root', $props.class]" data-vizel-root>
    <VizelToolbar v-if="showToolbar && editor && slots['toolbar']" :editor="editor" v-bind="props.locale ? { locale: props.locale } : {}">
      <slot name="toolbar" :editor="editor" />
    </VizelToolbar>
    <VizelToolbar v-else-if="showToolbar && editor" :editor="editor" v-bind="props.locale ? { locale: props.locale } : {}" />
    <VizelEditor :editor="editor" />
    <VizelBubbleMenu v-if="showBubbleMenu && editor && slots['bubble-menu']" :editor="editor" :enable-embed="enableEmbed ?? false" v-bind="props.locale ? { locale: props.locale } : {}">
      <slot name="bubble-menu" :editor="editor" />
    </VizelBubbleMenu>
    <VizelBubbleMenu v-else-if="showBubbleMenu && editor" :editor="editor" :enable-embed="enableEmbed ?? false" v-bind="props.locale ? { locale: props.locale } : {}" />
    <VizelBlockMenu v-if="props.locale" :locale="props.locale" />
    <VizelBlockMenu v-else />
    <slot :editor="editor" />
  </div>
</template>

// packages/svelte/src/components/Vizel.svelte
<script lang="ts" module>
import type {
  Editor,
  Extensions,
  JSONContent,
  VizelError,
  VizelFeatureOptions,
  VizelLocale,
  VizelMarkdownFlavor,
} from "@vizel/core";
import type { Snippet } from "svelte";

/**
 * Exposed ref type for Vizel component.
 * Use with `bind:this` and access the `editor` property.
 */
export interface VizelRef {
  /** The underlying Tiptap editor instance */
  readonly editor: Editor | null;
}

export interface VizelProps {
  /** Initial content in JSON format */
  initialContent?: JSONContent;
  /**
   * Initial content in Markdown format.
   * If both initialContent and initialMarkdown are provided, initialMarkdown takes precedence.
   * @example
   * ```svelte
   * <Vizel initialMarkdown="# Hello World\n\nThis is **bold** text." />
   * ```
   */
  initialMarkdown?: string;
  /**
   * Automatically transform diagram code blocks (mermaid, graphviz) to diagram nodes
   * when importing markdown content. Only applies when initialMarkdown is provided.
   * @default true
   */
  transformDiagramsOnImport?: boolean;
  /**
   * Two-way binding for markdown content (bind:markdown).
   * When set, markdown will be synchronized with the editor content.
   */
  markdown?: string;
  /** Placeholder text when editor is empty */
  placeholder?: string;
  /** Whether the editor is editable (default: true) */
  editable?: boolean;
  /** Auto focus on mount */
  autofocus?: boolean | "start" | "end" | "all" | number;
  /** Feature configuration */
  features?: VizelFeatureOptions;
  /**
   * Markdown output flavor.
   * Controls how Markdown is serialized when exporting content.
   * @default "gfm"
   */
  flavor?: VizelMarkdownFlavor;
  /** Locale for translated UI strings */
  locale?: VizelLocale;
  /** Additional Tiptap extensions */
  extensions?: Extensions;
  /** Custom class name for the editor container */
  class?: string;
  /** Whether to show the toolbar (default: false) */
  showToolbar?: boolean;
  /** Custom toolbar content */
  toolbar?: Snippet<[{ editor: Editor }]>;
  /** Whether to show the bubble menu (default: true) */
  showBubbleMenu?: boolean;
  /** Enable embed option in bubble menu link editor (requires Embed extension) */
  enableEmbed?: boolean;
  /** Custom bubble menu content */
  bubbleMenu?: Snippet<[{ editor: Editor }]>;
  /** Additional children to render inside the editor root */
  children?: Snippet<[{ editor: Editor | null }]>;
  /** Callback when content changes */
  onUpdate?: (props: { editor: Editor }) => void;
  /** Callback when editor is created */
  onCreate?: (props: { editor: Editor }) => void;
  /** Callback when editor is destroyed */
  onDestroy?: () => void;
  /** Callback when selection changes */
  onSelectionUpdate?: (props: { editor: Editor }) => void;
  /** Callback when editor gets focus */
  onFocus?: (props: { editor: Editor }) => void;
  /** Callback when editor loses focus */
  onBlur?: (props: { editor: Editor }) => void;
  /**
   * Callback when an error occurs during editor operations.
   * Provides structured error information for logging or user feedback.
   */
  onError?: (error: VizelError) => void;
}
</script>

<script lang="ts">
// Vizel - All-in-one editor component
// A complete editor component that includes EditorContent and BubbleMenu.
// This is the recommended way to use Vizel for most use cases.
import { getVizelMarkdown, setVizelMarkdown } from "@vizel/core";
import { createVizelEditor } from "../runes/createVizelEditor.svelte.js";
import VizelBlockMenu from "./VizelBlockMenu.svelte";
import VizelBubbleMenu from "./VizelBubbleMenu.svelte";
import VizelEditor from "./VizelEditor.svelte";
import VizelToolbar from "./VizelToolbar.svelte";

// Use $props() without destructuring to avoid state_referenced_locally warnings
// Props are intentionally captured once at editor creation time
let {
  class: className,
  showToolbar = false,
  toolbar,
  showBubbleMenu = true,
  enableEmbed = false,
  bubbleMenu,
  children,
  markdown = $bindable(),
  transformDiagramsOnImport = true,
  ...restProps
}: VizelProps = $props();

// Track whether we're currently updating from external markdown change
let isUpdatingFromMarkdown = false;

// Wrap onUpdate to sync markdown
const originalOnUpdate = restProps.onUpdate;
const wrappedOnUpdate = (e: { editor: import("@vizel/core").Editor }) => {
  originalOnUpdate?.(e);
  // Update markdown binding if not updating from external change
  if (!isUpdatingFromMarkdown && markdown !== undefined) {
    markdown = getVizelMarkdown(e.editor);
  }
};

// Capture initial values for editor creation (these are intentionally not reactive)
// The editor is created once and should not be recreated when props change
// svelte-ignore state_referenced_locally
const initialTransformDiagrams = transformDiagramsOnImport;

// Create editor with initial props - editor is intentionally created once
const editorState = createVizelEditor({
  ...(restProps.initialContent !== undefined && { initialContent: restProps.initialContent }),
  ...(restProps.initialMarkdown !== undefined && { initialMarkdown: restProps.initialMarkdown }),
  transformDiagramsOnImport: initialTransformDiagrams,
  ...(restProps.placeholder !== undefined && { placeholder: restProps.placeholder }),
  editable: restProps.editable ?? true,
  autofocus: restProps.autofocus ?? false,
  ...(restProps.features !== undefined && { features: restProps.features }),
  ...(restProps.flavor !== undefined && { flavor: restProps.flavor }),
  ...(restProps.locale !== undefined && { locale: restProps.locale }),
  ...(restProps.extensions !== undefined && { extensions: restProps.extensions }),
  onUpdate: wrappedOnUpdate,
  ...(restProps.onCreate !== undefined && { onCreate: restProps.onCreate }),
  ...(restProps.onDestroy !== undefined && { onDestroy: restProps.onDestroy }),
  ...(restProps.onSelectionUpdate !== undefined && { onSelectionUpdate: restProps.onSelectionUpdate }),
  ...(restProps.onFocus !== undefined && { onFocus: restProps.onFocus }),
  ...(restProps.onBlur !== undefined && { onBlur: restProps.onBlur }),
  ...(restProps.onError !== undefined && { onError: restProps.onError }),
});

const editor = $derived(editorState.current);

// Watch for external markdown changes (bind:markdown)
$effect(() => {
  if (markdown === undefined || !editor) return;

  // Get current editor markdown
  const currentMarkdown = getVizelMarkdown(editor);
  if (markdown === currentMarkdown) return;

  // Set flag to prevent emitting update during this update
  isUpdatingFromMarkdown = true;
  setVizelMarkdown(editor, markdown, {
    transformDiagrams: transformDiagramsOnImport,
  });
  isUpdatingFromMarkdown = false;
});
</script>

<div class="vizel-root {className ?? ''}" data-vizel-root>
  {#if showToolbar && editor && toolbar}
    <VizelToolbar {editor}>
      {#snippet children({ editor: e })}
        {@render toolbar({ editor: e })}
      {/snippet}
    </VizelToolbar>
  {:else if showToolbar && editor}
    <VizelToolbar {editor} />
  {/if}
  <VizelEditor {editor} />
  {#if showBubbleMenu && editor && bubbleMenu}
    <VizelBubbleMenu {editor} {enableEmbed}>
      {@render bubbleMenu({ editor })}
    </VizelBubbleMenu>
  {:else if showBubbleMenu && editor}
    <VizelBubbleMenu {editor} {enableEmbed} />
  {/if}
  {#if restProps.locale}
    <VizelBlockMenu locale={restProps.locale} />
  {:else}
    <VizelBlockMenu />
  {/if}
  {#if children}
    {@render children({ editor })}
  {/if}
</div>
