// packages/vue/src/components/VizelToolbarOverflow.vue
<script setup lang="ts">
import type { Editor, VizelLocale, VizelToolbarActionItem } from "@vizel/core";
import { formatVizelTooltip, isVizelToolbarDropdownAction, vizelEnLocale } from "@vizel/core";
import { onBeforeUnmount, ref, watch } from "vue";
import VizelIcon from "./VizelIcon.vue";
import VizelToolbarButton from "./VizelToolbarButton.vue";
import VizelToolbarDropdown from "./VizelToolbarDropdown.vue";

export interface VizelToolbarOverflowProps {
  editor: Editor;
  actions: readonly VizelToolbarActionItem[];
  class?: string;
  /** Locale for translated UI strings */
  locale?: VizelLocale;
}

const props = defineProps<VizelToolbarOverflowProps>();

const isOpen = ref(false);
const containerRef = ref<HTMLDivElement | null>(null);
const triggerRef = ref<HTMLButtonElement | null>(null);

function close() {
  isOpen.value = false;
  triggerRef.value?.focus();
}

function toggle() {
  isOpen.value = !isOpen.value;
}

function handleActionClick(action: VizelToolbarActionItem) {
  if (!isVizelToolbarDropdownAction(action)) {
    action.run(props.editor);
    close();
  }
}

function handleOutsideClick(e: MouseEvent) {
  if (!(e.target instanceof Node)) return;
  if (containerRef.value && !containerRef.value.contains(e.target)) {
    close();
  }
}

function handleKeydown(e: KeyboardEvent) {
  if (e.key === "Escape") {
    e.preventDefault();
    close();
  }
}

watch(isOpen, (open) => {
  if (open) {
    document.addEventListener("mousedown", handleOutsideClick);
    document.addEventListener("keydown", handleKeydown);
  } else {
    document.removeEventListener("mousedown", handleOutsideClick);
    document.removeEventListener("keydown", handleKeydown);
  }
});

onBeforeUnmount(() => {
  document.removeEventListener("mousedown", handleOutsideClick);
  document.removeEventListener("keydown", handleKeydown);
});
</script>

<template>
  <div
    v-if="props.actions.length > 0"
    ref="containerRef"
    :class="['vizel-toolbar-overflow', $props.class]"
    data-vizel-toolbar-overflow
  >
    <button
      ref="triggerRef"
      type="button"
      class="vizel-toolbar-overflow-trigger"
      aria-haspopup="true"
      :aria-expanded="isOpen"
      :aria-label="props.locale?.toolbar.moreActions ?? vizelEnLocale.toolbar.moreActions"
      @click="toggle"
    >
      <VizelIcon name="ellipsis" />
    </button>

    <div
      v-if="isOpen"
      class="vizel-toolbar-overflow-popover"
      role="group"
    >
      <template v-for="action in props.actions" :key="action.id">
        <VizelToolbarDropdown
          v-if="isVizelToolbarDropdownAction(action)"
          :editor="props.editor"
          :dropdown="action"
        />
        <VizelToolbarButton
          v-else
          :action="action.id"
          :is-active="action.isActive(props.editor)"
          :disabled="!action.isEnabled(props.editor)"
          :title="formatVizelTooltip(action.label, action.shortcut)"
          @click="handleActionClick(action)"
        >
          <VizelIcon :name="action.icon" />
        </VizelToolbarButton>
      </template>
    </div>
  </div>
</template>

// packages/svelte/src/components/VizelToolbarOverflow.svelte
<script lang="ts" module>
import type { Editor, VizelLocale, VizelToolbarActionItem } from "@vizel/core";

export interface VizelToolbarOverflowProps {
  editor: Editor;
  actions: readonly VizelToolbarActionItem[];
  class?: string;
  /** Locale for translated UI strings */
  locale?: VizelLocale;
}
</script>

<script lang="ts">
import { formatVizelTooltip, isVizelToolbarDropdownAction, vizelEnLocale } from "@vizel/core";
import VizelIcon from "./VizelIcon.svelte";
import VizelToolbarButton from "./VizelToolbarButton.svelte";
import VizelToolbarDropdown from "./VizelToolbarDropdown.svelte";

let {
  editor,
  actions,
  class: className,
  locale,
}: VizelToolbarOverflowProps = $props();

let isOpen = $state(false);
let containerEl: HTMLDivElement | undefined = $state(undefined);
let triggerEl: HTMLButtonElement | undefined = $state(undefined);

function close() {
  isOpen = false;
  triggerEl?.focus();
}

function toggle() {
  isOpen = !isOpen;
}

function handleActionClick(action: VizelToolbarActionItem) {
  if (!isVizelToolbarDropdownAction(action)) {
    action.run(editor);
    close();
  }
}

$effect(() => {
  if (!isOpen) return;

  function handleClick(e: MouseEvent) {
    if (!(e.target instanceof Node)) return;
    if (containerEl && !containerEl.contains(e.target)) {
      close();
    }
  }
  function handleKey(e: KeyboardEvent) {
    if (e.key === "Escape") {
      e.preventDefault();
      close();
    }
  }

  document.addEventListener("mousedown", handleClick);
  document.addEventListener("keydown", handleKey);
  return () => {
    document.removeEventListener("mousedown", handleClick);
    document.removeEventListener("keydown", handleKey);
  };
});
</script>

{#if actions.length > 0}
  <div
    bind:this={containerEl}
    class="vizel-toolbar-overflow {className ?? ''}"
    data-vizel-toolbar-overflow
  >
    <button
      bind:this={triggerEl}
      type="button"
      class="vizel-toolbar-overflow-trigger"
      aria-haspopup="true"
      aria-expanded={isOpen}
      aria-label={locale?.toolbar.moreActions ?? vizelEnLocale.toolbar.moreActions}
      onclick={toggle}
    >
      <VizelIcon name="ellipsis" />
    </button>

    {#if isOpen}
      <div class="vizel-toolbar-overflow-popover" role="group">
        {#each actions as action (action.id)}
          {#if isVizelToolbarDropdownAction(action)}
            <VizelToolbarDropdown {editor} dropdown={action} />
          {:else}
            <VizelToolbarButton
              action={action.id}
              isActive={action.isActive(editor)}
              disabled={!action.isEnabled(editor)}
              title={formatVizelTooltip(action.label, action.shortcut)}
              onclick={() => handleActionClick(action)}
            >
              <VizelIcon name={action.icon} />
            </VizelToolbarButton>
          {/if}
        {/each}
      </div>
    {/if}
  </div>
{/if}
