// packages/vue/src/components/VizelThemeProvider.vue
<script setup lang="ts">
import {
  applyVizelTheme,
  createVizelSystemThemeListener,
  getStoredVizelTheme,
  getVizelSystemTheme,
  resolveVizelTheme,
  storeVizelTheme,
  VIZEL_DEFAULT_THEME,
  VIZEL_DEFAULT_THEME_STORAGE_KEY,
  type VizelResolvedTheme,
  type VizelTheme,
  type VizelThemeProviderOptions,
  type VizelThemeState,
} from "@vizel/core";
import { computed, onBeforeUnmount, onMounted, provide, ref, watch } from "vue";
import { VIZEL_THEME_CONTEXT_KEY } from "./VizelThemeContext.ts";

export interface VizelThemeProviderProps extends VizelThemeProviderOptions {}

const props = withDefaults(defineProps<VizelThemeProviderProps>(), {
  defaultTheme: VIZEL_DEFAULT_THEME,
  storageKey: VIZEL_DEFAULT_THEME_STORAGE_KEY,
  disableTransitionOnChange: false,
});

const theme = ref<VizelTheme>(getStoredVizelTheme(props.storageKey) ?? props.defaultTheme);
const systemTheme = ref<VizelResolvedTheme>(getVizelSystemTheme());

const resolvedTheme = computed(() => resolveVizelTheme(theme.value, systemTheme.value));

function setTheme(newTheme: VizelTheme) {
  theme.value = newTheme;
  storeVizelTheme(props.storageKey, newTheme);
}

const themeState: VizelThemeState = {
  get theme() {
    return theme.value;
  },
  get resolvedTheme() {
    return resolvedTheme.value;
  },
  get systemTheme() {
    return systemTheme.value;
  },
  setTheme,
};

provide(VIZEL_THEME_CONTEXT_KEY, themeState);

let cleanup: (() => void) | null = null;

onMounted(() => {
  // Apply initial theme
  applyVizelTheme(resolvedTheme.value, props.targetSelector, props.disableTransitionOnChange);

  // Listen for system theme changes
  cleanup = createVizelSystemThemeListener((newSystemTheme) => {
    systemTheme.value = newSystemTheme;
  });
});

// Watch for resolved theme changes
watch(resolvedTheme, (newResolvedTheme) => {
  applyVizelTheme(newResolvedTheme, props.targetSelector, props.disableTransitionOnChange);
});

onBeforeUnmount(() => {
  if (cleanup) {
    cleanup();
  }
});
</script>

<template>
  <slot />
</template>

// packages/svelte/src/components/VizelThemeProvider.svelte
<script lang="ts" module>
import type { VizelThemeProviderOptions } from "@vizel/core";
import type { Snippet } from "svelte";

export interface VizelThemeProviderProps extends VizelThemeProviderOptions {
  /** Children to render */
  children: Snippet;
}
</script>

<script lang="ts">
  import {
    applyVizelTheme,
    createVizelSystemThemeListener,
    VIZEL_DEFAULT_THEME,
    VIZEL_DEFAULT_THEME_STORAGE_KEY,
    getStoredVizelTheme,
    getVizelSystemTheme,
    resolveVizelTheme,
    storeVizelTheme,
    type VizelResolvedTheme,
    type VizelTheme,
    type VizelThemeState,
  } from "@vizel/core";
  import { setContext } from "svelte";
  import { VIZEL_THEME_CONTEXT_KEY } from "./VizelThemeContext.ts";

  let {
    children,
    defaultTheme = VIZEL_DEFAULT_THEME,
    storageKey = VIZEL_DEFAULT_THEME_STORAGE_KEY,
    targetSelector,
    disableTransitionOnChange = false,
  }: VizelThemeProviderProps = $props();

  // Intentionally capture initial values only - theme state should persist
  // regardless of prop changes after mount
  // svelte-ignore state_referenced_locally
  let theme = $state<VizelTheme>(getStoredVizelTheme(storageKey) ?? defaultTheme);
  let systemTheme = $state<VizelResolvedTheme>(getVizelSystemTheme());

  const resolvedTheme = $derived(resolveVizelTheme(theme, systemTheme));

  function setTheme(newTheme: VizelTheme) {
    theme = newTheme;
    storeVizelTheme(storageKey, newTheme);
  }

  const themeState: VizelThemeState = {
    get theme() {
      return theme;
    },
    get resolvedTheme() {
      return resolvedTheme;
    },
    get systemTheme() {
      return systemTheme;
    },
    setTheme,
  };

  setContext(VIZEL_THEME_CONTEXT_KEY, themeState);

  // Apply theme when resolved theme changes
  $effect(() => {
    applyVizelTheme(resolvedTheme, targetSelector, disableTransitionOnChange);
  });

  $effect(() => {
    // Listen for system theme changes
    const cleanup = createVizelSystemThemeListener((newSystemTheme: VizelResolvedTheme) => {
      systemTheme = newSystemTheme;
    });

    return cleanup;
  });
</script>

{@render children()}
