// packages/vue/src/components/VizelMentionMenu.vue
<script setup lang="ts">
import { resolveVizelListNavigation, type VizelMentionItem } from "@vizel/core";
import { computed, nextTick, ref, watch } from "vue";

export interface VizelMentionMenuRef {
  onKeyDown: (event: KeyboardEvent) => boolean;
}

export interface VizelMentionMenuProps {
  items: VizelMentionItem[];
  class?: string;
}

const props = defineProps<VizelMentionMenuProps>();

const emit = defineEmits<{
  select: [item: VizelMentionItem];
}>();

const selectedIndex = ref(0);
const itemRefs = ref<(HTMLElement | null)[]>([]);

const activeOptionId = computed(() => {
  const item = props.items[selectedIndex.value];
  return item ? `vizel-mention-${item.id}` : undefined;
});

watch(
  () => props.items,
  () => {
    selectedIndex.value = 0;
    itemRefs.value = new Array(props.items.length).fill(null);
  }
);

function scrollToSelected() {
  void nextTick(() => {
    const el = itemRefs.value[selectedIndex.value];
    if (el) {
      el.scrollIntoView({ block: "nearest", behavior: "smooth" });
    }
  });
}

function selectItem(index: number) {
  const item = props.items[index];
  if (item) {
    emit("select", item);
  }
}

function onKeyDown(event: KeyboardEvent): boolean {
  if (event.key === "Enter") {
    selectItem(selectedIndex.value);
    return true;
  }
  const next = resolveVizelListNavigation(event.key, selectedIndex.value, props.items.length);
  if (next === null) return false;
  selectedIndex.value = next;
  scrollToSelected();
  return true;
}

defineExpose<VizelMentionMenuRef>({ onKeyDown });
</script>

<template>
  <div
    :class="['vizel-mention-menu', props.class]"
    data-vizel-mention-menu
    role="listbox"
    aria-label="Mentions"
    :aria-activedescendant="activeOptionId"
  >
    <div v-if="items.length === 0" class="vizel-mention-menu-empty">
      No results
    </div>
    <template v-else>
      <div
        v-for="(item, index) in items"
        :key="item.id"
        :id="`vizel-mention-${item.id}`"
        :ref="(el) => { itemRefs[index] = el as HTMLElement | null }"
        :class="['vizel-mention-menu-item', { 'is-selected': index === selectedIndex }]"
        role="option"
        :aria-selected="index === selectedIndex"
        :tabindex="-1"
        @click="selectItem(index)"
        @keydown.enter="selectItem(index)"
      >
        <div class="vizel-mention-menu-item-avatar">
          <img v-if="item.avatar" :src="item.avatar" :alt="item.label" />
          <template v-else>{{ item.label.charAt(0).toUpperCase() }}</template>
        </div>
        <div class="vizel-mention-menu-item-content">
          <div class="vizel-mention-menu-item-label">{{ item.label }}</div>
          <div v-if="item.description" class="vizel-mention-menu-item-description">
            {{ item.description }}
          </div>
        </div>
      </div>
    </template>
  </div>
</template>

// packages/svelte/src/components/VizelMentionMenu.svelte
<script lang="ts" module>
import type { VizelMentionItem } from "@vizel/core";

export interface VizelMentionMenuRef {
  onKeyDown: (event: KeyboardEvent) => boolean;
}

export interface VizelMentionMenuProps {
  items: VizelMentionItem[];
  class?: string;
  oncommand?: (item: VizelMentionItem) => void;
}
</script>

<script lang="ts">
import { tick } from "svelte";

let {
  items,
  class: className,
  oncommand,
}: VizelMentionMenuProps = $props();

let selectedIndex = $state(0);
let itemRefs: (HTMLElement | null)[] = $state([]);

$effect(() => {
  if (itemRefs.length > items.length) {
    itemRefs.length = items.length;
  }
});

// Reset selection when items change
$effect(() => {
  // Access items to track changes
  void items.length;
  selectedIndex = 0;
});

function scrollToSelected() {
  tick().then(() => {
    const el = itemRefs[selectedIndex];
    if (el) {
      el.scrollIntoView({ block: "nearest", behavior: "smooth" });
    }
  });
}

function selectItem(index: number) {
  const item = items[index];
  if (item) {
    oncommand?.(item);
  }
}

export function onKeyDown(event: KeyboardEvent): boolean {
  if (event.key === "ArrowUp") {
    selectedIndex = (selectedIndex + items.length - 1) % items.length;
    scrollToSelected();
    return true;
  }
  if (event.key === "ArrowDown") {
    selectedIndex = (selectedIndex + 1) % items.length;
    scrollToSelected();
    return true;
  }
  if (event.key === "Enter") {
    selectItem(selectedIndex);
    return true;
  }
  return false;
}
</script>

<div class="vizel-mention-menu {className ?? ''}" data-vizel-mention-menu>
  {#if items.length === 0}
    <div class="vizel-mention-menu-empty">No results</div>
  {:else}
    {#each items as item, index (item.id)}
      <div
        bind:this={itemRefs[index]}
        class="vizel-mention-menu-item {index === selectedIndex ? 'is-selected' : ''}"
        role="option"
        aria-selected={index === selectedIndex}
        onclick={() => selectItem(index)}
        onkeydown={(e) => { if (e.key === "Enter") selectItem(index); }}
        tabindex={-1}
      >
        <div class="vizel-mention-menu-item-avatar">
          {#if item.avatar}
            <img src={item.avatar} alt={item.label} />
          {:else}
            {item.label.charAt(0).toUpperCase()}
          {/if}
        </div>
        <div class="vizel-mention-menu-item-content">
          <div class="vizel-mention-menu-item-label">{item.label}</div>
          {#if item.description}
            <div class="vizel-mention-menu-item-description">{item.description}</div>
          {/if}
        </div>
      </div>
    {/each}
  {/if}
</div>
