// packages/react/src/components/VizelSlashMenuEmpty.tsx
import type { ReactNode } from "react";

export interface VizelSlashMenuEmptyProps {
  children?: ReactNode;
  className?: string;
}

/**
 * An empty state component for the VizelSlashMenu when no results are found.
 *
 * @example
 * ```tsx
 * {items.length === 0 && (
 *   <VizelSlashMenuEmpty>No commands found</VizelSlashMenuEmpty>
 * )}
 * ```
 */
export function VizelSlashMenuEmpty({ children, className }: VizelSlashMenuEmptyProps) {
  return (
    <div className={`vizel-slash-menu-empty ${className ?? ""}`} data-vizel-slash-menu-empty="">
      {children ?? "No results"}
    </div>
  );
}

// packages/svelte/src/components/VizelSlashMenuEmpty.svelte
<script lang="ts" module>
import type { Snippet } from "svelte";

export interface VizelSlashMenuEmptyProps {
  /** Custom class name */
  class?: string;
  /** Custom content */
  children?: Snippet;
}
</script>

<script lang="ts">
let { class: className, children }: VizelSlashMenuEmptyProps = $props();
</script>

<div class="vizel-slash-menu-empty {className ?? ''}" data-vizel-slash-menu-empty="">
  {#if children}
    {@render children()}
  {:else}
    No results
  {/if}
</div>
