// apps/demo/react/src/App.tsx
import {
  createVizelFindReplaceExtension,
  type Editor,
  type JSONContent,
  setVizelMarkdown,
  useVizelAutoSave,
  useVizelComment,
  useVizelEditorState,
  useVizelTheme,
  useVizelVersionHistory,
  Vizel,
  VizelFindReplace,
  type VizelMarkdownFlavor,
  VizelSaveIndicator,
  VizelThemeProvider,
} from "@vizel/react";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { getFlavorContent } from "../../shared/content";
import reactLogo from "../../shared/logos/react.svg";
import { mockMentionItems, mockUploadImage } from "../../shared/utils";

function ThemeToggle() {
  const { theme, setTheme } = useVizelTheme();

  return (
    <button
      type="button"
      className="theme-toggle"
      onClick={() => setTheme(theme === "dark" ? "light" : "dark")}
      aria-label={`Switch to ${theme === "dark" ? "light" : "dark"} mode`}
    >
      {theme === "dark" ? "☀️" : "🌙"}
    </button>
  );
}

interface FeatureToggleProps {
  label: string;
  checked: boolean;
  onChange: (checked: boolean) => void;
}

function FeatureToggle({ label, checked, onChange }: FeatureToggleProps) {
  return (
    <label className="feature-toggle">
      <input type="checkbox" checked={checked} onChange={(e) => onChange(e.target.checked)} />
      <span className="feature-toggle-label">{label}</span>
    </label>
  );
}

interface DemoFeatures {
  toolbar: boolean;
  theme: boolean;
  autoSave: boolean;
  stats: boolean;
  syncPanel: boolean;
  comments: boolean;
  history: boolean;
}

type PanelTab = "markdown" | "json" | "history" | "comments";

function AppContent() {
  // Feature toggles (all enabled by default)
  const [features, setFeatures] = useState<DemoFeatures>({
    toolbar: true,
    theme: true,
    autoSave: true,
    stats: true,
    syncPanel: true,
    comments: true,
    history: true,
  });

  const [flavor, setFlavor] = useState<VizelMarkdownFlavor>("gfm");
  const [activeTab, setActiveTab] = useState<PanelTab>("markdown");
  const [jsonInput, setJsonInput] = useState("");
  const [markdownInput, setMarkdownInput] = useState("");
  const [versionDescription, setVersionDescription] = useState("");
  const [commentText, setCommentText] = useState("");
  const [replyTexts, setReplyTexts] = useState<Record<string, string>>({});

  // Store editor reference (useState for reactivity, unlike useRef)
  const [editor, setEditor] = useState<Editor | null>(null);

  // Track editor state for character/word count (only when stats enabled)
  const editorState = useVizelEditorState(features.stats ? editor : null);

  // Auto-save functionality (only when autoSave enabled)
  const { status, lastSaved } = useVizelAutoSave(features.autoSave ? editor : null, {
    debounceMs: 2000,
    storage: "localStorage",
    key: "vizel-demo-react",
  });

  // Version History (only when history panel enabled)
  const versionHistory = useVizelVersionHistory(features.history ? editor : null, {
    key: "vizel-demo-react-versions",
    maxVersions: 20,
  });

  // Comments (only when comments panel enabled)
  const commentManager = useVizelComment(features.comments ? editor : null, {
    key: "vizel-demo-react-comments",
  });

  // Track previous flavor for content swap on change
  const prevFlavorRef = useRef(flavor);

  // Swap content when flavor changes
  useEffect(() => {
    if (flavor !== prevFlavorRef.current && editor) {
      setVizelMarkdown(editor, getFlavorContent(flavor), { transformDiagrams: true });
      prevFlavorRef.current = flavor;
    }
  }, [flavor, editor]);

  // Find & Replace extension (stable reference)
  const findReplaceExtensions = useMemo(() => [createVizelFindReplaceExtension()], []);

  // Handle Markdown input change and sync to editor
  const handleMarkdownChange = useCallback(
    (value: string) => {
      setMarkdownInput(value);
      if (editor) {
        setVizelMarkdown(editor, value);
      }
    },
    [editor]
  );

  // Handle JSON input change and sync to editor
  const handleJsonChange = useCallback(
    (value: string) => {
      setJsonInput(value);
      try {
        const parsed = JSON.parse(value) as JSONContent;
        if (editor) {
          editor.commands.setContent(parsed);
        }
      } catch {
        // Invalid JSON, ignore
      }
    },
    [editor]
  );

  async function handleSaveVersion() {
    if (!versionDescription.trim()) return;
    await versionHistory.saveVersion(versionDescription.trim());
    setVersionDescription("");
  }

  async function handleAddComment() {
    if (!commentText.trim()) return;
    await commentManager.addComment(commentText.trim(), "Demo User");
    setCommentText("");
  }

  async function handleReply(commentId: string) {
    const text = replyTexts[commentId]?.trim();
    if (!text) return;
    await commentManager.replyToComment(commentId, text, "Demo User");
    setReplyTexts((prev) => ({ ...prev, [commentId]: "" }));
  }

  function updateFeature(key: keyof DemoFeatures, value: boolean) {
    setFeatures((prev) => ({ ...prev, [key]: value }));
  }

  const showPanel = features.syncPanel || features.history || features.comments;

  return (
    <div className="app">
      <header className="header">
        <div className="header-content">
          <img src={reactLogo} alt="React" className="framework-logo" />
          <div className="header-text">
            <h1>Vizel Editor</h1>
            <span className="framework-badge">React 19</span>
          </div>
          {features.theme && <ThemeToggle />}
        </div>
        <p className="header-description">
          A block-based rich text editor with slash commands and inline formatting
        </p>
      </header>

      <section className="features-section">
        <div className="features-header">
          <span className="features-title">Features</span>
          <span className="features-hint">Toggle to see minimal vs full-featured usage</span>
        </div>
        <div className="features-toggles">
          <FeatureToggle
            label="Toolbar"
            checked={features.toolbar}
            onChange={(v) => updateFeature("toolbar", v)}
          />
          <FeatureToggle
            label="Theme"
            checked={features.theme}
            onChange={(v) => updateFeature("theme", v)}
          />
          <FeatureToggle
            label="Auto-save"
            checked={features.autoSave}
            onChange={(v) => updateFeature("autoSave", v)}
          />
          <FeatureToggle
            label="Stats"
            checked={features.stats}
            onChange={(v) => updateFeature("stats", v)}
          />
          <FeatureToggle
            label="Sync Panel"
            checked={features.syncPanel}
            onChange={(v) => updateFeature("syncPanel", v)}
          />
          <FeatureToggle
            label="Comments"
            checked={features.comments}
            onChange={(v) => updateFeature("comments", v)}
          />
          <FeatureToggle
            label="History"
            checked={features.history}
            onChange={(v) => updateFeature("history", v)}
          />
          <label className="feature-toggle">
            <span className="feature-toggle-label">Flavor</span>
            <select
              className="feature-select"
              value={flavor}
              onChange={(e) => {
                const value = e.target.value;
                if (
                  value === "commonmark" ||
                  value === "gfm" ||
                  value === "obsidian" ||
                  value === "docusaurus"
                ) {
                  setFlavor(value);
                }
              }}
            >
              <option value="commonmark">CommonMark</option>
              <option value="gfm">GFM</option>
              <option value="obsidian">Obsidian</option>
              <option value="docusaurus">Docusaurus</option>
            </select>
          </label>
        </div>
      </section>

      <main className="main">
        <div className="editor-section">
          <div className="editor-container">
            <Vizel
              initialMarkdown={getFlavorContent(flavor)}
              autofocus="start"
              className="editor-content"
              showToolbar={features.toolbar}
              flavor={flavor}
              enableEmbed
              extensions={findReplaceExtensions}
              features={{
                markdown: true,
                mathematics: true,
                embed: true,
                details: true,
                diagram: true,
                wikiLink: true,
                comment: true,
                callout: true,
                tableOfContents: true,
                superscript: true,
                subscript: true,
                typography: true,
                mention: { items: mockMentionItems },
                image: {
                  onUpload: mockUploadImage,
                  maxFileSize: 10 * 1024 * 1024, // 10MB
                  onValidationError: (error) => {
                    alert(`Validation error: ${error.message}`);
                  },
                  onUploadError: (error) => {
                    alert(`Upload failed: ${error.message}`);
                  },
                },
              }}
              onCreate={({ editor: newEditor }) => {
                setEditor(newEditor);
                const json = newEditor.getJSON();
                setJsonInput(JSON.stringify(json, null, 2));
                setMarkdownInput(newEditor.getMarkdown());
              }}
              onUpdate={({ editor: updatedEditor }) => {
                const json = updatedEditor.getJSON();
                setJsonInput(JSON.stringify(json, null, 2));
                setMarkdownInput(updatedEditor.getMarkdown());
              }}
            >
              <VizelFindReplace editor={editor} />
            </Vizel>
            {(features.autoSave || features.stats) && (
              <div className="status-bar">
                {features.autoSave && (
                  <>
                    <VizelSaveIndicator status={status} lastSaved={lastSaved} />
                    {features.stats && <span className="status-divider">·</span>}
                  </>
                )}
                {features.stats && (
                  <>
                    <span className="status-item">{editorState.characterCount} characters</span>
                    <span className="status-divider">·</span>
                    <span className="status-item">{editorState.wordCount} words</span>
                  </>
                )}
              </div>
            )}
          </div>
        </div>

        {showPanel && (
          <div className="panel-section">
            <div className="panel-container">
              <div className="panel-tabs">
                {features.syncPanel && (
                  <button
                    type="button"
                    className="panel-tab"
                    data-active={activeTab === "markdown"}
                    onClick={() => setActiveTab("markdown")}
                  >
                    Markdown
                  </button>
                )}
                {features.syncPanel && (
                  <button
                    type="button"
                    className="panel-tab"
                    data-active={activeTab === "json"}
                    onClick={() => setActiveTab("json")}
                  >
                    JSON
                  </button>
                )}
                {features.history && (
                  <button
                    type="button"
                    className="panel-tab"
                    data-active={activeTab === "history"}
                    onClick={() => setActiveTab("history")}
                  >
                    History
                  </button>
                )}
                {features.comments && (
                  <button
                    type="button"
                    className="panel-tab"
                    data-active={activeTab === "comments"}
                    onClick={() => setActiveTab("comments")}
                  >
                    Comments
                  </button>
                )}
              </div>
              <div className="panel-content">
                {activeTab === "markdown" && features.syncPanel && (
                  <textarea
                    className="panel-textarea"
                    value={markdownInput}
                    onChange={(e) => handleMarkdownChange(e.target.value)}
                    placeholder="Edit Markdown here..."
                  />
                )}
                {activeTab === "json" && features.syncPanel && (
                  <textarea
                    className="panel-textarea"
                    value={jsonInput}
                    onChange={(e) => handleJsonChange(e.target.value)}
                    placeholder="Edit JSON here..."
                  />
                )}
                {activeTab === "history" && (
                  <div className="panel-list">
                    <div className="panel-action-bar">
                      <input
                        type="text"
                        placeholder="Version description..."
                        value={versionDescription}
                        onChange={(e) => setVersionDescription(e.target.value)}
                        onKeyDown={(e) => e.key === "Enter" && handleSaveVersion()}
                      />
                      <button
                        type="button"
                        className="panel-action-btn"
                        onClick={handleSaveVersion}
                      >
                        Save
                      </button>
                    </div>
                    {versionHistory.snapshots.length === 0 ? (
                      <div className="panel-list-empty">No versions saved yet</div>
                    ) : (
                      versionHistory.snapshots.map((snapshot) => (
                        <div key={snapshot.id} className="panel-item">
                          <div className="panel-item-header">
                            <span className="panel-item-text">
                              {snapshot.description || "Untitled"}
                            </span>
                            <span className="panel-item-meta">
                              {new Date(snapshot.timestamp).toLocaleString()}
                            </span>
                          </div>
                          <div className="panel-item-actions">
                            <button
                              type="button"
                              className="panel-item-btn"
                              onClick={() => versionHistory.restoreVersion(snapshot.id)}
                            >
                              Restore
                            </button>
                            <button
                              type="button"
                              className="panel-item-btn panel-item-btn--danger"
                              onClick={() => versionHistory.deleteVersion(snapshot.id)}
                            >
                              Delete
                            </button>
                          </div>
                        </div>
                      ))
                    )}
                  </div>
                )}
                {activeTab === "comments" && (
                  <div className="panel-list">
                    <div className="panel-action-bar">
                      <input
                        type="text"
                        placeholder="Select text, then add a comment..."
                        value={commentText}
                        onChange={(e) => setCommentText(e.target.value)}
                        onKeyDown={(e) => e.key === "Enter" && handleAddComment()}
                      />
                      <button type="button" className="panel-action-btn" onClick={handleAddComment}>
                        Add
                      </button>
                    </div>
                    {commentManager.comments.length === 0 ? (
                      <div className="panel-list-empty">No comments yet</div>
                    ) : (
                      commentManager.comments.map((comment) => (
                        // biome-ignore lint/a11y/useSemanticElements: Card contains nested interactive elements
                        <div
                          key={comment.id}
                          className={`panel-item ${comment.resolved ? "panel-item-resolved" : ""}`}
                          role="button"
                          tabIndex={0}
                          onClick={() => commentManager.setActiveComment(comment.id)}
                          onKeyDown={(e) =>
                            e.key === "Enter" && commentManager.setActiveComment(comment.id)
                          }
                        >
                          <div className="panel-item-header">
                            <span className="panel-item-text">{comment.text}</span>
                            <span className="panel-item-meta">
                              {comment.author && `${comment.author} · `}
                              {new Date(comment.createdAt).toLocaleString()}
                            </span>
                          </div>
                          <div className="panel-item-actions">
                            {comment.resolved ? (
                              <button
                                type="button"
                                className="panel-item-btn"
                                onClick={(e) => {
                                  e.stopPropagation();
                                  commentManager.reopenComment(comment.id);
                                }}
                              >
                                Reopen
                              </button>
                            ) : (
                              <button
                                type="button"
                                className="panel-item-btn"
                                onClick={(e) => {
                                  e.stopPropagation();
                                  commentManager.resolveComment(comment.id);
                                }}
                              >
                                Resolve
                              </button>
                            )}
                            <button
                              type="button"
                              className="panel-item-btn panel-item-btn--danger"
                              onClick={(e) => {
                                e.stopPropagation();
                                commentManager.removeComment(comment.id);
                              }}
                            >
                              Remove
                            </button>
                          </div>
                          {comment.replies.length > 0 && (
                            <div className="panel-replies">
                              {comment.replies.map((reply) => (
                                <div key={reply.id} className="panel-reply">
                                  <span className="panel-reply-meta">
                                    {reply.author && `${reply.author} · `}
                                    {new Date(reply.createdAt).toLocaleString()}
                                  </span>
                                  <div>{reply.text}</div>
                                </div>
                              ))}
                            </div>
                          )}
                          <div className="panel-reply-input">
                            <input
                              placeholder="Reply..."
                              value={replyTexts[comment.id] || ""}
                              onChange={(e) =>
                                setReplyTexts((prev) => ({ ...prev, [comment.id]: e.target.value }))
                              }
                              onKeyDown={(e) => e.key === "Enter" && handleReply(comment.id)}
                              onClick={(e) => e.stopPropagation()}
                            />
                            <button
                              type="button"
                              onClick={(e) => {
                                e.stopPropagation();
                                handleReply(comment.id);
                              }}
                            >
                              Reply
                            </button>
                          </div>
                        </div>
                      ))
                    )}
                  </div>
                )}
              </div>
            </div>
          </div>
        )}
      </main>

      <footer className="footer">
        <p>
          Built with <span className="footer-highlight">@vizel/react</span>
        </p>
      </footer>
    </div>
  );
}

export function App() {
  return (
    <VizelThemeProvider defaultTheme="system" storageKey="vizel-theme">
      <AppContent />
    </VizelThemeProvider>
  );
}

// apps/demo/svelte/src/App.svelte
<script lang="ts">
import type { Editor, JSONContent } from "@tiptap/core";
import type { VizelMarkdownFlavor } from "@vizel/core";
import { createVizelFindReplaceExtension, setVizelMarkdown } from "@vizel/core";
import {
  createVizelAutoSave,
  createVizelComment,
  createVizelEditorState,
  createVizelVersionHistory,
  Vizel,
  VizelFindReplace,
  VizelSaveIndicator,
  VizelThemeProvider,
} from "@vizel/svelte";
import { getFlavorContent } from "../../shared/content";
import svelteLogo from "../../shared/logos/svelte.svg";
import { mockMentionItems, mockUploadImage } from "../../shared/utils";
import ThemeToggle from "./ThemeToggle.svelte";

// Feature toggles (all enabled by default)
let features = $state({
  toolbar: true,
  theme: true,
  autoSave: true,
  stats: true,
  syncPanel: true,
  comments: false,
  history: false,
});

let flavor = $state<VizelMarkdownFlavor>("gfm");

type PanelTab = "markdown" | "json" | "history" | "comments";
let activeTab = $state<PanelTab>("markdown");
let jsonInput = $state("");
let markdownInput = $state("");
let versionDescription = $state("");
let commentText = $state("");
let replyTexts = $state<Record<string, string>>({});

// Store editor reference from Vizel component
let editorRef: Editor | null = $state(null);

// Track editor state for character/word count (only when stats enabled)
const editorState = createVizelEditorState(() => (features.stats ? editorRef : null));

// Auto-save functionality (only when autoSave enabled)
const autoSave = createVizelAutoSave(() => (features.autoSave ? editorRef : null), {
  debounceMs: 2000,
  storage: "localStorage",
  key: "vizel-demo-svelte",
});

// Version History (only when history panel enabled)
const versionHistory = createVizelVersionHistory(() => (features.history ? editorRef : null), {
  key: "vizel-demo-svelte-versions",
  maxVersions: 20,
});

// Comments (only when comments panel enabled)
const commentManager = createVizelComment(() => (features.comments ? editorRef : null), {
  key: "vizel-demo-svelte-comments",
});

// Find & Replace extension
const findReplaceExtensions = [createVizelFindReplaceExtension()];

// Swap content when flavor changes
let prevFlavor = $state(flavor);
$effect(() => {
  if (flavor !== prevFlavor && editorRef) {
    setVizelMarkdown(editorRef, getFlavorContent(flavor), { transformDiagrams: true });
  }
  prevFlavor = flavor;
});

const showPanel = $derived(features.syncPanel || features.history || features.comments);

function handleCreate({ editor }: { editor: Editor }) {
  editorRef = editor;
  jsonInput = JSON.stringify(editor.getJSON(), null, 2);
  markdownInput = editor.getMarkdown();
}

function handleUpdate({ editor }: { editor: Editor }) {
  jsonInput = JSON.stringify(editor.getJSON(), null, 2);
  markdownInput = editor.getMarkdown();
}

function handleMarkdownChange(event: Event) {
  const target = event.target;
  if (!(target instanceof HTMLTextAreaElement)) return;
  const value = target.value;
  markdownInput = value;
  if (editorRef) {
    setVizelMarkdown(editorRef, value);
  }
}

async function handleSaveVersion() {
  if (!versionDescription.trim()) return;
  await versionHistory.saveVersion(versionDescription.trim());
  versionDescription = "";
}

async function handleAddComment() {
  if (!commentText.trim()) return;
  await commentManager.addComment(commentText.trim(), "Demo User");
  commentText = "";
}

async function handleReply(commentId: string) {
  const text = replyTexts[commentId]?.trim();
  if (!text) return;
  await commentManager.replyToComment(commentId, text, "Demo User");
  replyTexts = { ...replyTexts, [commentId]: "" };
}

function handleJsonChange(event: Event) {
  const target = event.target;
  if (!(target instanceof HTMLTextAreaElement)) return;
  const value = target.value;
  jsonInput = value;
  try {
    const parsed = JSON.parse(value) as JSONContent;
    if (editorRef) {
      editorRef.commands.setContent(parsed);
    }
  } catch {
    // Invalid JSON, ignore
  }
}
</script>

<VizelThemeProvider defaultTheme="system" storageKey="vizel-theme">
<div class="app">
  <header class="header">
    <div class="header-content">
      <img src={svelteLogo} alt="Svelte" class="framework-logo" />
      <div class="header-text">
        <h1>Vizel Editor</h1>
        <span class="framework-badge">Svelte 5</span>
      </div>
      {#if features.theme}
        <ThemeToggle />
      {/if}
    </div>
    <p class="header-description">
      A block-based rich text editor with slash commands and inline formatting
    </p>
  </header>

  <section class="features-section">
    <div class="features-header">
      <span class="features-title">Features</span>
      <span class="features-hint">Toggle to see minimal vs full-featured usage</span>
    </div>
    <div class="features-toggles">
      <label class="feature-toggle">
        <input type="checkbox" bind:checked={features.toolbar} />
        <span class="feature-toggle-label">Toolbar</span>
      </label>
      <label class="feature-toggle">
        <input type="checkbox" bind:checked={features.theme} />
        <span class="feature-toggle-label">Theme</span>
      </label>
      <label class="feature-toggle">
        <input type="checkbox" bind:checked={features.autoSave} />
        <span class="feature-toggle-label">Auto-save</span>
      </label>
      <label class="feature-toggle">
        <input type="checkbox" bind:checked={features.stats} />
        <span class="feature-toggle-label">Stats</span>
      </label>
      <label class="feature-toggle">
        <input type="checkbox" bind:checked={features.syncPanel} />
        <span class="feature-toggle-label">Sync Panel</span>
      </label>
      <label class="feature-toggle">
        <input type="checkbox" bind:checked={features.comments} />
        <span class="feature-toggle-label">Comments</span>
      </label>
      <label class="feature-toggle">
        <input type="checkbox" bind:checked={features.history} />
        <span class="feature-toggle-label">History</span>
      </label>
      <label class="feature-toggle">
        <span class="feature-toggle-label">Flavor</span>
        <select
          class="feature-select"
          bind:value={flavor}
        >
          <option value="commonmark">CommonMark</option>
          <option value="gfm">GFM</option>
          <option value="obsidian">Obsidian</option>
          <option value="docusaurus">Docusaurus</option>
        </select>
      </label>
    </div>
  </section>

  <main class="main">
    <div class="editor-section">
      <div class="editor-container">
        <Vizel
          initialMarkdown={getFlavorContent(flavor)}
          autofocus="end"
          class="editor-content"
          showToolbar={features.toolbar}
          {flavor}
          enableEmbed
          extensions={findReplaceExtensions}
          features={{
            markdown: true,
            mathematics: true,
            embed: true,
            details: true,
            diagram: true,
            wikiLink: true,
            comment: true,
            callout: true,
            tableOfContents: true,
            superscript: true,
            subscript: true,
            typography: true,
            mention: { items: mockMentionItems },
            image: {
              onUpload: mockUploadImage,
              maxFileSize: 10 * 1024 * 1024,
              onValidationError: (error) => alert(`Validation error: ${error.message}`),
              onUploadError: (error) => alert(`Upload failed: ${error.message}`),
            },
          }}
          onCreate={handleCreate}
          onUpdate={handleUpdate}
        >
          {#snippet children({ editor: snippetEditor })}
            {#if snippetEditor}
              <VizelFindReplace editor={snippetEditor} />
            {/if}
          {/snippet}
        </Vizel>
        {#if features.autoSave || features.stats}
          <div class="status-bar">
            {#if features.autoSave}
              <VizelSaveIndicator status={autoSave.status} lastSaved={autoSave.lastSaved} />
              {#if features.stats}
                <span class="status-divider">·</span>
              {/if}
            {/if}
            {#if features.stats}
              <span class="status-item">{editorState.current.characterCount} characters</span>
              <span class="status-divider">·</span>
              <span class="status-item">{editorState.current.wordCount} words</span>
            {/if}
          </div>
        {/if}
      </div>
    </div>

    {#if showPanel}
      <div class="panel-section">
        <div class="panel-container">
          <div class="panel-tabs">
            {#if features.syncPanel}
              <button
                type="button"
                class="panel-tab"
                data-active={activeTab === 'markdown'}
                onclick={() => activeTab = 'markdown'}
              >
                Markdown
              </button>
              <button
                type="button"
                class="panel-tab"
                data-active={activeTab === 'json'}
                onclick={() => activeTab = 'json'}
              >
                JSON
              </button>
            {/if}
            {#if features.history}
              <button
                type="button"
                class="panel-tab"
                data-active={activeTab === 'history'}
                onclick={() => activeTab = 'history'}
              >
                History
              </button>
            {/if}
            {#if features.comments}
              <button
                type="button"
                class="panel-tab"
                data-active={activeTab === 'comments'}
                onclick={() => activeTab = 'comments'}
              >
                Comments
              </button>
            {/if}
          </div>
          <div class="panel-content">
            {#if activeTab === 'markdown' && features.syncPanel}
              <textarea
                class="panel-textarea"
                value={markdownInput}
                placeholder="Edit Markdown here..."
                oninput={handleMarkdownChange}
              ></textarea>
            {:else if activeTab === 'json' && features.syncPanel}
              <textarea
                class="panel-textarea"
                value={jsonInput}
                placeholder="Edit JSON here..."
                oninput={handleJsonChange}
              ></textarea>
            {:else if activeTab === 'history'}
              <div class="panel-list">
                <div class="panel-action-bar">
                  <input
                    type="text"
                    placeholder="Version description..."
                    bind:value={versionDescription}
                    onkeydown={(e) => e.key === 'Enter' && handleSaveVersion()}
                  />
                  <button type="button" class="panel-action-btn" onclick={handleSaveVersion}>
                    Save
                  </button>
                </div>
                {#if versionHistory.snapshots.length === 0}
                  <div class="panel-list-empty">No versions saved yet</div>
                {:else}
                  {#each versionHistory.snapshots as snapshot (snapshot.id)}
                    <div class="panel-item">
                      <div class="panel-item-header">
                        <span class="panel-item-text">{snapshot.description || "Untitled"}</span>
                        <span class="panel-item-meta">
                          {new Date(snapshot.timestamp).toLocaleString()}
                        </span>
                      </div>
                      <div class="panel-item-actions">
                        <button type="button" class="panel-item-btn" onclick={() => versionHistory.restoreVersion(snapshot.id)}>
                          Restore
                        </button>
                        <button type="button" class="panel-item-btn panel-item-btn--danger" onclick={() => versionHistory.deleteVersion(snapshot.id)}>
                          Delete
                        </button>
                      </div>
                    </div>
                  {/each}
                {/if}
              </div>
            {:else if activeTab === 'comments'}
              <div class="panel-list">
                <div class="panel-action-bar">
                  <input
                    type="text"
                    placeholder="Select text, then add a comment..."
                    bind:value={commentText}
                    onkeydown={(e) => e.key === 'Enter' && handleAddComment()}
                  />
                  <button type="button" class="panel-action-btn" onclick={handleAddComment}>
                    Add
                  </button>
                </div>
                {#if commentManager.comments.length === 0}
                  <div class="panel-list-empty">No comments yet</div>
                {:else}
                  {#each commentManager.comments as comment (comment.id)}
                    <div
                      class="panel-item {comment.resolved ? 'panel-item-resolved' : ''}"
                      onclick={() => commentManager.setActiveComment(comment.id)}
                      onkeydown={(e) => e.key === 'Enter' && commentManager.setActiveComment(comment.id)}
                      role="button"
                      tabindex="0"
                    >
                      <div class="panel-item-header">
                        <span class="panel-item-text">{comment.text}</span>
                        <span class="panel-item-meta">
                          {comment.author ? comment.author + ' · ' : ''}{new Date(comment.createdAt).toLocaleString()}
                        </span>
                      </div>
                      <div class="panel-item-actions">
                        {#if comment.resolved}
                          <button type="button" class="panel-item-btn" onclick={(e) => { e.stopPropagation(); commentManager.reopenComment(comment.id); }}>
                            Reopen
                          </button>
                        {:else}
                          <button type="button" class="panel-item-btn" onclick={(e) => { e.stopPropagation(); commentManager.resolveComment(comment.id); }}>
                            Resolve
                          </button>
                        {/if}
                        <button type="button" class="panel-item-btn panel-item-btn--danger" onclick={(e) => { e.stopPropagation(); commentManager.removeComment(comment.id); }}>
                          Remove
                        </button>
                      </div>
                      {#if comment.replies.length > 0}
                        <div class="panel-replies">
                          {#each comment.replies as reply (reply.id)}
                            <div class="panel-reply">
                              <span class="panel-reply-meta">
                                {reply.author ? reply.author + ' · ' : ''}{new Date(reply.createdAt).toLocaleString()}
                              </span>
                              <div>{reply.text}</div>
                            </div>
                          {/each}
                        </div>
                      {/if}
                      <!-- svelte-ignore a11y_click_events_have_key_events -->
                      <div class="panel-reply-input" onclick={(e) => e.stopPropagation()}>
                        <input
                          placeholder="Reply..."
                          value={replyTexts[comment.id] || ""}
                          oninput={(e) => { replyTexts = { ...replyTexts, [comment.id]: (e.target as HTMLInputElement).value }; }}
                          onkeydown={(e) => e.key === 'Enter' && handleReply(comment.id)}
                        />
                        <button type="button" onclick={() => handleReply(comment.id)}>Reply</button>
                      </div>
                    </div>
                  {/each}
                {/if}
              </div>
            {/if}
          </div>
        </div>
      </div>
    {/if}
  </main>

  <footer class="footer">
    <p>
      Built with <span class="footer-highlight">@vizel/svelte</span>
    </p>
  </footer>
</div>
</VizelThemeProvider>
