// apps/demo/vue/src/ThemeToggle.vue
<script setup lang="ts">
import { useVizelTheme } from "@vizel/vue";

const themeState = useVizelTheme();

function toggleTheme() {
  themeState.setTheme(themeState.resolvedTheme === "dark" ? "light" : "dark");
}
</script>

<template>
  <button
    type="button"
    class="theme-toggle"
    @click="toggleTheme"
    :aria-label="`Switch to ${themeState.resolvedTheme === 'dark' ? 'light' : 'dark'} mode`"
  >
    {{ themeState.resolvedTheme === "dark" ? "☀️" : "🌙" }}
  </button>
</template>

// apps/demo/svelte/src/ThemeToggle.svelte
<script lang="ts">
import { getTheme } from "@vizel/svelte";

const themeState = getTheme();

function toggleTheme() {
  themeState.setTheme(themeState.resolvedTheme === "dark" ? "light" : "dark");
}
</script>

<button
  type="button"
  class="theme-toggle"
  onclick={toggleTheme}
  aria-label={`Switch to ${themeState.resolvedTheme === 'dark' ? 'light' : 'dark'} mode`}
>
  {themeState.resolvedTheme === "dark" ? "☀️" : "🌙"}
</button>
