// packages/vue/src/components/BubbleMenuButton.vue
<script setup lang="ts">
export interface BubbleMenuButtonProps {
  /** Whether the button is in active state */
  isActive?: boolean;
  /** Whether the button is disabled */
  disabled?: boolean;
  /** Tooltip title */
  title?: string;
  /** Custom class name */
  class?: string;
  /** Action identifier for testing */
  action?: string;
}

const props = defineProps<BubbleMenuButtonProps>();

const emit = defineEmits<{
  click: [];
}>();
</script>

<template>
  <button
    type="button"
    :disabled="disabled"
    :aria-pressed="isActive"
    :class="[
      'vizel-bubble-menu-button',
      { 'is-active': isActive },
      $props.class,
    ]"
    :title="title"
    :data-active="isActive || undefined"
    :data-action="props.action"
    @click="emit('click')"
  >
    <slot />
  </button>
</template>

// packages/react/src/components/BubbleMenuButton.tsx
import type { ReactNode } from "react";

export interface BubbleMenuButtonProps {
  onClick: () => void;
  isActive?: boolean;
  disabled?: boolean;
  children: ReactNode;
  title?: string;
  className?: string;
  /** Action identifier for testing */
  action?: string;
}

/**
 * A button component for use in the BubbleMenu toolbar.
 *
 * @example
 * ```tsx
 * <BubbleMenuButton
 *   onClick={() => editor.chain().focus().toggleBold().run()}
 *   isActive={editor.isActive("bold")}
 *   title="Bold (Cmd+B)"
 * >
 *   <strong>B</strong>
 * </BubbleMenuButton>
 * ```
 */
export function BubbleMenuButton({
  onClick,
  isActive = false,
  disabled = false,
  children,
  title,
  className,
  action,
}: BubbleMenuButtonProps) {
  return (
    <button
      type="button"
      onClick={onClick}
      disabled={disabled}
      aria-pressed={isActive}
      className={`vizel-bubble-menu-button ${isActive ? "is-active" : ""} ${className ?? ""}`}
      title={title}
      data-active={isActive || undefined}
      data-action={action}
    >
      {children}
    </button>
  );
}
