// packages/svelte/src/components/BubbleMenuLinkEditor.svelte
<script lang="ts" module>
import type { Editor } from "@vizel/core";

export interface BubbleMenuLinkEditorProps {
  /** The editor instance */
  editor: Editor;
  /** Custom class name */
  class?: string;
  /** Close handler */
  onclose?: () => void;
  /** Enable embed option (requires Embed extension) */
  enableEmbed?: boolean;
}
</script>

<script lang="ts">
import { detectProvider } from "@vizel/core";
import { onMount, untrack } from "svelte";
import Icon from "./Icon.svelte";

let {
  editor,
  class: className,
  onclose,
  enableEmbed = false,
}: BubbleMenuLinkEditorProps = $props();

let formElement: HTMLFormElement;
let inputElement: HTMLInputElement;
let currentHref = $derived(editor.getAttributes("link").href || "");
let url = $state(untrack(() => editor.getAttributes("link").href || ""));
let asEmbed = $state(false);

// Check if embed extension is available
const canEmbed = $derived.by(() => {
  if (!enableEmbed) return false;
  // Check if embed extension is loaded
  const extensionManager = editor.extensionManager;
  return extensionManager.extensions.some((ext) => ext.name === "embed");
});

// Check if URL is a known embed provider
const isEmbedProvider = $derived.by(() => {
  if (!url.trim()) return false;
  return detectProvider(url.trim()) !== null;
});

// Handle click outside to close
function handleClickOutside(event: MouseEvent) {
  if (formElement && !formElement.contains(event.target as Node)) {
    onclose?.();
  }
}

// Handle Escape key to close
function handleKeyDown(event: KeyboardEvent) {
  if (event.key === "Escape") {
    event.preventDefault();
    event.stopImmediatePropagation();
    onclose?.();
  }
}

onMount(() => {
  inputElement?.focus();

  // Use setTimeout to avoid immediate trigger from the click that opened the editor
  const timeoutId = setTimeout(() => {
    document.addEventListener("mousedown", handleClickOutside);
  }, 0);
  // Use capture phase so this handler runs before BubbleMenu's handler
  document.addEventListener("keydown", handleKeyDown, true);

  return () => {
    clearTimeout(timeoutId);
    document.removeEventListener("mousedown", handleClickOutside);
    document.removeEventListener("keydown", handleKeyDown, true);
  };
});

function handleSubmit(e: Event) {
  e.preventDefault();
  const trimmedUrl = url.trim();

  if (!trimmedUrl) {
    editor.chain().focus().unsetLink().run();
    onclose?.();
    return;
  }

  if (asEmbed && canEmbed) {
    // Remove the link first, then insert embed
    editor.chain().focus().unsetLink().setEmbed({ url: trimmedUrl }).run();
  } else {
    editor.chain().focus().setLink({ href: trimmedUrl }).run();
  }
  onclose?.();
}

function handleRemove() {
  editor.chain().focus().unsetLink().run();
  onclose?.();
}
</script>

<form
  bind:this={formElement}
  class="vizel-link-editor {className ?? ''}"
  onsubmit={handleSubmit}
>
  <div class="vizel-link-editor-row">
    <input
      bind:this={inputElement}
      bind:value={url}
      type="url"
      placeholder="Enter URL..."
      class="vizel-link-input"
    />
    <button type="submit" class="vizel-link-button" title="Apply">
      <Icon name="check" />
    </button>
    {#if currentHref}
      <button
        type="button"
        class="vizel-link-button vizel-link-remove"
        title="Remove link"
        onclick={handleRemove}
      >
        <Icon name="x" />
      </button>
    {/if}
  </div>
  {#if canEmbed && isEmbedProvider}
    <div class="vizel-link-editor-embed-toggle">
      <input
        id="vizel-embed-toggle"
        type="checkbox"
        bind:checked={asEmbed}
      />
      <label for="vizel-embed-toggle">Embed as rich content</label>
    </div>
  {/if}
</form>

// packages/react/src/components/BubbleMenuLinkEditor.tsx
import { detectProvider, type Editor } from "@vizel/core";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Icon } from "./Icon.tsx";

export interface BubbleMenuLinkEditorProps {
  editor: Editor;
  onClose: () => void;
  className?: string;
  /** Enable embed option (requires Embed extension) */
  enableEmbed?: boolean;
}

/**
 * A link editor component for editing hyperlinks in the BubbleMenu.
 * Provides an input field for URL entry and buttons to apply or remove the link.
 * Optionally supports converting links to embeds when the Embed extension is loaded.
 *
 * @example
 * ```tsx
 * const [showLinkEditor, setShowLinkEditor] = useState(false);
 *
 * {showLinkEditor ? (
 *   <BubbleMenuLinkEditor
 *     editor={editor}
 *     onClose={() => setShowLinkEditor(false)}
 *     enableEmbed
 *   />
 * ) : (
 *   <BubbleMenuButton onClick={() => setShowLinkEditor(true)}>
 *     Link
 *   </BubbleMenuButton>
 * )}
 * ```
 */
export function BubbleMenuLinkEditor({
  editor,
  onClose,
  className,
  enableEmbed = false,
}: BubbleMenuLinkEditorProps) {
  const currentHref = editor.getAttributes("link").href || "";
  const [url, setUrl] = useState(currentHref);
  const [asEmbed, setAsEmbed] = useState(false);
  const formRef = useRef<HTMLFormElement>(null);
  const inputRef = useRef<HTMLInputElement>(null);

  // Check if embed extension is available
  const canEmbed = useMemo(() => {
    if (!enableEmbed) return false;
    // Check if setEmbed command exists (embed extension is loaded)
    const extensionManager = editor.extensionManager;
    return extensionManager.extensions.some((ext) => ext.name === "embed");
  }, [editor, enableEmbed]);

  // Check if URL is a known embed provider
  const isEmbedProvider = useMemo(() => {
    if (!url.trim()) return false;
    return detectProvider(url.trim()) !== null;
  }, [url]);

  // Auto-focus input on mount
  useEffect(() => {
    inputRef.current?.focus();
  }, []);

  // Handle click outside to close
  useEffect(() => {
    function handleClickOutside(event: MouseEvent) {
      if (formRef.current && !formRef.current.contains(event.target as Node)) {
        onClose();
      }
    }

    // Handle Escape key to close
    function handleKeyDown(event: KeyboardEvent) {
      if (event.key === "Escape") {
        event.preventDefault();
        event.stopImmediatePropagation();
        onClose();
      }
    }

    // Use setTimeout to avoid immediate trigger from the click that opened the editor
    const timeoutId = setTimeout(() => {
      document.addEventListener("mousedown", handleClickOutside);
    }, 0);
    // Use capture phase so this handler runs before BubbleMenu's handler
    document.addEventListener("keydown", handleKeyDown, true);

    return () => {
      clearTimeout(timeoutId);
      document.removeEventListener("mousedown", handleClickOutside);
      document.removeEventListener("keydown", handleKeyDown, true);
    };
  }, [onClose]);

  const handleSubmit = useCallback(
    (e: React.FormEvent) => {
      e.preventDefault();
      const trimmedUrl = url.trim();

      if (!trimmedUrl) {
        editor.chain().focus().unsetLink().run();
        onClose();
        return;
      }

      if (asEmbed && canEmbed) {
        // Remove the link first, then insert embed
        editor.chain().focus().unsetLink().setEmbed({ url: trimmedUrl }).run();
      } else {
        editor.chain().focus().setLink({ href: trimmedUrl }).run();
      }
      onClose();
    },
    [editor, url, asEmbed, canEmbed, onClose]
  );

  const handleRemove = useCallback(() => {
    editor.chain().focus().unsetLink().run();
    onClose();
  }, [editor, onClose]);

  return (
    <form ref={formRef} onSubmit={handleSubmit} className={`vizel-link-editor ${className ?? ""}`}>
      <div className="vizel-link-editor-row">
        <input
          ref={inputRef}
          type="url"
          value={url}
          onChange={(e) => setUrl(e.target.value)}
          placeholder="Enter URL..."
          className="vizel-link-input"
        />
        <button type="submit" className="vizel-link-button" title="Apply">
          <Icon name="check" />
        </button>
        {currentHref && (
          <button
            type="button"
            onClick={handleRemove}
            className="vizel-link-button vizel-link-remove"
            title="Remove link"
          >
            <Icon name="x" />
          </button>
        )}
      </div>
      {canEmbed && isEmbedProvider && (
        <div className="vizel-link-editor-embed-toggle">
          <input
            type="checkbox"
            id="vizel-embed-toggle"
            checked={asEmbed}
            onChange={(e) => setAsEmbed(e.target.checked)}
          />
          <label htmlFor="vizel-embed-toggle">Embed as rich content</label>
        </div>
      )}
    </form>
  );
}
