// packages/vue/src/components/SaveIndicator.vue
<script setup lang="ts">
import { formatRelativeTime, type SaveStatus } from "@vizel/core";
import { computed, onBeforeUnmount, onMounted, ref, watch } from "vue";
import Icon from "./Icon.vue";

export interface SaveIndicatorProps {
  /** Current save status */
  status: SaveStatus;
  /** Timestamp of last successful save */
  lastSaved?: Date | null;
  /** Show relative timestamp (default: true) */
  showTimestamp?: boolean;
  /** Custom class name */
  class?: string;
}

const props = withDefaults(defineProps<SaveIndicatorProps>(), {
  showTimestamp: true,
});

const relativeTime = ref("");
let intervalId: ReturnType<typeof setInterval> | null = null;

function updateTime() {
  if (props.lastSaved) {
    relativeTime.value = formatRelativeTime(props.lastSaved);
  } else {
    relativeTime.value = "";
  }
}

onMounted(() => {
  updateTime();
  intervalId = setInterval(updateTime, 10000);
});

watch(
  () => props.lastSaved,
  () => {
    updateTime();
  }
);

onBeforeUnmount(() => {
  if (intervalId) {
    clearInterval(intervalId);
  }
});

const statusText = computed(() => {
  switch (props.status) {
    case "saved":
      return "Saved";
    case "saving":
      return "Saving...";
    case "unsaved":
      return "Unsaved";
    case "error":
      return "Error saving";
    default:
      return "";
  }
});

const shouldShowTimestamp = computed(() => {
  return props.showTimestamp && props.lastSaved && relativeTime.value && props.status === "saved";
});
</script>

<template>
  <div
    :class="['vizel-save-indicator', `vizel-save-indicator--${props.status}`, $props.class]"
    role="status"
    aria-live="polite"
    data-vizel-save-indicator
  >
    <span class="vizel-save-indicator-icon" aria-hidden="true">
      <template v-if="props.status === 'saved'">
        <Icon name="check" />
      </template>
      <template v-else-if="props.status === 'saving'">
        <span class="vizel-save-indicator-spinner" aria-hidden="true">
          <Icon name="loader" />
        </span>
      </template>
      <template v-else-if="props.status === 'unsaved'">
        <Icon name="circle" />
      </template>
      <template v-else-if="props.status === 'error'">
        <Icon name="warning" />
      </template>
    </span>
    <span class="vizel-save-indicator-text">{{ statusText }}</span>
    <span v-if="shouldShowTimestamp" class="vizel-save-indicator-timestamp">{{ relativeTime }}</span>
  </div>
</template>

// packages/react/src/components/SaveIndicator.tsx
import { formatRelativeTime, type SaveStatus } from "@vizel/core";
import { useEffect, useState } from "react";
import { Icon } from "./Icon.tsx";

export interface SaveIndicatorProps {
  /** Current save status */
  status: SaveStatus;
  /** Timestamp of last successful save */
  lastSaved?: Date | null;
  /** Show relative timestamp (default: true) */
  showTimestamp?: boolean;
  /** Custom class name */
  className?: string;
}

/**
 * Visual indicator for the current save state of the editor.
 *
 * @example
 * ```tsx
 * <SaveIndicator
 *   status={status}
 *   lastSaved={lastSaved}
 *   showTimestamp
 * />
 * ```
 */
export function SaveIndicator({
  status,
  lastSaved,
  showTimestamp = true,
  className,
}: SaveIndicatorProps) {
  const [relativeTime, setRelativeTime] = useState<string>("");

  // Update relative time every 10 seconds
  useEffect(() => {
    if (!lastSaved) {
      setRelativeTime("");
      return;
    }

    const updateTime = () => {
      setRelativeTime(formatRelativeTime(lastSaved));
    };

    updateTime();
    const interval = setInterval(updateTime, 10000);

    return () => clearInterval(interval);
  }, [lastSaved]);

  const getStatusIcon = () => {
    switch (status) {
      case "saved":
        return <Icon name="check" />;
      case "saving":
        return (
          <span className="vizel-save-indicator-spinner" aria-hidden="true">
            <Icon name="loader" />
          </span>
        );
      case "unsaved":
        return <Icon name="circle" />;
      case "error":
        return <Icon name="warning" />;
      default:
        return null;
    }
  };

  const getStatusText = () => {
    switch (status) {
      case "saved":
        return "Saved";
      case "saving":
        return "Saving...";
      case "unsaved":
        return "Unsaved";
      case "error":
        return "Error saving";
      default:
        return "";
    }
  };

  const shouldShowTimestamp = showTimestamp && lastSaved && relativeTime && status === "saved";

  return (
    // biome-ignore lint/a11y/useSemanticElements: role="status" is appropriate for non-form status announcements
    <div
      className={`vizel-save-indicator vizel-save-indicator--${status} ${className ?? ""}`}
      role="status"
      aria-live="polite"
      data-vizel-save-indicator
    >
      <span className="vizel-save-indicator-icon" aria-hidden="true">
        {getStatusIcon()}
      </span>
      <span className="vizel-save-indicator-text">{getStatusText()}</span>
      {shouldShowTimestamp && (
        <span className="vizel-save-indicator-timestamp">{relativeTime}</span>
      )}
    </div>
  );
}
