// packages/svelte/src/components/SlashMenuEmpty.svelte
<script lang="ts" module>
import type { Snippet } from "svelte";

export interface SlashMenuEmptyProps {
  /** Custom class name */
  class?: string;
  /** Custom content */
  children?: Snippet;
}
</script>

<script lang="ts">
let { class: className, children }: SlashMenuEmptyProps = $props();
</script>

<div class="vizel-slash-menu-empty {className ?? ''}">
  {#if children}
    {@render children()}
  {:else}
    No results
  {/if}
</div>

// packages/react/src/components/SlashMenuEmpty.tsx
import type { ReactNode } from "react";

export interface SlashMenuEmptyProps {
  children?: ReactNode;
  className?: string;
}

/**
 * An empty state component for the SlashMenu when no results are found.
 *
 * @example
 * ```tsx
 * {items.length === 0 && (
 *   <SlashMenuEmpty>No commands found</SlashMenuEmpty>
 * )}
 * ```
 */
export function SlashMenuEmpty({ children, className }: SlashMenuEmptyProps) {
  return (
    <div className={`vizel-slash-menu-empty ${className ?? ""}`}>{children ?? "No results"}</div>
  );
}
