// packages/svelte/src/components/SlashMenu.svelte
<script lang="ts" module>
import type { SlashCommandItem } from "@vizel/core";
import type { Snippet } from "svelte";

export interface SlashMenuRef {
  onKeyDown: (event: KeyboardEvent) => boolean;
}

export interface SlashMenuProps {
  /** The list of slash command items */
  items: SlashCommandItem[];
  /** Custom class name */
  class?: string;
  /** Command handler */
  oncommand?: (item: SlashCommandItem) => void;
  /** Whether to show items grouped by category (default: true when not searching) */
  showGroups?: boolean;
  /** Custom group order */
  groupOrder?: string[];
  /** Custom item renderer */
  renderItem?: Snippet<[{ item: SlashCommandItem; isSelected: boolean; onclick: () => void }]>;
  /** Custom empty state renderer */
  renderEmpty?: Snippet;
}
</script>

<script lang="ts">
import { groupSlashCommands, type SlashCommandGroup } from "@vizel/core";
import { tick } from "svelte";
import SlashMenuItem from "./SlashMenuItem.svelte";
import SlashMenuEmpty from "./SlashMenuEmpty.svelte";

let {
  items,
  class: className,
  oncommand,
  showGroups = true,
  groupOrder,
  renderItem,
  renderEmpty,
}: SlashMenuProps = $props();

let selectedIndex = $state(0);
let itemRefs: (HTMLElement | null)[] = $state([]);

// Group items when showGroups is true and there are enough items
const groups = $derived.by<SlashCommandGroup[]>(() => {
  if (!showGroups || items.length <= 5) {
    // Don't group if explicitly disabled or few items (likely search results)
    return [{ name: "", items }];
  }
  return groupSlashCommands(items, groupOrder);
});

// Flatten for navigation
const flatItems = $derived(groups.flatMap((g) => g.items));

// Reset selection when items change
$effect(() => {
  items;
  selectedIndex = 0;
});

// Scroll selected item into view when selection changes
$effect(() => {
  const index = selectedIndex;
  tick().then(() => {
    const selectedElement = itemRefs[index];
    if (selectedElement) {
      selectedElement.scrollIntoView({ block: "nearest", behavior: "smooth" });
    }
  });
});

function selectItem(index: number) {
  const item = flatItems[index];
  if (item) {
    oncommand?.(item);
  }
}

// Navigate to next group with Tab
function tabHandler() {
  if (groups.length <= 1) return;

  let currentGroupIndex = 0;
  let itemCount = 0;
  for (let i = 0; i < groups.length; i++) {
    const group = groups[i];
    if (!group) continue;
    if (selectedIndex < itemCount + group.items.length) {
      currentGroupIndex = i;
      break;
    }
    itemCount += group.items.length;
  }

  // Move to next group
  const nextGroupIndex = (currentGroupIndex + 1) % groups.length;
  let nextIndex = 0;
  for (let i = 0; i < nextGroupIndex; i++) {
    const group = groups[i];
    if (group) {
      nextIndex += group.items.length;
    }
  }
  selectedIndex = nextIndex;
}

// Calculate global index for items
function getGlobalIndex(groupIndex: number, itemIndex: number): number {
  let index = 0;
  for (let i = 0; i < groupIndex; i++) {
    const group = groups[i];
    if (group) {
      index += group.items.length;
    }
  }
  return index + itemIndex;
}

export function onKeyDown(event: KeyboardEvent): boolean {
  if (event.key === "ArrowUp") {
    selectedIndex = (selectedIndex + flatItems.length - 1) % flatItems.length;
    return true;
  }

  if (event.key === "ArrowDown") {
    selectedIndex = (selectedIndex + 1) % flatItems.length;
    return true;
  }

  if (event.key === "Enter") {
    selectItem(selectedIndex);
    return true;
  }

  if (event.key === "Tab") {
    event.preventDefault();
    tabHandler();
    return true;
  }

  return false;
}
</script>

<div class="vizel-slash-menu {className ?? ''}" data-vizel-slash-menu>
  {#if flatItems.length === 0}
    {#if renderEmpty}
      {@render renderEmpty()}
    {:else}
      <SlashMenuEmpty />
    {/if}
  {:else}
    {#each groups as group, groupIndex (group.name || groupIndex)}
      {#if group.name}
        <!-- Group with header -->
        <div class="vizel-slash-menu-group" data-vizel-slash-menu-group>
          <div class="vizel-slash-menu-group-header">{group.name}</div>
          {#each group.items as item, itemIndex (item.title)}
            {@const globalIdx = getGlobalIndex(groupIndex, itemIndex)}
            <div bind:this={itemRefs[globalIdx]}>
              {#if renderItem}
                {@render renderItem({
                  item,
                  isSelected: globalIdx === selectedIndex,
                  onclick: () => selectItem(globalIdx),
                })}
              {:else}
                <SlashMenuItem
                  {item}
                  isSelected={globalIdx === selectedIndex}
                  onclick={() => selectItem(globalIdx)}
                />
              {/if}
            </div>
          {/each}
        </div>
      {:else}
        <!-- Items without group header -->
        {#each group.items as item, itemIndex (item.title)}
          {@const globalIdx = getGlobalIndex(groupIndex, itemIndex)}
          <div bind:this={itemRefs[globalIdx]}>
            {#if renderItem}
              {@render renderItem({
                item,
                isSelected: globalIdx === selectedIndex,
                onclick: () => selectItem(globalIdx),
              })}
            {:else}
              <SlashMenuItem
                {item}
                isSelected={globalIdx === selectedIndex}
                onclick={() => selectItem(globalIdx)}
              />
            {/if}
          </div>
        {/each}
      {/if}
    {/each}
  {/if}
</div>

// packages/react/src/components/SlashMenu.tsx
import { groupSlashCommands, type SlashCommandGroup, type SlashCommandItem } from "@vizel/core";
import {
  forwardRef,
  type ReactNode,
  useCallback,
  useEffect,
  useImperativeHandle,
  useMemo,
  useRef,
  useState,
} from "react";
import { SlashMenuEmpty } from "./SlashMenuEmpty.tsx";
import { SlashMenuItem, type SlashMenuItemProps } from "./SlashMenuItem.tsx";

export interface SlashMenuRef {
  onKeyDown: (props: { event: KeyboardEvent }) => boolean;
}

export interface SlashMenuProps {
  items: SlashCommandItem[];
  command: (item: SlashCommandItem) => void;
  /** Custom class name for the menu container */
  className?: string;
  /** Whether to show items grouped by category (default: true when not searching) */
  showGroups?: boolean;
  /** Custom render function for items */
  renderItem?: (props: {
    item: SlashCommandItem;
    isSelected: boolean;
    onClick: () => void;
  }) => ReactNode;
  /** Custom empty state component */
  renderEmpty?: () => ReactNode;
  /** Custom group order */
  groupOrder?: string[];
}

/**
 * Slash command menu component for displaying command suggestions.
 * Supports grouping, keyboard navigation, and fuzzy search highlighting.
 *
 * @example
 * ```tsx
 * // Basic usage via createSlashMenuRenderer
 * import { SlashCommand, createSlashMenuRenderer } from '@vizel/react';
 *
 * const editor = useEditor({
 *   extensions: [
 *     SlashCommand.configure({
 *       suggestion: createSlashMenuRenderer(),
 *     }),
 *   ],
 * });
 * ```
 */
export const SlashMenu = forwardRef<SlashMenuRef, SlashMenuProps>(
  ({ items, command, className, showGroups = true, renderItem, renderEmpty, groupOrder }, ref) => {
    const [selectedIndex, setSelectedIndex] = useState(0);
    const itemRefs = useRef<(HTMLDivElement | null)[]>([]);

    // Group items when showGroups is true and there are enough items
    const groups = useMemo<SlashCommandGroup[]>(() => {
      if (!showGroups || items.length <= 5) {
        // Don't group if explicitly disabled or few items (likely search results)
        return [{ name: "", items }];
      }
      return groupSlashCommands(items, groupOrder);
    }, [items, showGroups, groupOrder]);

    // Flatten for navigation
    const flatItems = useMemo(() => groups.flatMap((g) => g.items), [groups]);

    // Scroll selected item into view when selection changes
    useEffect(() => {
      const selectedElement = itemRefs.current[selectedIndex];
      if (selectedElement) {
        selectedElement.scrollIntoView({ block: "nearest", behavior: "smooth" });
      }
    }, [selectedIndex]);

    const selectItem = useCallback(
      (index: number) => {
        const item = flatItems[index];
        if (item) {
          command(item);
        }
      },
      [flatItems, command]
    );

    const upHandler = useCallback(() => {
      setSelectedIndex((index) => (index + flatItems.length - 1) % flatItems.length);
    }, [flatItems.length]);

    const downHandler = useCallback(() => {
      setSelectedIndex((index) => (index + 1) % flatItems.length);
    }, [flatItems.length]);

    const enterHandler = useCallback(() => {
      selectItem(selectedIndex);
    }, [selectItem, selectedIndex]);

    // Navigate to next group with Tab
    const tabHandler = useCallback(() => {
      if (groups.length <= 1) return;

      let currentGroupIndex = 0;
      let itemCount = 0;
      for (let i = 0; i < groups.length; i++) {
        const group = groups[i];
        if (!group) continue;
        if (selectedIndex < itemCount + group.items.length) {
          currentGroupIndex = i;
          break;
        }
        itemCount += group.items.length;
      }

      // Move to next group
      const nextGroupIndex = (currentGroupIndex + 1) % groups.length;
      let nextIndex = 0;
      for (let i = 0; i < nextGroupIndex; i++) {
        const group = groups[i];
        if (group) {
          nextIndex += group.items.length;
        }
      }
      setSelectedIndex(nextIndex);
    }, [groups, selectedIndex]);

    // Reset selection when items change (tracked via groups length)
    // biome-ignore lint/correctness/useExhaustiveDependencies: intentional dependency on groups to reset selection
    useEffect(() => {
      setSelectedIndex(0);
    }, [groups]);

    useImperativeHandle(ref, () => ({
      onKeyDown: ({ event }) => {
        if (event.key === "ArrowUp") {
          upHandler();
          return true;
        }

        if (event.key === "ArrowDown") {
          downHandler();
          return true;
        }

        if (event.key === "Enter") {
          enterHandler();
          return true;
        }

        if (event.key === "Tab") {
          event.preventDefault();
          tabHandler();
          return true;
        }

        return false;
      },
    }));

    if (flatItems.length === 0) {
      return (
        <div className={`vizel-slash-menu ${className ?? ""}`} data-vizel-slash-menu="">
          {renderEmpty?.() ?? <SlashMenuEmpty />}
        </div>
      );
    }

    // Render with groups
    let globalIndex = 0;

    return (
      <div className={`vizel-slash-menu ${className ?? ""}`} data-vizel-slash-menu="">
        {groups.map((group) => {
          const groupItems = group.items.map((item) => {
            const index = globalIndex++;
            const isSelected = index === selectedIndex;
            const onClick = () => selectItem(index);

            if (renderItem) {
              return (
                <div
                  key={item.title}
                  ref={(el) => {
                    itemRefs.current[index] = el;
                  }}
                >
                  {renderItem({ item, isSelected, onClick })}
                </div>
              );
            }

            return (
              <div
                key={item.title}
                ref={(el) => {
                  itemRefs.current[index] = el;
                }}
              >
                <SlashMenuItem item={item} isSelected={isSelected} onClick={onClick} />
              </div>
            );
          });

          // If no group name, just render items
          if (!group.name) {
            return groupItems;
          }

          return (
            <div key={group.name} className="vizel-slash-menu-group" data-vizel-slash-menu-group>
              <div className="vizel-slash-menu-group-header">{group.name}</div>
              {groupItems}
            </div>
          );
        })}
      </div>
    );
  }
);

SlashMenu.displayName = "SlashMenu";

// Re-export SlashMenuItem props for consumers
export type { SlashMenuItemProps };
