// packages/svelte/src/components/VizelNodeSelector.svelte
<script lang="ts" module>
import type { Editor } from "@tiptap/core";
import type { VizelNodeTypeOption } from "@vizel/core";

export interface VizelNodeSelectorProps {
  /** The editor instance */
  editor: Editor;
  /** Custom node types (defaults to vizelDefaultNodeTypes) */
  nodeTypes?: VizelNodeTypeOption[];
  /** Custom class name */
  class?: string;
}
</script>

<script lang="ts">
import { vizelDefaultNodeTypes, getVizelActiveNodeType } from "@vizel/core";
import { createVizelState } from "../runes/createVizelState.svelte.ts";
import VizelIcon from "./VizelIcon.svelte";

let { editor, nodeTypes = vizelDefaultNodeTypes, class: className }: VizelNodeSelectorProps = $props();

// Subscribe to editor state changes
const editorState = createVizelState(() => editor);

let isOpen = $state(false);
let focusedIndex = $state(0);
let containerRef: HTMLDivElement | undefined = $state();
let dropdownRef: HTMLDivElement | undefined = $state();

const activeNodeType = $derived.by(() => {
  void editorState.current; // Trigger reactivity
  return getVizelActiveNodeType(editor, nodeTypes);
});

const currentLabel = $derived(activeNodeType?.label ?? "Text");
const currentIcon = $derived(activeNodeType?.icon ?? "paragraph");

// Close dropdown when clicking outside
function handleClickOutside(event: MouseEvent) {
  if (containerRef && !containerRef.contains(event.target as Node)) {
    isOpen = false;
  }
}

$effect(() => {
  document.addEventListener("mousedown", handleClickOutside);
  return () => document.removeEventListener("mousedown", handleClickOutside);
});

// Focus the dropdown when it opens to ensure keyboard navigation works
$effect(() => {
  if (isOpen && dropdownRef) {
    dropdownRef.focus();
  }
});

function handleKeyDown(event: KeyboardEvent) {
  if (!isOpen) {
    if (event.key === "Enter" || event.key === " " || event.key === "ArrowDown") {
      event.preventDefault();
      isOpen = true;
      focusedIndex = 0;
    }
    return;
  }

  switch (event.key) {
    case "Escape":
      event.preventDefault();
      isOpen = false;
      break;
    case "ArrowDown":
      event.preventDefault();
      focusedIndex = (focusedIndex + 1) % nodeTypes.length;
      break;
    case "ArrowUp":
      event.preventDefault();
      focusedIndex = (focusedIndex - 1 + nodeTypes.length) % nodeTypes.length;
      break;
    case "Enter":
    case " ": {
      event.preventDefault();
      const selectedNodeType = nodeTypes[focusedIndex];
      if (selectedNodeType) {
        handleSelectNodeType(selectedNodeType);
      }
      break;
    }
    case "Home":
      event.preventDefault();
      focusedIndex = 0;
      break;
    case "End":
      event.preventDefault();
      focusedIndex = nodeTypes.length - 1;
      break;
    default:
      // Allow other keys to propagate
      break;
  }
}

function handleSelectNodeType(nodeType: VizelNodeTypeOption) {
  nodeType.command(editor);
  isOpen = false;
}

function isNodeTypeActive(nodeType: VizelNodeTypeOption): boolean {
  void editorState.current; // Trigger reactivity
  return nodeType.isActive(editor);
}
</script>

<div
  bind:this={containerRef}
  class="vizel-node-selector {className ?? ''}"
  data-vizel-node-selector
>
  <button
    type="button"
    class="vizel-node-selector-trigger"
    aria-haspopup="listbox"
    aria-expanded={isOpen}
    aria-label={`Current block type: ${currentLabel}`}
    title="Change block type"
    onclick={() => (isOpen = !isOpen)}
    onkeydown={handleKeyDown}
  >
    <span class="vizel-node-selector-icon">
      <VizelIcon name={currentIcon} />
    </span>
    <span class="vizel-node-selector-label">{currentLabel}</span>
    <span class="vizel-node-selector-chevron" aria-hidden="true">
      <VizelIcon name="chevronDown" />
    </span>
  </button>

  {#if isOpen}
    <div
      bind:this={dropdownRef}
      class="vizel-node-selector-dropdown"
      role="listbox"
      aria-label="Block types"
      data-vizel-node-selector-dropdown
      tabindex="-1"
      onkeydown={handleKeyDown}
    >
      {#each nodeTypes as nodeType, index}
        {@const active = isNodeTypeActive(nodeType)}
        {@const focused = index === focusedIndex}
        <button
          type="button"
          role="option"
          aria-selected={active}
          class="vizel-node-selector-option {active ? 'is-active' : ''} {focused ? 'is-focused' : ''}"
          tabindex={focused ? 0 : -1}
          onclick={() => handleSelectNodeType(nodeType)}
          onmouseenter={() => (focusedIndex = index)}
        >
          <span class="vizel-node-selector-option-icon">
            <VizelIcon name={nodeType.icon} />
          </span>
          <span class="vizel-node-selector-option-label">{nodeType.label}</span>
          {#if active}
            <span class="vizel-node-selector-check" aria-hidden="true">
              <VizelIcon name="check" />
            </span>
          {/if}
        </button>
      {/each}
    </div>
  {/if}
</div>

// packages/react/src/components/VizelNodeSelector.tsx
import type { Editor } from "@tiptap/core";
import {
  getVizelActiveNodeType,
  type VizelNodeTypeOption,
  vizelDefaultNodeTypes,
} from "@vizel/core";
import { useEffect, useRef, useState } from "react";
import { useVizelState } from "../hooks/useVizelState.ts";
import { VizelIcon } from "./VizelIcon.tsx";

export interface VizelNodeSelectorProps {
  /** The editor instance */
  editor: Editor;
  /** Custom node types (defaults to vizelDefaultNodeTypes) */
  nodeTypes?: VizelNodeTypeOption[];
  /** Custom class name */
  className?: string;
}

/**
 * A dropdown selector for changing block node types.
 * Displays the current node type and allows transformation to other types.
 *
 * @example
 * ```tsx
 * <VizelNodeSelector editor={editor} />
 * ```
 */
export function VizelNodeSelector({
  editor,
  nodeTypes = vizelDefaultNodeTypes,
  className,
}: VizelNodeSelectorProps) {
  // Subscribe to editor state changes
  useVizelState(editor);

  const [isOpen, setIsOpen] = useState(false);
  const [focusedIndex, setFocusedIndex] = useState(0);
  const containerRef = useRef<HTMLDivElement>(null);
  const dropdownRef = useRef<HTMLDivElement>(null);

  const activeNodeType = getVizelActiveNodeType(editor, nodeTypes);
  const currentLabel = activeNodeType?.label ?? "Text";
  const currentIcon = activeNodeType?.icon ?? "paragraph";

  // Close dropdown when clicking outside
  useEffect(() => {
    if (!isOpen) return;

    const handleClickOutside = (event: MouseEvent) => {
      if (containerRef.current && !containerRef.current.contains(event.target as Node)) {
        setIsOpen(false);
      }
    };

    document.addEventListener("mousedown", handleClickOutside);
    return () => document.removeEventListener("mousedown", handleClickOutside);
  }, [isOpen]);

  // Focus the dropdown when it opens to ensure keyboard navigation works
  useEffect(() => {
    if (isOpen && dropdownRef.current) {
      dropdownRef.current.focus();
    }
  }, [isOpen]);

  // Handle keyboard navigation
  const handleKeyDown = (event: React.KeyboardEvent) => {
    if (!isOpen) {
      if (event.key === "Enter" || event.key === " " || event.key === "ArrowDown") {
        event.preventDefault();
        setIsOpen(true);
        setFocusedIndex(0);
      }
      return;
    }

    switch (event.key) {
      case "Escape":
        event.preventDefault();
        setIsOpen(false);
        break;
      case "ArrowDown":
        event.preventDefault();
        setFocusedIndex((prev) => (prev + 1) % nodeTypes.length);
        break;
      case "ArrowUp":
        event.preventDefault();
        setFocusedIndex((prev) => (prev - 1 + nodeTypes.length) % nodeTypes.length);
        break;
      case "Enter":
      case " ": {
        event.preventDefault();
        const selectedNodeType = nodeTypes[focusedIndex];
        if (selectedNodeType) {
          handleSelectNodeType(selectedNodeType);
        }
        break;
      }
      case "Home":
        event.preventDefault();
        setFocusedIndex(0);
        break;
      case "End":
        event.preventDefault();
        setFocusedIndex(nodeTypes.length - 1);
        break;
      default:
        // Allow other keys to propagate
        break;
    }
  };

  const handleSelectNodeType = (nodeType: VizelNodeTypeOption) => {
    nodeType.command(editor);
    setIsOpen(false);
  };

  return (
    <div
      ref={containerRef}
      className={`vizel-node-selector ${className ?? ""}`}
      data-vizel-node-selector
    >
      <button
        type="button"
        className="vizel-node-selector-trigger"
        onClick={() => setIsOpen(!isOpen)}
        onKeyDown={handleKeyDown}
        aria-haspopup="listbox"
        aria-expanded={isOpen}
        aria-label={`Current block type: ${currentLabel}`}
        title="Change block type"
      >
        <span className="vizel-node-selector-icon">
          <VizelIcon name={currentIcon} />
        </span>
        <span className="vizel-node-selector-label">{currentLabel}</span>
        <span className="vizel-node-selector-chevron" aria-hidden="true">
          <VizelIcon name="chevronDown" />
        </span>
      </button>

      {isOpen && (
        <div
          ref={dropdownRef}
          className="vizel-node-selector-dropdown"
          role="listbox"
          aria-label="Block types"
          data-vizel-node-selector-dropdown
          tabIndex={-1}
          onKeyDown={handleKeyDown}
        >
          {nodeTypes.map((nodeType, index) => {
            const isActive = nodeType.isActive(editor);
            const isFocused = index === focusedIndex;

            return (
              <button
                key={nodeType.name}
                type="button"
                role="option"
                aria-selected={isActive}
                className={`vizel-node-selector-option ${isActive ? "is-active" : ""} ${isFocused ? "is-focused" : ""}`}
                onClick={() => handleSelectNodeType(nodeType)}
                onMouseEnter={() => setFocusedIndex(index)}
                tabIndex={isFocused ? 0 : -1}
              >
                <span className="vizel-node-selector-option-icon">
                  <VizelIcon name={nodeType.icon} />
                </span>
                <span className="vizel-node-selector-option-label">{nodeType.label}</span>
                {isActive && (
                  <span className="vizel-node-selector-check" aria-hidden="true">
                    <VizelIcon name="check" />
                  </span>
                )}
              </button>
            );
          })}
        </div>
      )}
    </div>
  );
}
