// packages/vue/src/components/VizelMinimap.vue
<script setup lang="ts">
import { buildVizelMinimapSpec, type Editor, renderVizelMinimapToCanvas } from "@vizel/core";
import { computed, onBeforeUnmount, onMounted, ref, watch } from "vue";
import { useVizelState } from "../composables/useVizelState.ts";

export interface VizelMinimapProps {
  /** The Tiptap editor instance, or `null` while the editor is initializing. */
  editor: Editor | null;
  /** Custom class name applied to the wrapping `<canvas>`. */
  class?: string;
  /** Canvas pixel width. Defaults to 120. */
  width?: number;
  /** Canvas pixel height. Defaults to 400. */
  height?: number;
}

const props = withDefaults(defineProps<VizelMinimapProps>(), {
  width: 120,
  height: 400,
});

const canvasRef = ref<HTMLCanvasElement | null>(null);
const rafState: { handle: number | null } = { handle: null };

// Subscribe to editor transactions so we redraw on every doc mutation.
// The returned tick value is intentionally unused.
const tick = useVizelState(() => props.editor);
const editorRef = computed(() => props.editor);

function redraw() {
  const editor = props.editor;
  if (!editor) return;
  if (rafState.handle !== null) return;
  rafState.handle = requestAnimationFrame(() => {
    rafState.handle = null;
    const canvas = canvasRef.value;
    if (!canvas) return;
    const spec = buildVizelMinimapSpec(editor);
    renderVizelMinimapToCanvas(canvas, spec);
  });
}

onMounted(() => {
  redraw();
  // Track page scroll / resize so the minimap viewport highlight
  // stays aligned when the editor sits at its natural height and the
  // page scrolls around it. `redraw` is throttled through
  // `requestAnimationFrame`, so event-heavy scrolling stays smooth.
  if (typeof window !== "undefined") {
    window.addEventListener("scroll", redraw, { passive: true });
    window.addEventListener("resize", redraw, { passive: true });
  }
});
onBeforeUnmount(() => {
  if (rafState.handle !== null) {
    cancelAnimationFrame(rafState.handle);
    rafState.handle = null;
  }
  if (typeof window !== "undefined") {
    window.removeEventListener("scroll", redraw);
    window.removeEventListener("resize", redraw);
  }
});

// Re-render when the editor instance changes or when transactions arrive.
watch([editorRef, tick], redraw);

function focusBlockAtY(clientY: number) {
  const editor = props.editor;
  if (!editor) return;
  const canvas = canvasRef.value;
  if (!canvas) return;
  const rect = canvas.getBoundingClientRect();
  const ratio = (clientY - rect.top) / Math.max(1, rect.height);
  const clamped = Math.max(0, Math.min(1, ratio));
  const spec = buildVizelMinimapSpec(editor);
  if (spec.blocks.length === 0) return;
  const index = Math.min(spec.blocks.length - 1, Math.floor(clamped * spec.blocks.length));
  const block = spec.blocks[index];
  if (!block) return;
  editor.commands.focus(block.pos);
  editor.commands.scrollIntoView();
}

function handlePointerDown(event: PointerEvent) {
  focusBlockAtY(event.clientY);
}

function handleWheel(event: WheelEvent) {
  focusBlockAtY(event.clientY + event.deltaY);
}
</script>

<template>
  <canvas
    ref="canvasRef"
    :width="props.width"
    :height="props.height"
    :class="['vizel-minimap', props.class]"
    @pointerdown="handlePointerDown"
    @wheel="handleWheel"
  />
</template>

// packages/react/src/components/VizelMinimap.tsx
import { buildVizelMinimapSpec, type Editor, renderVizelMinimapToCanvas } from "@vizel/core";
import { type PointerEvent, useCallback, useEffect, useRef, type WheelEvent } from "react";
import { useVizelState } from "../hooks/useVizelState.ts";

export interface VizelMinimapProps {
  /** The Tiptap editor instance, or `null` while the editor is initializing. */
  editor: Editor | null;
  /** Custom class name applied to the wrapping `<canvas>`. */
  className?: string;
  /** Canvas pixel width. Defaults to 120. */
  width?: number;
  /** Canvas pixel height. Defaults to 400. */
  height?: number;
}

/**
 * Canvas-based document minimap for React.
 *
 * Draws a colored-rectangle reduction of the entire document via the
 * framework-neutral `renderVizelMinimapToCanvas` helper from
 * `@vizel/core`. Clicking or wheeling on the canvas focuses the
 * corresponding block in the editor.
 */
export function VizelMinimap({ editor, className, width = 120, height = 400 }: VizelMinimapProps) {
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const rafRef = useRef<number | null>(null);

  // Subscribe to editor transactions so the canvas redraws on every doc
  // mutation. The tick value is intentionally unused — the subscription
  // alone is what we want.
  useVizelState(editor);

  // Schedule one redraw per animation frame. `redraw` is stable across
  // renders so event handlers keep their identity.
  const redraw = useCallback(() => {
    if (!editor) return;
    if (rafRef.current !== null) return;
    rafRef.current = requestAnimationFrame(() => {
      rafRef.current = null;
      const canvas = canvasRef.current;
      if (!canvas) return;
      const spec = buildVizelMinimapSpec(editor);
      renderVizelMinimapToCanvas(canvas, spec);
    });
  }, [editor]);

  useEffect(() => {
    redraw();
    // When the editor sits at its natural height inside a page that
    // scrolls (instead of an `overflow: auto` container), the visible
    // slice is computed from the editor's bounding rect. That slice
    // changes on every window scroll / resize event, so the minimap
    // must redraw to keep its viewport highlight aligned with the
    // user's actual reading position. The `redraw` callback is
    // throttled through `requestAnimationFrame`, so event-heavy
    // scrolling stays smooth.
    if (typeof window !== "undefined") {
      window.addEventListener("scroll", redraw, { passive: true });
      window.addEventListener("resize", redraw, { passive: true });
    }
    return () => {
      if (rafRef.current !== null) {
        cancelAnimationFrame(rafRef.current);
        rafRef.current = null;
      }
      if (typeof window !== "undefined") {
        window.removeEventListener("scroll", redraw);
        window.removeEventListener("resize", redraw);
      }
    };
  }, [redraw]);

  // Map a pointer Y inside the canvas to the doc-level position of the
  // nearest block, then focus it.
  const focusBlockAtY = useCallback(
    (clientY: number) => {
      if (!editor) return;
      const canvas = canvasRef.current;
      if (!canvas) return;
      const rect = canvas.getBoundingClientRect();
      const ratio = (clientY - rect.top) / Math.max(1, rect.height);
      const clamped = Math.max(0, Math.min(1, ratio));
      const spec = buildVizelMinimapSpec(editor);
      if (spec.blocks.length === 0) return;
      const index = Math.min(spec.blocks.length - 1, Math.floor(clamped * spec.blocks.length));
      const block = spec.blocks[index];
      if (!block) return;
      editor.commands.focus(block.pos);
      editor.commands.scrollIntoView();
    },
    [editor]
  );

  const handlePointerDown = useCallback(
    (event: PointerEvent<HTMLCanvasElement>) => {
      focusBlockAtY(event.clientY);
    },
    [focusBlockAtY]
  );

  const handleWheel = useCallback(
    (event: WheelEvent<HTMLCanvasElement>) => {
      focusBlockAtY(event.clientY + event.deltaY);
    },
    [focusBlockAtY]
  );

  return (
    <canvas
      ref={canvasRef}
      width={width}
      height={height}
      className={`vizel-minimap ${className || ""}`}
      onPointerDown={handlePointerDown}
      onWheel={handleWheel}
    />
  );
}
