// packages/svelte/src/components/Vizel.svelte
<script lang="ts" module>
import type {
  Editor,
  Extensions,
  JSONContent,
  VizelError,
  VizelFeatureOptions,
  VizelLocale,
  VizelMarkdownFlavor,
} from "@vizel/core";
import type { Snippet } from "svelte";

/**
 * Exposed ref type for Vizel component.
 * Use with `bind:this` and access the `editor` property.
 */
export interface VizelRef {
  /** The underlying Tiptap editor instance */
  readonly editor: Editor | null;
}

export interface VizelProps {
  /** Initial content in JSON format */
  initialContent?: JSONContent;
  /**
   * Initial content in Markdown format.
   * If both initialContent and initialMarkdown are provided, initialMarkdown takes precedence.
   * @example
   * ```svelte
   * <Vizel initialMarkdown="# Hello World\n\nThis is **bold** text." />
   * ```
   */
  initialMarkdown?: string;
  /**
   * Automatically transform diagram code blocks (mermaid, graphviz) to diagram nodes
   * when importing markdown content. Only applies when initialMarkdown is provided.
   * @default true
   */
  transformDiagramsOnImport?: boolean;
  /**
   * Two-way binding for markdown content (bind:markdown).
   * When set, markdown will be synchronized with the editor content.
   */
  markdown?: string;
  /** Placeholder text when editor is empty */
  placeholder?: string;
  /** Whether the editor is editable (default: true) */
  editable?: boolean;
  /** Auto focus on mount */
  autofocus?: boolean | "start" | "end" | "all" | number;
  /** Feature configuration */
  features?: VizelFeatureOptions;
  /**
   * Markdown output flavor.
   * Controls how Markdown is serialized when exporting content.
   * @default "gfm"
   */
  flavor?: VizelMarkdownFlavor;
  /** Locale for translated UI strings */
  locale?: VizelLocale;
  /** Additional Tiptap extensions */
  extensions?: Extensions;
  /** Custom class name for the editor container */
  class?: string;
  /** Whether to show the toolbar (default: false) */
  showToolbar?: boolean;
  /** Custom toolbar content */
  toolbar?: Snippet<[{ editor: Editor }]>;
  /** Whether to show the bubble menu (default: true) */
  showBubbleMenu?: boolean;
  /** Enable embed option in bubble menu link editor (requires Embed extension) */
  enableEmbed?: boolean;
  /** Custom bubble menu content */
  bubbleMenu?: Snippet<[{ editor: Editor }]>;
  /** Additional children to render inside the editor root */
  children?: Snippet<[{ editor: Editor | null }]>;
  /** Callback when content changes */
  onUpdate?: (props: { editor: Editor }) => void;
  /** Callback when editor is created */
  onCreate?: (props: { editor: Editor }) => void;
  /** Callback when editor is destroyed */
  onDestroy?: () => void;
  /** Callback when selection changes */
  onSelectionUpdate?: (props: { editor: Editor }) => void;
  /** Callback when editor gets focus */
  onFocus?: (props: { editor: Editor }) => void;
  /** Callback when editor loses focus */
  onBlur?: (props: { editor: Editor }) => void;
  /**
   * Callback when an error occurs during editor operations.
   * Provides structured error information for logging or user feedback.
   */
  onError?: (error: VizelError) => void;
}
</script>

<script lang="ts">
// Vizel - All-in-one editor component
// A complete editor component that includes EditorContent and BubbleMenu.
// This is the recommended way to use Vizel for most use cases.
import { getVizelMarkdown, setVizelMarkdown } from "@vizel/core";
import { createVizelEditor } from "../runes/createVizelEditor.svelte.js";
import VizelBlockMenu from "./VizelBlockMenu.svelte";
import VizelBubbleMenu from "./VizelBubbleMenu.svelte";
import VizelEditor from "./VizelEditor.svelte";
import VizelToolbar from "./VizelToolbar.svelte";

// Use $props() without destructuring to avoid state_referenced_locally warnings
// Props are intentionally captured once at editor creation time
let {
  class: className,
  showToolbar = false,
  toolbar,
  showBubbleMenu = true,
  enableEmbed = false,
  bubbleMenu,
  children,
  markdown = $bindable(),
  transformDiagramsOnImport = true,
  ...restProps
}: VizelProps = $props();

// Track whether we're currently updating from external markdown change
let isUpdatingFromMarkdown = false;

// Wrap onUpdate to sync markdown
const originalOnUpdate = restProps.onUpdate;
const wrappedOnUpdate = (e: { editor: import("@vizel/core").Editor }) => {
  originalOnUpdate?.(e);
  // Update markdown binding if not updating from external change
  if (!isUpdatingFromMarkdown && markdown !== undefined) {
    markdown = getVizelMarkdown(e.editor);
  }
};

// Capture initial values for editor creation (these are intentionally not reactive)
// The editor is created once and should not be recreated when props change
// svelte-ignore state_referenced_locally
const initialTransformDiagrams = transformDiagramsOnImport;

// Create editor with initial props - editor is intentionally created once
const editorState = createVizelEditor({
  ...(restProps.initialContent !== undefined && { initialContent: restProps.initialContent }),
  ...(restProps.initialMarkdown !== undefined && { initialMarkdown: restProps.initialMarkdown }),
  transformDiagramsOnImport: initialTransformDiagrams,
  ...(restProps.placeholder !== undefined && { placeholder: restProps.placeholder }),
  editable: restProps.editable ?? true,
  autofocus: restProps.autofocus ?? false,
  ...(restProps.features !== undefined && { features: restProps.features }),
  ...(restProps.flavor !== undefined && { flavor: restProps.flavor }),
  ...(restProps.locale !== undefined && { locale: restProps.locale }),
  ...(restProps.extensions !== undefined && { extensions: restProps.extensions }),
  onUpdate: wrappedOnUpdate,
  ...(restProps.onCreate !== undefined && { onCreate: restProps.onCreate }),
  ...(restProps.onDestroy !== undefined && { onDestroy: restProps.onDestroy }),
  ...(restProps.onSelectionUpdate !== undefined && { onSelectionUpdate: restProps.onSelectionUpdate }),
  ...(restProps.onFocus !== undefined && { onFocus: restProps.onFocus }),
  ...(restProps.onBlur !== undefined && { onBlur: restProps.onBlur }),
  ...(restProps.onError !== undefined && { onError: restProps.onError }),
});

const editor = $derived(editorState.current);

// Watch for external markdown changes (bind:markdown)
$effect(() => {
  if (markdown === undefined || !editor) return;

  // Get current editor markdown
  const currentMarkdown = getVizelMarkdown(editor);
  if (markdown === currentMarkdown) return;

  // Set flag to prevent emitting update during this update
  isUpdatingFromMarkdown = true;
  setVizelMarkdown(editor, markdown, {
    transformDiagrams: transformDiagramsOnImport,
  });
  isUpdatingFromMarkdown = false;
});
</script>

<div class="vizel-root {className ?? ''}" data-vizel-root>
  {#if showToolbar && editor && toolbar}
    <VizelToolbar {editor}>
      {#snippet children({ editor: e })}
        {@render toolbar({ editor: e })}
      {/snippet}
    </VizelToolbar>
  {:else if showToolbar && editor}
    <VizelToolbar {editor} />
  {/if}
  <VizelEditor {editor} />
  {#if showBubbleMenu && editor && bubbleMenu}
    <VizelBubbleMenu {editor} {enableEmbed}>
      {@render bubbleMenu({ editor })}
    </VizelBubbleMenu>
  {:else if showBubbleMenu && editor}
    <VizelBubbleMenu {editor} {enableEmbed} />
  {/if}
  {#if restProps.locale}
    <VizelBlockMenu locale={restProps.locale} />
  {:else}
    <VizelBlockMenu />
  {/if}
  {#if children}
    {@render children({ editor })}
  {/if}
</div>

// packages/react/src/components/Vizel.tsx
import {
  type Editor,
  type Extensions,
  getVizelMarkdown,
  type JSONContent,
  setVizelMarkdown,
  type VizelError,
  type VizelFeatureOptions,
  type VizelLocale,
  type VizelMarkdownFlavor,
} from "@vizel/core";
import type { ReactNode, Ref } from "react";
import { useEffect, useImperativeHandle, useRef } from "react";
import { useVizelEditor } from "../hooks/useVizelEditor.ts";
import { VizelBlockMenu } from "./VizelBlockMenu.tsx";
import { VizelBubbleMenu } from "./VizelBubbleMenu.tsx";
import { VizelEditor } from "./VizelEditor.tsx";
import { VizelToolbar } from "./VizelToolbar.tsx";

export interface VizelProps {
  /** Ref to access editor instance */
  ref?: Ref<VizelRef>;
  /** Initial content in JSON format */
  initialContent?: JSONContent;
  /**
   * Initial content in Markdown format.
   * If both initialContent and initialMarkdown are provided, initialMarkdown takes precedence.
   * @example
   * ```tsx
   * <Vizel initialMarkdown="# Hello World\n\nThis is **bold** text." />
   * ```
   */
  initialMarkdown?: string;
  /**
   * Automatically transform diagram code blocks (mermaid, graphviz) to diagram nodes
   * when importing markdown content. Only applies when initialMarkdown is provided.
   * @default true
   */
  transformDiagramsOnImport?: boolean;
  /** Placeholder text when editor is empty */
  placeholder?: string;
  /** Whether the editor is editable (default: true) */
  editable?: boolean;
  /** Auto focus on mount */
  autofocus?: boolean | "start" | "end" | "all" | number;
  /** Feature configuration */
  features?: VizelFeatureOptions;
  /**
   * Markdown output flavor.
   * Controls how Markdown is serialized when exporting content.
   * @default "gfm"
   */
  flavor?: VizelMarkdownFlavor;
  /** Locale for translated UI strings */
  locale?: VizelLocale;
  /** Additional Tiptap extensions */
  extensions?: Extensions;
  /** Custom class name for the editor container */
  className?: string;
  /** Whether to show the toolbar (default: false) */
  showToolbar?: boolean;
  /** Custom toolbar content */
  toolbarContent?: ReactNode;
  /** Whether to show the bubble menu (default: true) */
  showBubbleMenu?: boolean;
  /** Enable embed option in bubble menu link editor (requires Embed extension) */
  enableEmbed?: boolean;
  /** Custom bubble menu content */
  bubbleMenuContent?: ReactNode;
  /** Additional children to render inside the editor root */
  children?: ReactNode;
  /**
   * Controlled markdown content.
   * When set, the editor content will be synchronized with this value.
   * Use together with `onMarkdownChange` for controlled mode.
   * @example
   * ```tsx
   * const [md, setMd] = useState("# Hello");
   * <Vizel markdown={md} onMarkdownChange={setMd} />
   * ```
   */
  markdown?: string;
  /**
   * Callback when markdown content changes.
   * Called with the current markdown string when the editor content is updated.
   * Use together with `markdown` for controlled mode.
   */
  onMarkdownChange?: (markdown: string) => void;
  /** Callback when content changes */
  onUpdate?: (props: { editor: Editor }) => void;
  /** Callback when editor is created */
  onCreate?: (props: { editor: Editor }) => void;
  /** Callback when editor is destroyed */
  onDestroy?: () => void;
  /** Callback when selection changes */
  onSelectionUpdate?: (props: { editor: Editor }) => void;
  /** Callback when editor gets focus */
  onFocus?: (props: { editor: Editor }) => void;
  /** Callback when editor loses focus */
  onBlur?: (props: { editor: Editor }) => void;
  /**
   * Callback when an error occurs during editor operations.
   * Provides structured error information for logging or user feedback.
   */
  onError?: (error: VizelError) => void;
}

export interface VizelRef {
  /** The underlying Tiptap editor instance */
  editor: Editor | null;
}

/**
 * Vizel - All-in-one editor component
 *
 * A complete editor component that includes VizelEditor and VizelBubbleMenu.
 * This is the recommended way to use Vizel for most use cases.
 *
 * @example
 * ```tsx
 * import { Vizel } from '@vizel/react';
 *
 * function App() {
 *   return <Vizel placeholder="Type '/' for commands..." />;
 * }
 * ```
 *
 * @example
 * ```tsx
 * import { Vizel, type VizelRef } from '@vizel/react';
 * import { useRef } from 'react';
 *
 * function App() {
 *   const vizelRef = useRef<VizelRef>(null);
 *
 *   const handleSave = () => {
 *     const content = vizelRef.current?.editor?.getJSON();
 *     console.log(content);
 *   };
 *
 *   return (
 *     <>
 *       <Vizel ref={vizelRef} onUpdate={({ editor }) => console.log(editor.getJSON())} />
 *       <button onClick={handleSave}>Save</button>
 *     </>
 *   );
 * }
 * ```
 */
export function Vizel({
  ref,
  initialContent,
  initialMarkdown,
  transformDiagramsOnImport = true,
  placeholder,
  editable = true,
  autofocus = false,
  features,
  flavor,
  locale,
  extensions,
  className,
  showToolbar = false,
  toolbarContent,
  showBubbleMenu = true,
  enableEmbed = false,
  bubbleMenuContent,
  children,
  markdown,
  onMarkdownChange,
  onUpdate,
  onCreate,
  onDestroy,
  onSelectionUpdate,
  onFocus,
  onBlur,
  onError,
}: VizelProps): ReactNode {
  // Track whether we're currently updating from external markdown change
  const isUpdatingFromMarkdownRef = useRef(false);

  // Keep refs for values accessed in the onUpdate closure to avoid stale captures.
  // useVizelEditor only reads options once at mount time, so the onUpdate callback
  // would otherwise permanently capture the initial markdown/onMarkdownChange values.
  const markdownRef = useRef(markdown);
  markdownRef.current = markdown;
  const onMarkdownChangeRef = useRef(onMarkdownChange);
  onMarkdownChangeRef.current = onMarkdownChange;
  const onUpdateRef = useRef(onUpdate);
  onUpdateRef.current = onUpdate;

  const editor = useVizelEditor({
    ...(initialContent !== undefined && { initialContent }),
    ...(initialMarkdown !== undefined && { initialMarkdown }),
    transformDiagramsOnImport,
    ...(placeholder !== undefined && { placeholder }),
    editable,
    autofocus,
    ...(features !== undefined && { features }),
    ...(flavor !== undefined && { flavor }),
    ...(locale !== undefined && { locale }),
    ...(extensions !== undefined && { extensions }),
    onUpdate: (e) => {
      onUpdateRef.current?.(e);
      // Update markdown if not updating from external change
      if (!isUpdatingFromMarkdownRef.current && markdownRef.current !== undefined) {
        onMarkdownChangeRef.current?.(getVizelMarkdown(e.editor));
      }
    },
    ...(onCreate !== undefined && { onCreate }),
    ...(onDestroy !== undefined && { onDestroy }),
    ...(onSelectionUpdate !== undefined && { onSelectionUpdate }),
    ...(onFocus !== undefined && { onFocus }),
    ...(onBlur !== undefined && { onBlur }),
    ...(onError !== undefined && { onError }),
  });

  // Watch for external markdown changes (controlled mode)
  useEffect(() => {
    if (markdown === undefined || !editor) return;

    // Get current editor markdown
    const currentMarkdown = getVizelMarkdown(editor);
    if (markdown === currentMarkdown) return;

    // Set flag to prevent emitting onMarkdownChange during this update
    isUpdatingFromMarkdownRef.current = true;
    setVizelMarkdown(editor, markdown, {
      transformDiagrams: transformDiagramsOnImport,
    });
    isUpdatingFromMarkdownRef.current = false;
  }, [markdown, editor, transformDiagramsOnImport]);

  // Expose editor instance via ref
  useImperativeHandle(
    ref,
    () => ({
      editor,
    }),
    [editor]
  );

  const localeProps = locale !== undefined ? { locale } : {};

  return (
    <div className={`vizel-root ${className ?? ""}`} data-vizel-root="">
      {showToolbar &&
        editor &&
        (toolbarContent ? (
          <VizelToolbar editor={editor} {...localeProps}>
            {toolbarContent}
          </VizelToolbar>
        ) : (
          <VizelToolbar editor={editor} {...localeProps} />
        ))}
      <VizelEditor editor={editor} />
      {showBubbleMenu &&
        editor &&
        (bubbleMenuContent ? (
          <VizelBubbleMenu editor={editor} enableEmbed={enableEmbed}>
            {bubbleMenuContent}
          </VizelBubbleMenu>
        ) : (
          <VizelBubbleMenu editor={editor} enableEmbed={enableEmbed} />
        ))}
      <VizelBlockMenu {...localeProps} />
      {children}
    </div>
  );
}
