// packages/svelte/src/components/VizelProvider.svelte
<script lang="ts" module>
import type { Editor } from "@tiptap/core";
import type { Snippet } from "svelte";

export interface VizelProviderProps {
  /** The editor instance */
  editor: Editor | null;
  /** Custom class name */
  class?: string;
  /** Children content */
  children: Snippet;
}
</script>

<script lang="ts">
import { setContext } from "svelte";
import { VIZEL_CONTEXT_KEY } from "./VizelContext.ts";

let { editor, class: className, children }: VizelProviderProps = $props();

setContext(VIZEL_CONTEXT_KEY, () => editor);
</script>

<div class={className} data-vizel-root>
  {@render children()}
</div>

// packages/react/src/components/VizelProvider.tsx
import type { Editor } from "@tiptap/core";
import type { ReactNode } from "react";
import { VizelInternalProvider } from "./VizelContext.tsx";

export interface VizelProviderProps {
  /** The editor instance from useVizelEditor */
  editor: Editor | null;
  /** Child components (VizelEditor, VizelToolbar, etc.) */
  children: ReactNode;
  /** Optional className for the root container */
  className?: string;
}

/**
 * Provider component for the Vizel editor.
 * Provides editor context to all child components.
 *
 * @example
 * ```tsx
 * const editor = useVizelEditor();
 *
 * return (
 *   <VizelProvider editor={editor}>
 *     <VizelEditor />
 *     <VizelToolbar />
 *   </VizelProvider>
 * );
 * ```
 */
export function VizelProvider({ editor, children, className }: VizelProviderProps) {
  return (
    <VizelInternalProvider editor={editor}>
      <div className={className} data-vizel-root="">
        {children}
      </div>
    </VizelInternalProvider>
  );
}
