// packages/vue/src/components/VizelEmbedView.vue
<script setup lang="ts">
import type { VizelEmbedData, VizelEmbedType } from "@vizel/core";
import { computed, onMounted, ref, watch } from "vue";
import VizelIcon from "./VizelIcon.vue";

export interface VizelEmbedViewProps {
  /** Embed data */
  data: VizelEmbedData & { loading?: boolean };
  /** Additional class name */
  class?: string;
  /** Whether the embed is selected */
  selected?: boolean;
}

const props = defineProps<VizelEmbedViewProps>();

const containerRef = ref<HTMLDivElement | null>(null);

const baseClass = computed(() => {
  const classes = ["vizel-embed"];
  if (props.data.loading) classes.push("is-loading");
  if (props.selected) classes.push("ProseMirror-selectednode");
  if (props.class) classes.push(props.class);
  return classes.join(" ");
});

const isVideo = computed(() => {
  return ["youtube", "vimeo", "loom", "tiktok"].includes(props.data.provider ?? "");
});

const hasImage = computed(() => Boolean(props.data.image));

const hostname = computed(() => {
  try {
    return new URL(props.data.url).hostname;
  } catch {
    return props.data.url;
  }
});

// Handle oEmbed scripts (Twitter, Instagram, etc.)
function loadScripts() {
  if (props.data.type === "oembed" && props.data.html && containerRef.value) {
    const scripts = containerRef.value.querySelectorAll("script");
    for (const script of scripts) {
      const newScript = document.createElement("script");
      if (script.src) {
        newScript.src = script.src;
      } else {
        newScript.textContent = script.textContent;
      }
      script.parentNode?.replaceChild(newScript, script);
    }

    // Load Twitter widgets if present
    if (props.data.provider === "twitter" && "twttr" in window) {
      (window as { twttr?: { widgets?: { load?: () => void } } }).twttr?.widgets?.load?.();
    }
  }
}

onMounted(loadScripts);
watch(() => [props.data.type, props.data.html], loadScripts);
</script>

<template>
  <!-- Loading state -->
  <div
    v-if="data.loading"
    :class="baseClass"
    data-embed-type="loading"
    :data-embed-provider="data.provider"
  >
    <div class="vizel-embed-loading">
      <div class="vizel-embed-loading-spinner" />
      <span>Loading embed...</span>
    </div>
  </div>

  <!-- oEmbed (rich embed) -->
  <div
    v-else-if="data.type === 'oembed' && data.html"
    ref="containerRef"
    :class="baseClass"
    data-embed-type="oembed"
    :data-embed-provider="data.provider"
  >
    <div
      :class="isVideo ? 'vizel-embed-video' : 'vizel-embed-oembed'"
      v-html="data.html"
    />
  </div>

  <!-- OGP card -->
  <div
    v-else-if="data.type === 'ogp'"
    :class="baseClass"
    data-embed-type="ogp"
    :data-embed-provider="data.provider"
  >
    <a
      :href="data.url"
      target="_blank"
      rel="noopener noreferrer"
      :class="['vizel-embed-card', hasImage ? 'vizel-embed-card-horizontal' : '']"
    >
      <img
        v-if="hasImage"
        :src="data.image"
        alt=""
        class="vizel-embed-card-image"
        loading="lazy"
      />
      <div class="vizel-embed-card-content">
        <div v-if="data.siteName || data.favicon" class="vizel-embed-card-site">
          <img
            v-if="data.favicon"
            :src="data.favicon"
            alt=""
            class="vizel-embed-card-favicon"
          />
          <span v-if="data.siteName">{{ data.siteName }}</span>
        </div>
        <div v-if="data.title" class="vizel-embed-card-title">{{ data.title }}</div>
        <div v-if="data.description" class="vizel-embed-card-description">{{ data.description }}</div>
        <div class="vizel-embed-card-url">{{ hostname }}</div>
      </div>
    </a>
  </div>

  <!-- Title link -->
  <div
    v-else-if="data.type === 'title' && data.title"
    :class="baseClass"
    data-embed-type="title"
    :data-embed-provider="data.provider"
  >
    <a :href="data.url" target="_blank" rel="noopener noreferrer" class="vizel-embed-link">
      <span class="vizel-embed-link-icon"><VizelIcon name="link" /></span>
      <span class="vizel-embed-link-text">{{ data.title }}</span>
    </a>
  </div>

  <!-- Plain link (fallback) -->
  <div
    v-else
    :class="baseClass"
    data-embed-type="link"
    :data-embed-provider="data.provider"
  >
    <a :href="data.url" target="_blank" rel="noopener noreferrer" class="vizel-embed-link">
      <span class="vizel-embed-link-icon"><VizelIcon name="link" /></span>
      <span class="vizel-embed-link-text">{{ data.url }}</span>
    </a>
  </div>
</template>

// packages/react/src/components/VizelEmbedView.tsx
import type { VizelEmbedData, VizelEmbedType } from "@vizel/core";
import type React from "react";
import { useEffect, useRef } from "react";
import { VizelIcon } from "./VizelIcon.tsx";

export interface VizelEmbedViewProps {
  /** Embed data */
  data: VizelEmbedData;
  /** Additional class name */
  className?: string;
  /** Whether the embed is selected */
  selected?: boolean;
}

/** Build base class name for embed container */
function buildBaseClass(
  loading: boolean | undefined,
  selected: boolean | undefined,
  className: string | undefined
): string {
  return `vizel-embed ${loading ? "is-loading" : ""} ${selected ? "ProseMirror-selectednode" : ""} ${className ?? ""}`;
}

/** Render loading state */
function renderLoading(baseClass: string, provider: string | undefined): React.JSX.Element {
  return (
    <div className={baseClass} data-embed-type="loading" data-embed-provider={provider}>
      <div className="vizel-embed-loading">
        <div className="vizel-embed-loading-spinner" />
        <span>Loading embed...</span>
      </div>
    </div>
  );
}

/** Render oEmbed (rich embed) */
function renderOEmbed(
  baseClass: string,
  data: VizelEmbedData,
  containerRef: React.RefObject<HTMLDivElement | null>
): React.JSX.Element {
  const isVideo = ["youtube", "vimeo", "loom", "tiktok"].includes(data.provider ?? "");

  return (
    <div
      ref={containerRef}
      className={baseClass}
      data-embed-type="oembed"
      data-embed-provider={data.provider}
    >
      <div
        className={isVideo ? "vizel-embed-video" : "vizel-embed-oembed"}
        // biome-ignore lint/security/noDangerouslySetInnerHtml lint/style/useNamingConvention: oEmbed requires rendering provider HTML; __html is React API
        dangerouslySetInnerHTML={{ __html: data.html ?? "" }}
      />
    </div>
  );
}

/** Render OGP card */
function renderOGPCard(baseClass: string, data: VizelEmbedData): React.JSX.Element {
  const hasImage = Boolean(data.image);
  const cardLayout = hasImage ? "vizel-embed-card-horizontal" : "";

  return (
    <div className={baseClass} data-embed-type="ogp" data-embed-provider={data.provider}>
      <a
        href={data.url}
        target="_blank"
        rel="noopener noreferrer"
        className={`vizel-embed-card ${cardLayout}`}
      >
        {hasImage && (
          <img src={data.image} alt="" className="vizel-embed-card-image" loading="lazy" />
        )}
        <div className="vizel-embed-card-content">
          {(data.siteName || data.favicon) && (
            <div className="vizel-embed-card-site">
              {data.favicon && (
                <img src={data.favicon} alt="" className="vizel-embed-card-favicon" />
              )}
              {data.siteName && <span>{data.siteName}</span>}
            </div>
          )}
          {data.title && <div className="vizel-embed-card-title">{data.title}</div>}
          {data.description && (
            <div className="vizel-embed-card-description">{data.description}</div>
          )}
          <div className="vizel-embed-card-url">{new URL(data.url).hostname}</div>
        </div>
      </a>
    </div>
  );
}

/** Render title link */
function renderTitleLink(
  baseClass: string,
  data: VizelEmbedData,
  LinkIcon: React.JSX.Element
): React.JSX.Element {
  return (
    <div className={baseClass} data-embed-type="title" data-embed-provider={data.provider}>
      <a href={data.url} target="_blank" rel="noopener noreferrer" className="vizel-embed-link">
        <span className="vizel-embed-link-icon">{LinkIcon}</span>
        <span className="vizel-embed-link-text">{data.title}</span>
      </a>
    </div>
  );
}

/** Render plain link (fallback) */
function renderPlainLink(
  baseClass: string,
  data: VizelEmbedData,
  LinkIcon: React.JSX.Element
): React.JSX.Element {
  return (
    <div className={baseClass} data-embed-type="link" data-embed-provider={data.provider}>
      <a href={data.url} target="_blank" rel="noopener noreferrer" className="vizel-embed-link">
        <span className="vizel-embed-link-icon">{LinkIcon}</span>
        <span className="vizel-embed-link-text">{data.url}</span>
      </a>
    </div>
  );
}

/**
 * Renders an embed based on its type.
 * Supports oEmbed (rich), OGP (card), title (link with text), and plain link.
 */
export function VizelEmbedView({ data, className, selected }: VizelEmbedViewProps) {
  const containerRef = useRef<HTMLDivElement>(null);

  // Handle oEmbed scripts (Twitter, Instagram, etc.)
  useEffect(() => {
    if (data.type === "oembed" && data.html && containerRef.current) {
      // Find and execute any scripts in the HTML
      const scripts = containerRef.current.querySelectorAll("script");
      for (const script of scripts) {
        const newScript = document.createElement("script");
        if (script.src) {
          newScript.src = script.src;
        } else {
          newScript.textContent = script.textContent;
        }
        script.parentNode?.replaceChild(newScript, script);
      }

      // Load Twitter widgets if present
      if (data.provider === "twitter" && "twttr" in window) {
        (window as { twttr?: { widgets?: { load?: () => void } } }).twttr?.widgets?.load?.();
      }
    }
  }, [data.type, data.html, data.provider]);

  const baseClass = buildBaseClass(data.loading, selected, className);

  // Loading state
  if (data.loading) {
    return renderLoading(baseClass, data.provider);
  }

  // oEmbed (rich embed)
  if (data.type === "oembed" && data.html) {
    return renderOEmbed(baseClass, data, containerRef);
  }

  // OGP card
  if (data.type === "ogp") {
    return renderOGPCard(baseClass, data);
  }

  const linkIcon = <VizelIcon name="link" />;

  // Title link
  if (data.type === "title" && data.title) {
    return renderTitleLink(baseClass, data, linkIcon);
  }

  // Plain link (fallback)
  return renderPlainLink(baseClass, data, linkIcon);
}

/**
 * Create a mock EmbedData for testing/demo purposes
 */
export function createMockEmbedData(url: string, type: VizelEmbedType = "link"): VizelEmbedData {
  return {
    url,
    type,
  };
}
