// packages/svelte/src/components/VizelBubbleMenuButton.svelte
<script lang="ts" module>
import type { Snippet } from "svelte";

export interface VizelBubbleMenuButtonProps {
  /** Whether the button is in active state */
  isActive?: boolean;
  /** Whether the button is disabled */
  disabled?: boolean;
  /** Tooltip title */
  title?: string;
  /** Custom class name */
  class?: string;
  /** Button content */
  children: Snippet;
  /** Click handler */
  onclick?: () => void;
  /** Action identifier for testing */
  action?: string;
}
</script>

<script lang="ts">
let {
  isActive = false,
  disabled = false,
  title,
  class: className,
  children,
  onclick,
  action,
}: VizelBubbleMenuButtonProps = $props();
</script>

<button
  type="button"
  {disabled}
  aria-pressed={isActive}
  class="vizel-bubble-menu-button {isActive ? 'is-active' : ''} {className ?? ''}"
  {title}
  data-active={isActive || undefined}
  data-action={action}
  {onclick}
>
  {@render children()}
</button>

// packages/react/src/components/VizelBubbleMenuButton.tsx
import type { ReactNode } from "react";

export interface VizelBubbleMenuButtonProps {
  /** Click handler. Optional when disabled is true. */
  onClick?: () => void;
  isActive?: boolean;
  disabled?: boolean;
  children: ReactNode;
  title?: string;
  className?: string;
  /** Action identifier for testing */
  action?: string;
}

/**
 * A button component for use in the VizelBubbleMenu.
 *
 * @example
 * ```tsx
 * <VizelBubbleMenuButton
 *   onClick={() => editor.chain().focus().toggleBold().run()}
 *   isActive={editor.isActive("bold")}
 *   title="Bold (Cmd+B)"
 * >
 *   <strong>B</strong>
 * </VizelBubbleMenuButton>
 * ```
 */
export function VizelBubbleMenuButton({
  onClick,
  isActive = false,
  disabled = false,
  children,
  title,
  className,
  action,
}: VizelBubbleMenuButtonProps) {
  return (
    <button
      type="button"
      onClick={onClick}
      disabled={disabled}
      aria-pressed={isActive}
      className={`vizel-bubble-menu-button ${isActive ? "is-active" : ""} ${className ?? ""}`}
      title={title}
      data-active={isActive || undefined}
      data-action={action}
    >
      {children}
    </button>
  );
}
