// packages/svelte/src/components/VizelEditor.svelte
<script lang="ts" module>
import type { Editor } from "@vizel/core";

export interface VizelEditorRef {
  /** The container DOM element */
  container: HTMLDivElement | null;
  /**
   * The Tiptap editor instance that this component is rendering.
   *
   * Mirrors whichever editor was resolved (explicit prop or context).
   * Lets callers skip the extra round-trip through `getVizelContext` or
   * lifting state when they only need imperative access to the editor.
   */
  editor: Editor | null;
}

export interface VizelEditorProps {
  /** Editor instance. Falls back to the editor from `VizelProvider` / `Vizel` context if omitted. */
  editor?: Editor | null;
  /** Custom class name */
  class?: string;
  /**
   * Mutable ref object the component keeps in sync with the editor container.
   * Pass an object; this component assigns `container` so callers can read
   * `ref.container` directly — symmetric with React's `useImperativeHandle`
   * and Vue's `defineExpose`.
   */
  ref?: VizelEditorRef;
}
</script>

<script lang="ts">
import { mountVizelEditorView } from "@vizel/core";
import { getVizelContextSafe } from "./VizelContext.js";

let { editor: editorProp, class: className, ref }: VizelEditorProps = $props();

const contextEditor = getVizelContextSafe();
const editor = $derived(editorProp ?? contextEditor?.current);

let element: HTMLDivElement | null = $state(null);

// Keep ref.container and ref.editor in sync with the live values.
$effect(() => {
  if (ref) {
    ref.container = element;
    ref.editor = editor ?? null;
  }
});

$effect(() => {
  if (!editor || !element) return;
  return mountVizelEditorView(editor, element);
});
</script>

{#if editor}
  <div bind:this={element} class={className} data-vizel-content></div>
{/if}

// packages/react/src/components/VizelEditor.tsx
import { type Editor, mountVizelEditorView } from "@vizel/core";
import type { ReactNode, Ref } from "react";
import { useEffect, useImperativeHandle, useRef } from "react";
import { useVizelContextSafe } from "./VizelContext.tsx";

export interface VizelEditorProps {
  /** Ref to access editor container */
  ref?: Ref<VizelEditorRef>;
  /** Editor instance. Falls back to the editor from `VizelProvider` / `Vizel` context if omitted. */
  editor?: Editor | null;
  /** Optional className for the editor container */
  className?: string;
}

export interface VizelEditorRef {
  /** The container DOM element */
  container: HTMLDivElement | null;
  /**
   * The Tiptap editor instance that this component is rendering.
   *
   * Mirrors whichever editor was resolved (explicit prop or context).
   * Lets callers skip the extra round-trip through `useVizelContext` or
   * lifting state when they only need imperative access to the editor.
   */
  editor: Editor | null;
}

/**
 * Renders the editable content area of the Vizel editor.
 *
 * Can be used within an VizelProvider (no editor prop needed), or standalone with editor prop.
 *
 * @example
 * ```tsx
 * // With VizelProvider
 * <VizelProvider editor={editor}>
 *   <VizelEditor className="prose" />
 * </VizelProvider>
 *
 * // Or directly with editor prop
 * <VizelEditor editor={editor} className="prose" />
 *
 * // With ref to access container DOM
 * const editorRef = useRef<VizelEditorRef>(null);
 * <VizelEditor ref={editorRef} editor={editor} />
 * // editorRef.current?.container gives you the container element
 * ```
 */
export function VizelEditor({ ref, editor: editorProp, className }: VizelEditorProps): ReactNode {
  const contextEditor = useVizelContextSafe();
  const editor = editorProp ?? contextEditor;
  const containerRef = useRef<HTMLDivElement>(null);

  // Expose container ref and editor instance via imperative handle. The
  // editor moves into the dependency list so consumers that read
  // `ref.current?.editor` after the editor resolves see the live value
  // instead of the `null` snapshot captured at first mount.
  useImperativeHandle(
    ref,
    () => ({
      container: containerRef.current,
      editor: editor ?? null,
    }),
    [editor]
  );

  useEffect(() => {
    const container = containerRef.current;
    if (!(editor && container)) return;
    return mountVizelEditorView(editor, container);
  }, [editor]);

  if (!editor) {
    return null;
  }

  return <div ref={containerRef} className={className} data-vizel-content="" />;
}
