// packages/svelte/src/components/Portal.svelte
<script lang="ts" module>
import type { PortalLayer } from "@vizel/core";
import type { Snippet } from "svelte";

/**
 * Props for the Portal component.
 */
export interface PortalProps {
  /** Content to render in the portal */
  children: Snippet;
  /** Z-index layer for the portal content */
  layer?: PortalLayer;
  /** Additional CSS class name */
  class?: string;
  /** Whether the portal is disabled (renders children in place) */
  disabled?: boolean;
}
</script>

<script lang="ts">
  import { getPortalContainer, PORTAL_Z_INDEX } from "@vizel/core";

  const {
    children,
    layer = "dropdown",
    class: className,
    disabled = false,
  }: PortalProps = $props();

  // Create portal action that moves content to the portal container
  function portal(node: HTMLElement) {
    const container = getPortalContainer();

    // Create wrapper element
    const wrapper = document.createElement("div");
    wrapper.setAttribute("data-vizel-portal-layer", layer);
    if (className) {
      wrapper.className = className;
    }
    wrapper.style.position = "absolute";
    wrapper.style.top = "0";
    wrapper.style.left = "0";
    wrapper.style.zIndex = String(PORTAL_Z_INDEX[layer]);

    // Move node's children to wrapper
    while (node.firstChild) {
      wrapper.appendChild(node.firstChild);
    }

    container.appendChild(wrapper);

    return {
      destroy() {
        // Move content back to original location for cleanup
        while (wrapper.firstChild) {
          node.appendChild(wrapper.firstChild);
        }
        wrapper.remove();
      },
    };
  }
</script>

{#if disabled}
  {@render children()}
{:else}
  <div use:portal>
    {@render children()}
  </div>
{/if}

// packages/vue/src/components/Portal.vue
<script setup lang="ts">
import { getPortalContainer, PORTAL_Z_INDEX, type PortalLayer, VIZEL_PORTAL_ID } from "@vizel/core";
import { computed, onMounted, ref, Teleport } from "vue";

/**
 * Props for the Portal component.
 */
export interface PortalProps {
  /** Z-index layer for the portal content */
  layer?: PortalLayer;
  /** Additional CSS class name */
  class?: string;
  /** Whether the portal is disabled (renders children in place) */
  disabled?: boolean;
}

const props = withDefaults(defineProps<PortalProps>(), {
  layer: "dropdown",
  disabled: false,
});

const mounted = ref(false);

onMounted(() => {
  // Ensure portal container exists
  getPortalContainer();
  mounted.value = true;
});

const portalTarget = computed(() => `#${VIZEL_PORTAL_ID}`);

const wrapperStyle = computed(() => ({
  position: "absolute" as const,
  top: 0,
  left: 0,
  zIndex: PORTAL_Z_INDEX[props.layer],
}));
</script>

<template>
  <Teleport v-if="mounted && !disabled" :to="portalTarget">
    <div
      :data-vizel-portal-layer="layer"
      :class="props.class"
      :style="wrapperStyle"
    >
      <slot />
    </div>
  </Teleport>
  <slot v-else />
</template>
