// packages/react/src/components/VizelThemeProvider.tsx
import {
  applyVizelTheme,
  createVizelSystemThemeListener,
  getStoredVizelTheme,
  getVizelSystemTheme,
  resolveVizelTheme,
  storeVizelTheme,
  VIZEL_DEFAULT_THEME,
  VIZEL_DEFAULT_THEME_STORAGE_KEY,
  type VizelResolvedTheme,
  type VizelTheme,
  type VizelThemeProviderOptions,
  type VizelThemeState,
} from "@vizel/core";
import { type ReactNode, useCallback, useEffect, useMemo, useState } from "react";
import { VizelThemeContext } from "./VizelThemeContext.tsx";

export interface VizelThemeProviderProps extends VizelThemeProviderOptions {
  /** Children to render */
  children: ReactNode;
}

/**
 * Theme provider component for managing dark mode
 *
 * @example
 * ```tsx
 * <VizelThemeProvider defaultTheme="system">
 *   <App />
 * </VizelThemeProvider>
 * ```
 */
export function VizelThemeProvider({
  children,
  defaultTheme = VIZEL_DEFAULT_THEME,
  storageKey = VIZEL_DEFAULT_THEME_STORAGE_KEY,
  targetSelector,
  disableTransitionOnChange = false,
}: VizelThemeProviderProps) {
  const [theme, setThemeState] = useState<VizelTheme>(() => {
    // Check stored theme first
    const stored = getStoredVizelTheme(storageKey);
    if (stored) {
      return stored;
    }
    return defaultTheme;
  });

  const [systemTheme, setSystemTheme] = useState<VizelResolvedTheme>(() => getVizelSystemTheme());

  const resolvedTheme = useMemo(() => resolveVizelTheme(theme, systemTheme), [theme, systemTheme]);

  // Apply theme to DOM
  useEffect(() => {
    applyVizelTheme(resolvedTheme, targetSelector, disableTransitionOnChange);
  }, [resolvedTheme, targetSelector, disableTransitionOnChange]);

  // Listen for system theme changes
  useEffect(() => {
    const cleanup = createVizelSystemThemeListener((newSystemTheme) => {
      setSystemTheme(newSystemTheme);
    });

    return cleanup;
  }, []);

  const setTheme = useCallback(
    (newTheme: VizelTheme) => {
      setThemeState(newTheme);
      storeVizelTheme(storageKey, newTheme);
    },
    [storageKey]
  );

  const value = useMemo<VizelThemeState>(
    () => ({
      theme,
      resolvedTheme,
      systemTheme,
      setTheme,
    }),
    [theme, resolvedTheme, systemTheme, setTheme]
  );

  return <VizelThemeContext.Provider value={value}>{children}</VizelThemeContext.Provider>;
}

// packages/vue/src/components/VizelThemeProvider.vue
<script setup lang="ts">
import {
  applyVizelTheme,
  createVizelSystemThemeListener,
  getStoredVizelTheme,
  getVizelSystemTheme,
  resolveVizelTheme,
  storeVizelTheme,
  VIZEL_DEFAULT_THEME,
  VIZEL_DEFAULT_THEME_STORAGE_KEY,
  type VizelResolvedTheme,
  type VizelTheme,
  type VizelThemeProviderOptions,
  type VizelThemeState,
} from "@vizel/core";
import { computed, onBeforeUnmount, onMounted, provide, ref, watch } from "vue";
import { VIZEL_THEME_CONTEXT_KEY } from "./VizelThemeContext.ts";

export interface VizelThemeProviderProps extends VizelThemeProviderOptions {}

const props = withDefaults(defineProps<VizelThemeProviderProps>(), {
  defaultTheme: VIZEL_DEFAULT_THEME,
  storageKey: VIZEL_DEFAULT_THEME_STORAGE_KEY,
  disableTransitionOnChange: false,
});

const theme = ref<VizelTheme>(getStoredVizelTheme(props.storageKey) ?? props.defaultTheme);
const systemTheme = ref<VizelResolvedTheme>(getVizelSystemTheme());

const resolvedTheme = computed(() => resolveVizelTheme(theme.value, systemTheme.value));

function setTheme(newTheme: VizelTheme) {
  theme.value = newTheme;
  storeVizelTheme(props.storageKey, newTheme);
}

const themeState: VizelThemeState = {
  get theme() {
    return theme.value;
  },
  get resolvedTheme() {
    return resolvedTheme.value;
  },
  get systemTheme() {
    return systemTheme.value;
  },
  setTheme,
};

provide(VIZEL_THEME_CONTEXT_KEY, themeState);

let cleanup: (() => void) | null = null;

onMounted(() => {
  // Apply initial theme
  applyVizelTheme(resolvedTheme.value, props.targetSelector, props.disableTransitionOnChange);

  // Listen for system theme changes
  cleanup = createVizelSystemThemeListener((newSystemTheme) => {
    systemTheme.value = newSystemTheme;
  });
});

// Watch for resolved theme changes
watch(resolvedTheme, (newResolvedTheme) => {
  applyVizelTheme(newResolvedTheme, props.targetSelector, props.disableTransitionOnChange);
});

onBeforeUnmount(() => {
  if (cleanup) {
    cleanup();
  }
});
</script>

<template>
  <slot />
</template>
