// packages/svelte/src/components/VizelSlashMenuEmpty.svelte
<script lang="ts" module>
import type { Snippet } from "svelte";

export interface VizelSlashMenuEmptyProps {
  /** Custom class name */
  class?: string;
  /** Custom content */
  children?: Snippet;
}
</script>

<script lang="ts">
let { class: className, children }: VizelSlashMenuEmptyProps = $props();
</script>

<div class="vizel-slash-menu-empty {className ?? ''}" data-vizel-slash-menu-empty="">
  {#if children}
    {@render children()}
  {:else}
    No results
  {/if}
</div>

// packages/vue/src/components/VizelSlashMenuEmpty.vue
<script setup lang="ts">
import { useSlots } from "vue";

export interface VizelSlashMenuEmptyProps {
  /** Custom class name */
  class?: string;
}

defineProps<VizelSlashMenuEmptyProps>();

const slots = useSlots();
</script>

<template>
  <div :class="['vizel-slash-menu-empty', $props.class]" data-vizel-slash-menu-empty="">
    <slot v-if="slots.default" />
    <template v-else>No results</template>
  </div>
</template>
