// packages/react/src/components/VizelToolbarDefault.tsx
import type { Editor } from "@vizel/core";
import {
  createVizelToolbarActions,
  formatVizelTooltip,
  groupVizelToolbarActions,
  isVizelToolbarDropdownAction,
  type VizelLocale,
  type VizelToolbarActionItem,
  vizelDefaultToolbarActions,
} from "@vizel/core";
import { Fragment } from "react";
import { useVizelState } from "../hooks/useVizelState.ts";
import { VizelIcon } from "./VizelIcon.tsx";
import { VizelToolbarButton } from "./VizelToolbarButton.tsx";
import { VizelToolbarDivider } from "./VizelToolbarDivider.tsx";
import { VizelToolbarDropdown } from "./VizelToolbarDropdown.tsx";

export interface VizelToolbarDefaultProps {
  editor: Editor;
  className?: string;
  /** Custom toolbar actions — supports both simple actions and dropdown actions */
  actions?: readonly VizelToolbarActionItem[];
  /** Locale for translated labels */
  locale?: VizelLocale;
}

/**
 * The default toolbar content for VizelToolbar.
 * Provides formatting buttons grouped by category with dividers between groups.
 * Supports both simple button actions and dropdown menu actions.
 *
 * @example
 * ```tsx
 * <VizelToolbar>
 *   <VizelToolbarDefault editor={editor} />
 * </VizelToolbar>
 * ```
 */
export function VizelToolbarDefault({
  editor,
  className,
  actions,
  locale,
}: VizelToolbarDefaultProps) {
  // Subscribe to editor state changes to update active/enabled states
  useVizelState(editor);

  const effectiveActions: readonly VizelToolbarActionItem[] =
    actions ?? (locale ? createVizelToolbarActions(locale) : vizelDefaultToolbarActions);
  const groups = groupVizelToolbarActions(effectiveActions);

  return (
    <div className={`vizel-toolbar-content ${className ?? ""}`} data-vizel-toolbar="">
      {groups.map((group, groupIndex) => (
        <Fragment key={group[0]?.group ?? groupIndex}>
          {groupIndex > 0 && <VizelToolbarDivider />}
          {group.map((action) =>
            isVizelToolbarDropdownAction(action) ? (
              <VizelToolbarDropdown key={action.id} editor={editor} dropdown={action} />
            ) : (
              <VizelToolbarButton
                key={action.id}
                action={action.id}
                onClick={() => action.run(editor)}
                isActive={action.isActive(editor)}
                disabled={!action.isEnabled(editor)}
                title={formatVizelTooltip(action.label, action.shortcut)}
              >
                <VizelIcon name={action.icon} />
              </VizelToolbarButton>
            )
          )}
        </Fragment>
      ))}
    </div>
  );
}

// packages/vue/src/components/VizelToolbarDefault.vue
<script setup lang="ts">
import type { Editor } from "@vizel/core";
import {
  createVizelToolbarActions,
  formatVizelTooltip,
  groupVizelToolbarActions,
  isVizelToolbarDropdownAction,
  type VizelLocale,
  type VizelToolbarActionItem,
  vizelDefaultToolbarActions,
} from "@vizel/core";
import { computed } from "vue";

import { useVizelState } from "../composables/useVizelState.ts";
import VizelIcon from "./VizelIcon.vue";
import VizelToolbarButton from "./VizelToolbarButton.vue";
import VizelToolbarDivider from "./VizelToolbarDivider.vue";
import VizelToolbarDropdown from "./VizelToolbarDropdown.vue";

export interface VizelToolbarDefaultProps {
  /** The editor instance */
  editor: Editor;
  /** Custom class name */
  class?: string;
  /** Custom toolbar actions — supports both simple actions and dropdown actions */
  actions?: readonly VizelToolbarActionItem[];
  /** Locale for translated UI strings */
  locale?: VizelLocale;
}

const props = defineProps<VizelToolbarDefaultProps>();

const effectiveActions = computed(
  () =>
    props.actions ??
    (props.locale ? createVizelToolbarActions(props.locale) : vizelDefaultToolbarActions)
);

// Subscribe to editor state changes to update active/enabled states
const editorStateVersion = useVizelState(() => props.editor);

const groups = computed(() => {
  void editorStateVersion.value;
  return groupVizelToolbarActions(effectiveActions.value);
});
</script>

<template>
  <div :class="['vizel-toolbar-content', $props.class]" data-vizel-toolbar>
    <template v-for="(group, groupIndex) in groups" :key="group[0]?.group ?? groupIndex">
      <VizelToolbarDivider v-if="groupIndex > 0" />
      <template v-for="action in group" :key="action.id">
        <VizelToolbarDropdown
          v-if="isVizelToolbarDropdownAction(action)"
          :editor="props.editor"
          :dropdown="action"
        />
        <VizelToolbarButton
          v-else
          :action="action.id"
          :is-active="action.isActive(props.editor)"
          :disabled="!action.isEnabled(props.editor)"
          :title="formatVizelTooltip(action.label, action.shortcut)"
          @click="action.run(props.editor)"
        >
          <VizelIcon :name="action.icon" />
        </VizelToolbarButton>
      </template>
    </template>
  </div>
</template>
