// packages/svelte/src/components/VizelToolbarColorPicker.svelte
<script lang="ts" module>
import type { Editor } from "@tiptap/core";
import type { VizelColorDefinition } from "@vizel/core";

export interface VizelToolbarColorPickerProps {
  /** The editor instance */
  editor: Editor;
  /** Color picker type */
  type: "textColor" | "highlight";
  /** Custom color palette */
  colors?: VizelColorDefinition[];
  /** Custom class name */
  class?: string;
  /** Enable custom color input (default: true) */
  allowCustomColor?: boolean;
  /** Enable recent colors (default: true) */
  showRecentColors?: boolean;
}
</script>

<script lang="ts">
import {
  addVizelRecentColor,
  getVizelRecentColors,
  VIZEL_HIGHLIGHT_COLORS,
  VIZEL_TEXT_COLORS,
} from "@vizel/core";
import { onMount, onDestroy } from "svelte";
import VizelColorPicker from "./VizelColorPicker.svelte";
import VizelIcon from "./VizelIcon.svelte";

let {
  editor,
  type,
  colors,
  class: className,
  allowCustomColor = true,
  showRecentColors = true,
}: VizelToolbarColorPickerProps = $props();

let isOpen = $state(false);
let recentColors = $state<string[]>([]);
let containerRef: HTMLDivElement | null = $state(null);

const colorPalette = $derived(colors ?? (type === "textColor" ? VIZEL_TEXT_COLORS : VIZEL_HIGHLIGHT_COLORS));

const currentColor = $derived.by(() => {
  if (type === "textColor") {
    return editor.getAttributes("textStyle").color;
  }
  return editor.getAttributes("highlight").color;
});

const isTextColor = $derived(type === "textColor");

const noneValues = $derived(isTextColor ? ["inherit"] : ["transparent"]);

// Load recent colors when dropdown opens
$effect(() => {
  if (isOpen && showRecentColors) {
    recentColors = getVizelRecentColors(type);
  }
});

function handleColorChange(color: string) {
  if (type === "textColor") {
    if (color === "inherit") {
      editor.chain().focus().unsetColor().run();
    } else {
      editor.chain().focus().setColor(color).run();
      addVizelRecentColor(type, color);
    }
  } else if (color === "transparent") {
    editor.chain().focus().unsetHighlight().run();
  } else {
    editor.chain().focus().toggleHighlight({ color }).run();
    addVizelRecentColor(type, color);
  }
  isOpen = false;
}

function handleClickOutside(event: MouseEvent) {
  if (containerRef && !containerRef.contains(event.target as Node)) {
    isOpen = false;
  }
}

onMount(() => {
  document.addEventListener("mousedown", handleClickOutside);
});

onDestroy(() => {
  document.removeEventListener("mousedown", handleClickOutside);
});

function getTriggerStyle(): string {
  if (isTextColor) {
    return `color: ${currentColor || "inherit"}`;
  }
  return `--highlight-color: ${currentColor || "transparent"}`;
}
</script>

<div
  bind:this={containerRef}
  class="vizel-color-picker {className ?? ''}"
  data-type={type}
>
  <button
    type="button"
    class="vizel-bubble-menu-button vizel-color-picker-trigger {currentColor ? 'has-color' : ''}"
    title={isTextColor ? "Text Color" : "Highlight"}
    data-action={type}
    style={getTriggerStyle()}
    onclick={() => (isOpen = !isOpen)}
  >
    {#if isTextColor}
      <VizelIcon name="textColor" />
    {:else}
      <VizelIcon name="highlighter" />
    {/if}
  </button>

  {#if isOpen}
    <div class="vizel-color-picker-dropdown">
      <VizelColorPicker
        colors={colorPalette}
        value={currentColor}
        label={isTextColor ? "Text color palette" : "Highlight color palette"}
        {allowCustomColor}
        {recentColors}
        {showRecentColors}
        {noneValues}
        onchange={handleColorChange}
      />
    </div>
  {/if}
</div>

// packages/vue/src/components/VizelToolbarColorPicker.vue
<script setup lang="ts">
import type { Editor } from "@tiptap/core";
import {
  addVizelRecentColor,
  getVizelRecentColors,
  VIZEL_HIGHLIGHT_COLORS,
  VIZEL_TEXT_COLORS,
  type VizelColorDefinition,
} from "@vizel/core";
import { computed, onMounted, onUnmounted, ref, watch } from "vue";
import VizelColorPicker from "./VizelColorPicker.vue";
import VizelIcon from "./VizelIcon.vue";

export interface VizelToolbarColorPickerProps {
  /** The editor instance */
  editor: Editor;
  /** Color picker type */
  type: "textColor" | "highlight";
  /** Custom color palette */
  colors?: VizelColorDefinition[];
  /** Custom class name */
  class?: string;
  /** Enable custom color input (default: true) */
  allowCustomColor?: boolean;
  /** Enable recent colors (default: true) */
  showRecentColors?: boolean;
}

const props = withDefaults(defineProps<VizelToolbarColorPickerProps>(), {
  allowCustomColor: true,
  showRecentColors: true,
});

const isOpen = ref(false);
const recentColors = ref<string[]>([]);
const containerRef = ref<HTMLDivElement | null>(null);

const colorPalette = computed(() => {
  return props.colors ?? (props.type === "textColor" ? VIZEL_TEXT_COLORS : VIZEL_HIGHLIGHT_COLORS);
});

const currentColor = computed(() => {
  if (props.type === "textColor") {
    return props.editor.getAttributes("textStyle").color;
  }
  return props.editor.getAttributes("highlight").color;
});

const isTextColor = computed(() => props.type === "textColor");

const noneValues = computed(() => (isTextColor.value ? ["inherit"] : ["transparent"]));

// Load recent colors when dropdown opens
watch(isOpen, (open) => {
  if (open && props.showRecentColors) {
    recentColors.value = getVizelRecentColors(props.type);
  }
});

function handleColorChange(color: string) {
  if (props.type === "textColor") {
    if (color === "inherit") {
      props.editor.chain().focus().unsetColor().run();
    } else {
      props.editor.chain().focus().setColor(color).run();
      addVizelRecentColor(props.type, color);
    }
  } else if (color === "transparent") {
    props.editor.chain().focus().unsetHighlight().run();
  } else {
    props.editor.chain().focus().toggleHighlight({ color }).run();
    addVizelRecentColor(props.type, color);
  }
  isOpen.value = false;
}

function handleClickOutside(event: MouseEvent) {
  if (containerRef.value && !containerRef.value.contains(event.target as Node)) {
    isOpen.value = false;
  }
}

onMounted(() => {
  document.addEventListener("mousedown", handleClickOutside);
});

onUnmounted(() => {
  document.removeEventListener("mousedown", handleClickOutside);
});

function getTriggerStyle() {
  if (isTextColor.value) {
    return { color: currentColor.value || "inherit" };
  }
  return { "--highlight-color": currentColor.value || "transparent" };
}
</script>

<template>
  <div
    ref="containerRef"
    :class="['vizel-color-picker', $props.class]"
    :data-type="props.type"
  >
    <button
      type="button"
      :class="['vizel-bubble-menu-button', 'vizel-color-picker-trigger', { 'has-color': currentColor }]"
      :title="isTextColor ? 'Text Color' : 'Highlight'"
      :data-action="props.type"
      :style="getTriggerStyle()"
      @click="isOpen = !isOpen"
    >
      <VizelIcon v-if="isTextColor" name="textColor" />
      <VizelIcon v-else name="highlighter" />
    </button>

    <div v-if="isOpen" class="vizel-color-picker-dropdown">
      <VizelColorPicker
        :colors="colorPalette"
        :value="currentColor"
        :label="isTextColor ? 'Text color palette' : 'Highlight color palette'"
        :allow-custom-color="props.allowCustomColor ?? true"
        :recent-colors="recentColors"
        :show-recent-colors="props.showRecentColors ?? true"
        :none-values="noneValues"
        @change="handleColorChange"
      />
    </div>
  </div>
</template>
