// packages/svelte/src/components/VizelBubbleMenuButton.svelte
<script lang="ts" module>
import type { Snippet } from "svelte";

export interface VizelBubbleMenuButtonProps {
  /** Whether the button is in active state */
  isActive?: boolean;
  /** Whether the button is disabled */
  disabled?: boolean;
  /** Tooltip title */
  title?: string;
  /** Custom class name */
  class?: string;
  /** Button content */
  children: Snippet;
  /** Click handler */
  onclick?: () => void;
  /** Action identifier for testing */
  action?: string;
}
</script>

<script lang="ts">
let {
  isActive = false,
  disabled = false,
  title,
  class: className,
  children,
  onclick,
  action,
}: VizelBubbleMenuButtonProps = $props();
</script>

<button
  type="button"
  {disabled}
  aria-pressed={isActive}
  class="vizel-bubble-menu-button {isActive ? 'is-active' : ''} {className ?? ''}"
  {title}
  data-active={isActive || undefined}
  data-action={action}
  {onclick}
>
  {@render children()}
</button>

// packages/vue/src/components/VizelBubbleMenuButton.vue
<script setup lang="ts">
export interface VizelBubbleMenuButtonProps {
  /** Whether the button is in active state */
  isActive?: boolean;
  /** Whether the button is disabled */
  disabled?: boolean;
  /** Tooltip title */
  title?: string;
  /** Custom class name */
  class?: string;
  /** Action identifier for testing */
  action?: string;
}

const props = defineProps<VizelBubbleMenuButtonProps>();

const emit = defineEmits<{
  click: [];
}>();
</script>

<template>
  <button
    type="button"
    :disabled="disabled"
    :aria-pressed="isActive"
    :class="['vizel-bubble-menu-button', { 'is-active': isActive }, $props.class]"
    :title="title"
    :data-active="isActive || undefined"
    :data-action="props.action"
    @click="emit('click')"
  >
    <slot />
  </button>
</template>
