// packages/react/src/components/VizelColorPicker.tsx
import {
  isVizelValidHexColor,
  normalizeVizelHexColor,
  type VizelColorDefinition,
} from "@vizel/core";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { VizelIcon } from "./VizelIcon.tsx";

export interface VizelColorPickerProps {
  /** Color palette to display */
  colors: readonly VizelColorDefinition[];
  /** Currently selected color */
  value?: string | undefined;
  /** Callback when color is selected */
  onChange: (color: string) => void;
  /** Label for accessibility */
  label?: string;
  /** Custom class name */
  className?: string;
  /** Enable custom HEX input (default: true) */
  allowCustomColor?: boolean;
  /** Recent colors to display */
  recentColors?: string[];
  /** Show recent colors section (default: true) */
  showRecentColors?: boolean;
  /** "None" option color values (e.g., ["transparent", "inherit"]) */
  noneValues?: string[];
  /** Label for recent colors section */
  recentLabel?: string;
  /** Placeholder for hex input */
  hexPlaceholder?: string;
  /** Title for apply button */
  applyTitle?: string;
  /** Aria label for apply button */
  applyAriaLabel?: string;
}

const GRID_COLUMNS = 4;
const DEFAULT_NONE_VALUES = ["transparent", "inherit"];

/**
 * A reusable color picker component with keyboard navigation and accessibility support.
 */
export function VizelColorPicker({
  colors,
  value,
  onChange,
  label = "Color palette",
  className,
  allowCustomColor = true,
  recentColors = [],
  showRecentColors = true,
  noneValues = DEFAULT_NONE_VALUES,
  recentLabel = "Recent",
  hexPlaceholder = "#000000",
  applyTitle = "Apply",
  applyAriaLabel = "Apply custom color",
}: VizelColorPickerProps) {
  const [inputValue, setInputValue] = useState("");
  const [focusedIndex, setFocusedIndex] = useState(-1);
  const swatchRefs = useRef<(HTMLButtonElement | null)[]>([]);
  const inputRef = useRef<HTMLInputElement>(null);

  // Build flat list of all selectable colors for keyboard navigation
  const allColors = useMemo(
    () => [...(showRecentColors ? recentColors : []), ...colors.map((c) => c.color)],
    [showRecentColors, recentColors, colors]
  );

  // Trim refs array when colors count decreases to prevent stale references
  useEffect(() => {
    if (swatchRefs.current.length > allColors.length) {
      swatchRefs.current.length = allColors.length;
    }
  }, [allColors.length]);

  // Calculate the offset for color palette indices (after recent colors)
  const paletteOffset = showRecentColors ? recentColors.length : 0;

  // Check if a color is a "none" value
  const isNoneValue = useCallback(
    (color: string): boolean => {
      return noneValues.includes(color);
    },
    [noneValues]
  );

  // Handle swatch selection
  const handleSelect = useCallback(
    (color: string) => {
      onChange(color);
      setInputValue("");
    },
    [onChange]
  );

  // Handle custom color input submit
  const handleInputSubmit = useCallback(() => {
    const normalized = normalizeVizelHexColor(inputValue);
    if (isVizelValidHexColor(normalized)) {
      onChange(normalized);
      setInputValue("");
    }
  }, [inputValue, onChange]);

  // Handle input keydown
  const handleInputKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === "Enter") {
      e.preventDefault();
      handleInputSubmit();
    }
  };

  // Keyboard navigation handler
  const handleKeyDown = useCallback(
    (e: React.KeyboardEvent, currentIndex: number) => {
      const totalColors = allColors.length;
      if (totalColors === 0) return;

      if (e.key === "Enter" || e.key === " ") {
        e.preventDefault();
        const selectedColor = allColors[currentIndex];
        if (selectedColor) {
          handleSelect(selectedColor);
        }
        return;
      }

      const newIndex = ((): number | null => {
        switch (e.key) {
          case "ArrowRight":
            return (currentIndex + 1) % totalColors;
          case "ArrowLeft":
            return (currentIndex - 1 + totalColors) % totalColors;
          case "ArrowDown":
            return Math.min(currentIndex + GRID_COLUMNS, totalColors - 1);
          case "ArrowUp":
            return Math.max(currentIndex - GRID_COLUMNS, 0);
          case "Home":
            return 0;
          case "End":
            return totalColors - 1;
          default:
            return null;
        }
      })();

      if (newIndex !== null) {
        e.preventDefault();
        setFocusedIndex(newIndex);
        swatchRefs.current[newIndex]?.focus();
      }
    },
    [allColors, handleSelect]
  );

  // Update input value when value prop changes
  useEffect(() => {
    if (value && !isNoneValue(value)) {
      setInputValue(value);
    } else {
      setInputValue("");
    }
  }, [value, isNoneValue]);

  // Focus first swatch or current value on mount
  useEffect(() => {
    const currentIndex = value ? allColors.indexOf(value) : -1;
    if (currentIndex >= 0) {
      setFocusedIndex(currentIndex);
    } else if (allColors.length > 0) {
      setFocusedIndex(0);
    }
  }, [allColors, value]);

  const isInputValid = isVizelValidHexColor(normalizeVizelHexColor(inputValue));
  const previewColor = isInputValid ? normalizeVizelHexColor(inputValue) : undefined;

  return (
    <div
      className={`vizel-color-picker-content ${className ?? ""}`}
      role="listbox"
      aria-label={label}
    >
      {/* Recent colors */}
      {showRecentColors && recentColors.length > 0 && (
        <div className="vizel-color-picker-section">
          <div className="vizel-color-picker-label">{recentLabel}</div>
          <div className="vizel-color-picker-recent">
            {recentColors.map((color, idx) => (
              <button
                key={color}
                ref={(el) => {
                  swatchRefs.current[idx] = el;
                }}
                type="button"
                role="option"
                aria-selected={value === color}
                aria-label={color}
                tabIndex={focusedIndex === idx ? 0 : -1}
                className={`vizel-color-picker-swatch ${value === color ? "is-active" : ""}`}
                onClick={() => handleSelect(color)}
                onKeyDown={(e) => handleKeyDown(e, idx)}
                style={{
                  backgroundColor: isNoneValue(color) ? "transparent" : color,
                }}
                data-color={color}
              >
                {isNoneValue(color) ? (
                  <span className="vizel-color-picker-none">
                    <VizelIcon name="x" />
                  </span>
                ) : null}
              </button>
            ))}
          </div>
        </div>
      )}

      {/* Color palette */}
      <div className="vizel-color-picker-section">
        <div className="vizel-color-picker-grid">
          {colors.map((colorDef, i) => {
            const idx = paletteOffset + i;
            return (
              <button
                key={colorDef.color}
                ref={(el) => {
                  swatchRefs.current[idx] = el;
                }}
                type="button"
                role="option"
                aria-selected={value === colorDef.color}
                aria-label={colorDef.name}
                tabIndex={focusedIndex === idx ? 0 : -1}
                className={`vizel-color-picker-swatch ${value === colorDef.color ? "is-active" : ""}`}
                onClick={() => handleSelect(colorDef.color)}
                onKeyDown={(e) => handleKeyDown(e, idx)}
                style={{
                  backgroundColor: isNoneValue(colorDef.color) ? "transparent" : colorDef.color,
                }}
                data-color={colorDef.color}
              >
                {isNoneValue(colorDef.color) ? (
                  <span className="vizel-color-picker-none">
                    <VizelIcon name="x" />
                  </span>
                ) : null}
              </button>
            );
          })}
        </div>
      </div>

      {/* HEX input with preview */}
      {allowCustomColor && (
        <div className="vizel-color-picker-input-row">
          <span
            className="vizel-color-picker-preview"
            style={{ backgroundColor: previewColor || "transparent" }}
            aria-hidden="true"
          />
          <input
            ref={inputRef}
            type="text"
            className="vizel-color-picker-input"
            placeholder={hexPlaceholder}
            value={inputValue}
            onChange={(e) => setInputValue(e.target.value)}
            onKeyDown={handleInputKeyDown}
            maxLength={7}
            aria-label="Custom color hex value"
          />
          <button
            type="button"
            className="vizel-color-picker-apply"
            onClick={handleInputSubmit}
            disabled={!isInputValid}
            title={applyTitle}
            aria-label={applyAriaLabel}
          >
            <VizelIcon name="check" />
          </button>
        </div>
      )}
    </div>
  );
}

// packages/vue/src/components/VizelColorPicker.vue
<script setup lang="ts">
import {
  isVizelValidHexColor,
  normalizeVizelHexColor,
  type VizelColorDefinition,
} from "@vizel/core";
import { computed, onMounted, ref, watch } from "vue";
import VizelIcon from "./VizelIcon.vue";

export interface VizelColorPickerProps {
  /** Color palette to display */
  colors: readonly VizelColorDefinition[];
  /** Currently selected color */
  value?: string;
  /** Label for accessibility */
  label?: string;
  /** Custom class name */
  class?: string;
  /** Enable custom HEX input (default: true) */
  allowCustomColor?: boolean;
  /** Recent colors to display */
  recentColors?: string[];
  /** Show recent colors section (default: true) */
  showRecentColors?: boolean;
  /** "None" option color values (e.g., ["transparent", "inherit"]) */
  noneValues?: string[];
  /** Label for recent colors section */
  recentLabel?: string;
  /** Placeholder for hex input */
  hexPlaceholder?: string;
  /** Title for apply button */
  applyTitle?: string;
  /** Aria label for apply button */
  applyAriaLabel?: string;
}

const props = withDefaults(defineProps<VizelColorPickerProps>(), {
  label: "Color palette",
  allowCustomColor: true,
  recentColors: () => [],
  showRecentColors: true,
  noneValues: () => ["transparent", "inherit"],
  recentLabel: "Recent",
  hexPlaceholder: "#000000",
  applyTitle: "Apply",
  applyAriaLabel: "Apply custom color",
});

const emit = defineEmits<{
  /** Emitted when the selected color changes */
  change: [color: string];
}>();

const currentValue = computed(() => props.value);

const GRID_COLUMNS = 4;

const inputValue = ref("");
const focusedIndex = ref(-1);
const swatchRefs = ref<(HTMLButtonElement | null)[]>([]);
const inputRef = ref<HTMLInputElement | null>(null);

// Build flat list of all selectable colors for keyboard navigation
const allColors = computed(() => [
  ...(props.showRecentColors ? props.recentColors : []),
  ...props.colors.map((c) => c.color),
]);

// Trim refs array when colors count decreases to prevent stale references
watch(
  () => allColors.value.length,
  (newLength) => {
    if (swatchRefs.value.length > newLength) {
      swatchRefs.value.length = newLength;
    }
  }
);

// Calculate the offset for color palette indices (after recent colors)
const paletteOffset = computed(() => (props.showRecentColors ? props.recentColors.length : 0));

// Find color definition by color value
function findColorDef(color: string): VizelColorDefinition | undefined {
  return props.colors.find((c) => c.color === color);
}

// Get display name for a color
function getColorName(color: string): string {
  const def = findColorDef(color);
  return def?.name ?? color;
}

// Check if a color is a "none" value
function isNoneValue(color: string): boolean {
  return props.noneValues.includes(color);
}

// Handle swatch selection
function handleSelect(color: string) {
  emit("change", color);
  inputValue.value = "";
}

// Handle custom color input submit
function handleInputSubmit() {
  const normalized = normalizeVizelHexColor(inputValue.value);
  if (isVizelValidHexColor(normalized)) {
    emit("change", normalized);
    inputValue.value = "";
  }
}

// Handle input keydown
function handleInputKeyDown(e: KeyboardEvent) {
  if (e.key === "Enter") {
    e.preventDefault();
    handleInputSubmit();
  }
}

// Keyboard navigation handler
function handleKeyDown(e: KeyboardEvent, currentIndex: number) {
  const totalColors = allColors.value.length;
  if (totalColors === 0) return;

  if (e.key === "Enter" || e.key === " ") {
    e.preventDefault();
    const selectedColor = allColors.value[currentIndex];
    if (selectedColor) {
      handleSelect(selectedColor);
    }
    return;
  }

  const newIndex = ((): number | null => {
    switch (e.key) {
      case "ArrowRight":
        return (currentIndex + 1) % totalColors;
      case "ArrowLeft":
        return (currentIndex - 1 + totalColors) % totalColors;
      case "ArrowDown":
        return Math.min(currentIndex + GRID_COLUMNS, totalColors - 1);
      case "ArrowUp":
        return Math.max(currentIndex - GRID_COLUMNS, 0);
      case "Home":
        return 0;
      case "End":
        return totalColors - 1;
      default:
        return null;
    }
  })();

  if (newIndex !== null) {
    e.preventDefault();
    focusedIndex.value = newIndex;
    swatchRefs.value[newIndex]?.focus();
  }
}

// Update input value when value prop changes
watch(
  currentValue,
  (value) => {
    if (value && !isNoneValue(value)) {
      inputValue.value = value;
    } else {
      inputValue.value = "";
    }
  },
  { immediate: true }
);

// Focus first swatch or current value on mount
onMounted(() => {
  const currentIndex = currentValue.value ? allColors.value.indexOf(currentValue.value) : -1;
  if (currentIndex >= 0) {
    focusedIndex.value = currentIndex;
  } else if (allColors.value.length > 0) {
    focusedIndex.value = 0;
  }
});

const isInputValid = computed(() => isVizelValidHexColor(normalizeVizelHexColor(inputValue.value)));
const previewColor = computed(() =>
  isInputValid.value ? normalizeVizelHexColor(inputValue.value) : undefined
);
</script>

<template>
  <div
    :class="['vizel-color-picker-content', $props.class]"
    role="listbox"
    :aria-label="props.label"
  >
    <!-- Recent colors -->
    <div
      v-if="showRecentColors && props.recentColors && props.recentColors.length > 0"
      class="vizel-color-picker-section"
    >
      <div class="vizel-color-picker-label">{{ props.recentLabel }}</div>
      <div class="vizel-color-picker-recent">
        <button
          v-for="(color, idx) in recentColors"
          :key="color"
          :ref="(el) => { swatchRefs[idx] = el as HTMLButtonElement | null }"
          type="button"
          role="option"
          :aria-selected="currentValue === color"
          :aria-label="color"
          :tabindex="focusedIndex === idx ? 0 : -1"
          :class="['vizel-color-picker-swatch', { 'is-active': currentValue === color }]"
          :style="{ backgroundColor: isNoneValue(color) ? 'transparent' : color }"
          :data-color="color"
          @click="handleSelect(color)"
          @keydown="handleKeyDown($event, idx)"
        >
          <span v-if="isNoneValue(color)" class="vizel-color-picker-none"><VizelIcon name="x" /></span>
        </button>
      </div>
    </div>

    <!-- Color palette -->
    <div class="vizel-color-picker-section">
      <div class="vizel-color-picker-grid">
        <button
          v-for="(colorDef, i) in colors"
          :key="colorDef.color"
          :ref="(el) => { swatchRefs[paletteOffset + i] = el as HTMLButtonElement | null }"
          type="button"
          role="option"
          :aria-selected="currentValue === colorDef.color"
          :aria-label="colorDef.name"
          :tabindex="focusedIndex === paletteOffset + i ? 0 : -1"
          :class="['vizel-color-picker-swatch', { 'is-active': currentValue === colorDef.color }]"
          :style="{ backgroundColor: isNoneValue(colorDef.color) ? 'transparent' : colorDef.color }"
          :data-color="colorDef.color"
          @click="handleSelect(colorDef.color)"
          @keydown="handleKeyDown($event, paletteOffset + i)"
        >
          <span v-if="isNoneValue(colorDef.color)" class="vizel-color-picker-none"><VizelIcon name="x" /></span>
        </button>
      </div>
    </div>

    <!-- HEX input with preview -->
    <div v-if="allowCustomColor" class="vizel-color-picker-input-row">
      <span
        class="vizel-color-picker-preview"
        :style="{ backgroundColor: previewColor || 'transparent' }"
        aria-hidden="true"
      />
      <input
        ref="inputRef"
        type="text"
        class="vizel-color-picker-input"
        :placeholder="props.hexPlaceholder"
        :value="inputValue"
        maxlength="7"
        aria-label="Custom color hex value"
        @input="inputValue = ($event.target as HTMLInputElement).value"
        @keydown="handleInputKeyDown"
      >
      <button
        type="button"
        class="vizel-color-picker-apply"
        :disabled="!isInputValid"
        :title="props.applyTitle"
        :aria-label="props.applyAriaLabel"
        @click="handleInputSubmit"
      >
        <VizelIcon name="check" />
      </button>
    </div>
  </div>
</template>
